### ISSUE TITLE
wish you complete

### ISSUE THREAD

**Issue by baolitoumu** [HappyZ/dpt-tools#1]

**Comment by HappyZ** [comment]
lol thx, recently I was very busy in life but I can see the possibility (thx to the Internet again). The only question now is to understand how the system works and re-enable adb. I can send you the `boot.img` if you are interested. Let me know.

**Comment by baolitoumu** [comment]
Sorry, I don't know how it works at present, but I have been trying to use the API to operate. Do you know how to use the API to install the app, or to enter the test mode? The picture shows me trying to operate the API 。
![image](https://user-images.githubusercontent.com/14047916/43996508-98ce791e-9df6-11e8-9985-491a25b2b398.png)

**Comment by HappyZ** [comment]
The APIs do not provide any installation command. For testmode, it requires authentication with a private key, which unfortunately we do not have. Currently there are two paths to work on. One is to find a way to get into testmode, maybe bypassing API sanity check; two is to rebuild a working pkg to flash it onto the device. I am more comfortable working on the later. 

Yet, to be not very excited, both methods need private keys. Ah I wish I have uart to play with.

**Comment by HappyZ** [comment]
You can check https://github.com/HappyZ/dpt-tools/tree/master/extracted_apk/Dpcif/out/assets on all available APIs. I did find testmode public keys, yet there is no way to find private keys based on it.

**Comment by baolitoumu** [comment]
I believe some people get this, through some kind of relationship

HappyZ <notifications@github.com> 于2018年8月13日周一 下午5:51写道：

**Comment by baolitoumu** [comment]
I think the  private keys maby from a API

**Comment by HappyZ** [comment]
I don't think so. I know public keys are in API. There is no incentive for them to put private keys in there as well. I was exploring around and this method clearly fails. One potential way though, is to have minimal change to the pkg and flash it that disables the key check in testmode/recovery mode. In that way we will be able to easily do modifications.

**Comment by HappyZ** [comment]
Another interesting thing is [DCSS](https://www.sony.jp/digital-paper/developer/dcss/). If you are able to apply as a developer, you will get a key for DCSS (the kitting API). Not sure if that would help. I still believe the best method is to be able to flash pkg, or at least find a way to hack into it while it flashes pkg. 

A note: I could recompile the pkg, but unfortunately it also requires a private key.

**Comment by baolitoumu** [comment]
i have see the DCSS already ,But they have strict vetted，What's new

**Comment by HappyZ** [comment]
I think we may have to go through logistic hacks where you look into the logic bugs in web API, or other means through USB interface. The pkg part is unfortunately not gonna happen, unless we also get the private keys through some sort of "relationship" ;)
