### ISSUE TITLE
My broken device has been repaired. the rom space is enhanced to 128GB！

### ISSUE THREAD

**Issue by 6bigfire** [HappyZ/dpt-tools#100]
Thanks to HappyZ and shankerzhiwu for their help during this period!
HAHAHA!
![20190603123945](https://user-images.githubusercontent.com/21056561/58776903-c84a2300-85fe-11e9-87c8-b11ba0a85a50.jpg)

**Comment by worldzhang2010** [comment]
r u sure?

**Comment by 6bigfire** [comment]
> 你确定吗？
当然啦，折腾了一个多月啦，周边的端子和元件被整坏了好几个，差点就坚持不下去了。
![201906031348424](https://user-images.githubusercontent.com/21056561/58788276-263a3300-861e-11e9-99fb-665eb315e359.jpg)
![201906031348425](https://user-images.githubusercontent.com/21056561/58788282-289c8d00-861e-11e9-8e28-255386b4ff78.jpg)
![emmc芯片替换表](https://user-images.githubusercontent.com/21056561/58788308-381bd600-861e-11e9-8388-f4edae9c9ee9.jpg)

**Comment by HappyZ** [comment]
a unique device indeed 💯

**Comment by 6bigfire** [comment]
> a unique device indeed 💯

Thank you! I'm glad I've proved a viable path.

**Comment by kitsek** [comment]
Maybe u can write a tutorial on how to do it

**Comment by 6bigfire** [comment]
The tutorial is actually not very useful. The repair process and the tools used are too professional. Those who don't have the basic knowledge can't operate at all, but for those who know, it is enough to know that this is feasible.

**Comment by ghostwheel** [comment]
But who did it? Is it service that is available? What part was replaced?

Oh I see, it is related to this thread:
https://github.com/HappyZ/dpt-tools/issues/68

**Comment by 6bigfire** [comment]
here you are，a simple tutorial.
http://www.ifix.net.cn/thread-95242-1-1.html

**Comment by 6bigfire** [comment]
![8C3924B3-906A-4C0D-BC2C-B692FD98900D](https://user-images.githubusercontent.com/21056561/59623100-e3bc3e80-9165-11e9-81c5-1375a5aed40f.jpeg)
So happy, another device was enhanced.
This device installed a set of software purchased on Taobao, which caused the FwUpdater and initialization functions to be invalid, so ROOT could not be performed. After the hardware expansion, the system could not be re-initialized, resulting in an infinite loop.  
Finally, all the files of the boot partition was replaced by offline, the diagnosis function was re-enabled, and the system upgrade was completed by manually executing format_uaerdata.sh.  
😁😁😁😁😁😁Year
