### ISSUE TITLE
Problem, help. I've refresh the wrong version of PKG

### ISSUE THREAD

**Issue by devilzwy** [HappyZ/dpt-tools#102]
I've flashed the wrong version of PKG (cp1 1.4ver), actually my  device is Rp1(1.4ver) , Now its Stuck on welcome screen...how should i do

**Comment by devilzwy** [comment]
i can still use adb shell. but wifi cannot connected ,so i cannot use fw to re-flash the correct PKG(RP1)

**Comment by 6bigfire** [comment]
go to black block state and connect the usb cable.
python dpt-tools.py --diagnosis
install-pkg

**Comment by devilzwy** [comment]
> go to black block state and connect the usb cable.
> python dpt-tools.py --diagnosis
> install-pkg

Thanks a lot !  
should i unpack the correct PKG, and run apk which is included in ?

**Comment by HappyZ** [comment]
No, just flash the right system pkg. Don't unpack anything.

**Comment by devilzwy** [comment]
Sorry, but how to "install-PKG" in diagnosis mode?
could you show me the shell ?

**Comment by HappyZ** [comment]
download the latest `dpt-tool`:
```
>> python dpt-tools.py --diagnosis
...
>> help
...
>> install-pkg
<follow instructions>
```
and you should use the correct PKG

**Comment by devilzwy** [comment]
i tried "python dpt-tools.py --diagnosis "

**Comment by devilzwy** [comment]
After install-pkg - reboot ,  Stuck on welcome screen... i do use the correct PKG (RP1 ver1.4 10.6MB)
how long should i wait ? 
<img width="544" alt="WX20190607-235531@2x" src="https://user-images.githubusercontent.com/33926506/59117247-e2c62880-897f-11e9-9309-f4620c92799d.png">

Copy pkg to mass storage
Eject disk and Enter
Hold Home until flashing yellow
Stuck on Welcome Screen  for a looooooong time ( just like i flashed wrong PKG yesterday...)

**Comment by 6bigfire** [comment]
If you are using a Windows system, when the USB cable is connected, check which COM port is added in the serial port of the system device list. If it is COM8, enter the command line when you ask for your communication port: com8

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: devilzwy <notifications@github.com>
发送时间: Friday, June 7, 2019 10:43:16 PM
收件人: HappyZ/dpt-tools
抄送: H; Comment
主题: Re: [HappyZ/dpt-tools] Problem, help. I've refresh the wrong version of PKG (#102)


i tried "python dpt-tools.py --diagnosis ", but the shell show “Cannot open serial port /dev/tty.usbmodem01 due to could not open port '/dev/usbmodem01”

―

**Comment by devilzwy** [comment]
> If you are using a Windows system, when the USB cable is connected, check which COM port is added in the serial port of the system device list. If it is COM8, enter the command line when you ask for your communication port: com8

Thanks 6bigfire ,
Done this before, and now i've flashed the correct PKG ( 0x3 FwUpdater.pkg ) by install-pkg. ( following instructions ) .  But its still Stuck on welcome screen for a long time ( over 10min...) , should i flash 0x4 FwUpdater.pkg now? 
  
<img width="544" alt="WX20190607-235531@2x" src="https://user-images.githubusercontent.com/33926506/59121518-db584c80-898a-11e9-9310-dc1971be2faf.png">

**Comment by HappyZ** [comment]
to confirm, you see `welcome` but it stucks? are you still able to use adb? If so, you got stuff wrong in system partition.

And I kinda suggest you to upgrade to 1.6 directly based on the upgrade guide. Try to do official updates. Or apply the modded v1.6 fw pkg, using the same `install-pkg` method in diagnosis mode.

Let's hope you system partition and partition map didn't mess up. If it did, you need to carefully reformat the system partition...

**Comment by devilzwy** [comment]
> to confirm, you see `welcome` but it stucks? are you still able to use adb? If so, you got stuff wrong in system partition.

yes, I can use 'adb shell'  when `welcome`.

**Comment by devilzwy** [comment]
To HappyZ：
I think i got wrong stuff wrong in system partition when 0x3 (The modification will change your Android boot partition.) ,  could you tel me how to fix it

**Comment by HappyZ** [comment]
i suggest you to flash the official pkg and update to 1.6 first, then flash the modded official pkg v1.6

**Comment by devilzwy** [comment]
Thanks,
i do so ~

**Comment by emeng82** [comment]
I factory reset my device and now it cannot be connected with WiFi. I can connect it with command:
`dpt-tools --diagnosis`
But I have no idea what to do next to connect the device to WiFi. I tried to flash v1.6 with install-pkg, but it seems failed. 
I checked this thread, @HappyZ suggests to flash the official pkg first. I would like to know where to find the official pkg? Thanks a lot!
