### ISSUE TITLE
Upgrade didn't work (?)

### ISSUE THREAD

**Issue by ghostwheel** [HappyZ/dpt-tools#103]
I tried to upgrade using method 2. My original rooting happened on a mac, and was relatively old. I haven't really followed up and changed to newer versions of the hack.

Anyway, now I'm on windows 10, and I wanted to upgrade to the 1.6 fw version.
I managed to run dpt-tools using:
python .\dpt-tools.py -id .\deviceid.dat -k .\privatekey.dat -ip IP
I copied deviceid.dat and privatekey.dat from 
`C:\Users\<ME>\AppData\Roaming\Sony Corporation\Digital Paper App\DigitalPaperApp`

and I found IP from wifi properties on the RP1.

I entered fw, gave the path, and got back the Success! reply.
But, after my RP1 rebooted, it reported update failed, error 90001 or something like that. All my apps where still there, and when I go to "About phone" in settings, I still see 1.4.01

And the Digital Papers app still wants to update my firmware.

**Comment by HappyZ** [comment]
Is it the first time when you flash the 1.6 fw pkg? If so, then showing "update failed" means something wrong. 

First thing to check is if you have stuff in the mass storage disk. It could be highly likely you don't have enough space left in that mass storage (1Gigabyte in total) and the PKG unpacking failed in the middle. Please clear everything in that mass storage.

After that, if it still didn't work, since you are using one of the old mods, I would suggest you try to redo the initial rooting process, so I can make sure your update_script.sh is up-to-date. Let me know.

**Comment by ghostwheel** [comment]
Yes, this is the first time.
When I manually mount mass_storage the directory is empty.
I tried to manually copy FwUpdater.pkg there, and then reset and enter diagnostic mode again, and the DPT does seem to do something - the screen flashes a couple of times. But eventually it reboots to my old setup.

**Comment by HappyZ** [comment]
im guess then trying method 1 also didn't work for you? if you haven't tried, go ahead.

to understand why it is like this, can you boot into diagnosis mode, and print the update log?

```
>> diagnosis
...
>> cd /root
>> ls
...
updater_official_mod_xxx.log
...
>> cat updater_official_mod_xxx.log
```

**Comment by ghostwheel** [comment]
I didn't try method 1 yet. 

So, what I did now is method 2, enter fw, with the 1.6 Fw as before. Then it boots regularly, complains that update failed, and I'm back to 1.4. Then I enter diagnosis mode by powering off, pressing home button while pressing power button. 

There was nothing in /root, other than boot.img.bak
There is a file updater.log in /var/log/upstart
here it is:
```
0+1 records in
0+1 records out
644994 bytes (629.9KB) copied, 5.122372 seconds, 123.0KB/s
2+1 records in
2+1 records out
11022336 bytes (10.5MB) copied, 0.369701 seconds, 28.4MB/s
1+0 records in
1+0 records out
11022336 bytes (10.5MB) copied, 0.215627 seconds, 48.7MB/s
mount: mounting /dev/root on / failed: Device or resource busy
Terminated
Terminated
Error reading signature file /tmp/anim_sig.dat
mount: mounting /dev/root on / failed: Device or resource busy
Terminated
Terminated
Error reading signature file /tmp/anim_sig.dat
tar: invalid magic
tar: short read
mount: mounting /dev/root on / failed: Device or resource busy
Terminated
Terminated
Error reading signature file /tmp/anim_sig.dat
mount: mounting /dev/root on / failed: Device or resource busy
Terminated
Terminated
Error reading signature file /tmp/anim_sig.dat
mount: mounting /dev/root on / failed: Device or resource busy
Terminated
Terminated
Error reading signature file /tmp/anim_sig.dat
mount: mounting /dev/root on / failed: Device or resource busy
Terminated
Terminated
Error reading signature file /tmp/anim_sig.dat
mount: mounting /dev/root on / failed: Device or resource busy
Terminated
Terminated
Error reading signature file /tmp/anim_sig.dat
mount: mounting /dev/root on / failed: Device or resource busy
Terminated
Terminated
Error reading signature file /tmp/anim_sig.dat
mount: mounting /dev/root on / failed: Device or resource busy
Terminated
Terminated

```

**Comment by ghostwheel** [comment]
What is interesting is that now the Digital Paper App sees the DPT using the USB cable, which hadn't worked after I hacked it...

**Comment by ghostwheel** [comment]
OK, I used method 1. Well, partially. I flashed the official firmware, and all my apps seem to have survived and work (as far as I can tell).
I think I have an old version of the hack installed, maybe it has a different method of checking pkg files. Maybe it didn't even use pkg files....

(And while I was doing the official update, I realized that I didn't actually have a backup of all my documents.... just of one synced dir. I thought that once the App syncs with the device all is backed up, which of course it isn't!!! Maybe it would be wothwhile to point that out in the update process... so maybe I'm lucky that method 2 didn't work)

**Comment by HappyZ** [comment]
`mount: mounting /dev/root on / failed: Device or resource busy` this is the reason it failed.. huh..

**Comment by HappyZ** [comment]
@ghostwheel yea, the app sync function sucks..

**Comment by HappyZ** [comment]
closed as problem resolved by user
