### ISSUE TITLE
KoReader File Management

### ISSUE THREAD

**Issue by TheRealNewbie** [HappyZ/dpt-tools#106]
My nickname says it all. I didn't have any python experience at all but I managed to root my DPT RP1 and install KoReader following the guidelines here. My issue is with file management, within the storage folder I have about 190 folders with seemingly encrypted folder names (really long alpha numeric names) and once in there I can see which PDFs they hold. Is there a guide or something that makes navigation easier? Maybe through scanning the device and listing all ebooks or maybe putting all ebooks in a single folder?

Thanks

**Comment by HappyZ** [comment]
it is how s-o-n-y made the app.. you cannot and should not change the format/organization of files, otherwise the original app can no longer work/detect your files

I suggest you to manage pdfs for KOReader and those for the official apps separately..

**Comment by TheRealNewbie** [comment]
OK. Thanks. Keeping a fresh set of files makes sense.
Cheeers!
