### ISSUE TITLE
About changing DPI by "wm density"

### ISSUE THREAD

**Issue by grinning2015** [HappyZ/dpt-tools#109]
`adb shell`
- [x] `     su`
- [x] `     wm density 200`

it is found that wm command in adb shell can successfully change the system DPI
but the side effect is that the home menu icons become too large so that some icons are out of window.
i tried changing the icon png image size, with no effect.

Any way to avoid this?

**Comment by HappyZ** [comment]
you'll have to change the system framework to avoid it, as well as the app..
