### ISSUE TITLE
Maybe a guide on customizing home button(AppLauncher)?

### ISSUE THREAD

**Issue by Antiparadox** [HappyZ/dpt-tools#11]
Since we can evoke su in adb, could we somehow manipulate with the AppLauncher to include more functionalities? 
I am thinking about recreating the TAObao version of the home screen, say, adding a browser, or a general app catalog, etc.
It would be nice to have these additional features, since we've come so far.
Thanks!

**Comment by sisyphose** [comment]
yes，the would be a wonderful feather

**Comment by HappyZ** [comment]
There is a non-trivial way to customize the home button, as I added in README.md. I suspect taobao wrote their own Launcher that mimics the stock one, as the stock launcher does not have categories.

Ideally we need an app that automates all these.. but for now I get no time to implement it.

**Comment by Antiparadox** [comment]
Unfortunately I encounter AppLauncher Crash when I install shortcut of Android Settings and Browser into the home screen., using the fixed provided 
I have tried remove these two extra folders from dp-extension path, but it still crashes after I reboot the system.
Any idea what the issue might be?
Many thanks!

**Comment by HappyZ** [comment]
can you post what `adb logcat` says about applauncher?

**Comment by cypresstwist** [comment]
First of all - this is amazing work you guys are doing here.
Secondly - to be on point - some pictures of a modified menu would be of great value. And of a 3rd party Android app running on the device (maybe an EPUB reader or - I would love to see that - Mendeley Desktop?).

**Comment by JacobJacob** [comment]
Unfortunately AppLauncher has stopped.  my DPT-CP1 also crashed after i added a shorcut of android settings.

**Comment by JacobJacob** [comment]
> Unfortunately AppLauncher has stopped. my DPT-CP1 also crashed after i added a shorcut of android settings.

i tried to recovery the system image via DTG mode with the bakup of  boot.img , the AppLauncher also crashed when reboot.

any guys could help to resolve this issue ?  Thanks.

**Comment by Antiparadox** [comment]
you have to reinitialize the DPT in order to recover, this is the only way.
First, make sure that you backup all your files in your PC,
then, run:
adb shell am start -a com.sony.capas.setting.intent.action.SETTINGS_TOP
This will evoke settings for you
Then, under Device settings, reinitialize the DPT,
Hope this will help

**Comment by JacobJacob** [comment]
> you have to reinitialize the DPT in order to recover, this is the only way.
> First, make sure that you backup all your files in your PC,
> then, run:
> adb shell am start -a com.sony.capas.setting.intent.action.SETTINGS_TOP
> This will evoke settings for you
> Then, under Device settings, reinitialize the DPT,
> Hope this will help

Thanks Antiparadox,  the reset function of DPT system can't work. 
i'm trying flash system.img  following this guide : https://github.com/HappyZ/dpt-tools/issues/14
hope the home applauncher will come back.

**Comment by JacobJacob** [comment]
it's so confusing , the issue still is  here .

**Comment by Antiparadox** [comment]
flash system would not work, since all your modification remains in cache.
Could you explain what you did to dp_extensions?

**Comment by Antiparadox** [comment]
Also, try to go to Android settings:
adb shell am start -a android.settings.SETTINGS
then clear all cache.
If the issue is still there, try sent me a cap of log cat app launcher.apk, this would probably reveal something suspicious

**Comment by JacobJacob** [comment]
I modified a new icon for android setting function via URI which could be launched in CMD ADB following guide. And pull the folder dp_extensions to my local Mac. That’s all, reboot and crashed.

**Comment by JacobJacob** [comment]
Maybe I can’t use ADB since i’ve update boot.img morning.

**Comment by Antiparadox** [comment]
Have you tried reinitialized DPT already? This is how I get rid of this issue.
could you post contents of the modified .xml file?

**Comment by JacobJacob** [comment]
Ive tried reset function in Android stetting before flash boot.img and system.img. 
And insert the reset button besides power.
Later I submit the xml.

**Comment by Antiparadox** [comment]
TO clarify, reset in Android settings won't work, since the original Sony is untouched.
Did you reinitialize DPT in Sony DPT settings? (The settings menu that come with Sony software)

**Comment by que01** [comment]
> Also, try to go to Android settings:
> adb shell am start -a android.settings.SETTINGS
> then clear all cache.
> If the issue is still there, try sent me a cap of log cat app launcher.apk, this would probably reveal something suspicious

My situation is the same as him @JacobJacob . I tried this method but it didn't work.

**Comment by HappyZ** [comment]
thanks @Antiparadox for helping.

and @JacobJacob @que01, flashing `system.img` does not work because it remains the cache of that app state in user data. You have to do a hard reset from `initialize digital paper` in Sony's `DPT settings`. It will reformat all user data.

But if you want to wait a bit till next weekend, I shall be able to find where the cache is and fix this without wiping out the entire system.

**Comment by JacobJacob** [comment]
> thanks @Antiparadox for helping.
> 
> and @JacobJacob @que01, flashing `system.img` does not work because it remains the cache of that app state in user data. You have to do a hard reset from `initialize digital paper` in Sony's `DPT settings`. It will reformat all user data.
> 
> But if you want to wait a bit till next weekend, I shall be able to find where the cache is and fix this without wiping out the entire system.

Many thanks @HappyZ , @Antiparadox  for your all reply.

i found  i can't access Sony's DPT settings since the Applauncher crashed. and so far i lost the ADB shell bcz i've flash a bakup of boot.img. maybe i should flash a boot.img with ADB shell.

here is my xml for your review:
`<?xml version="1.0" encoding="utf-8"?>

<Application name="AndroidSetting" type="System" version="1">
    <LauncherEntry name="AndroidSetting" category="Launcher" uri="intent:#Intent;component=com.android.settings/.Settings;end" string="STR_ICONMENU_9999" icon="ic_homemenu_androidsetting.png" order="999"/>
</Application>
`

**Comment by JacobJacob** [comment]
<?xml version="1.0" encoding="utf-8"?>

<Application name="AndroidSetting" type="System" version="1">
    <LauncherEntry name="AndroidSetting" category="Launcher" uri="intent:#Intent;component=com.android.settings/.Settings;end" string="STR_ICONMENU_9999" icon="ic_homemenu_androidsetting.png" order="999"/>
</Application>

**Comment by JacobJacob** [comment]
`<?xml version="1.0" encoding="utf-8"?>

<Application name="AndroidSetting" type="System" version="1">
    <LauncherEntry name="AndroidSetting" category="Launcher" uri="intent:#Intent;component=com.android.settings/.Settings;end" string="STR_ICONMENU_9999" icon="ic_homemenu_androidsetting.png" order="999"/>
</Application>`

**Comment by JacobJacob** [comment]
![xmlcapture](https://user-images.githubusercontent.com/7627796/49355447-96fda280-f702-11e8-9a39-c954c58e23c9.PNG)

**Comment by que01** [comment]
>`initialize digital paper` in Sony's `DPT settings`
it can't work

**Comment by JacobJacob** [comment]
So, any ideas for me to wipe ALL  current configurations of DPT system , Guys?

**Comment by HappyZ** [comment]
> > `initialize digital paper` in Sony's `DPT settings`
> > it can't work

Did you remove the folders you added and then do the reset? 

FYI, while helping Antiparadox, I also asked Antiparadox to do the following before the reset:
1. Go to Android settings (via adb), and open `Apps` and clear the cache for AppLauncher.
2. And clear `dalvik-cache` of the system: (in adb sudo)
```
cd /data/dalvik-cache/
rm *
reboot
```

**Comment by HappyZ** [comment]
This issue is weird to me as I can't reproduce what happened to you all. If you have the folder that causes this malfunction, can you zip it and send it to me so I can try it? I modified many times that crash the ExtensionManagerService but once I changed it back it's working fine.. I'll have more time to dig more next weekend.

**Comment by JacobJacob** [comment]
> This issue is weird to me as I can't reproduce what happened to you all. If you have the folder that causes this malfunction, can you zip it and send it to me so I can try it? I modified many times that crash the ExtensionManagerService but once I changed it back it's working fine.. I'll have more time to dig more next weekend.

Thanks a lot @HappyZ , let me know you email address for zip sending and if you need other logs of current devices.

**Comment by HappyZ** [comment]
> > This issue is weird to me as I can't reproduce what happened to you all. If you have the folder that causes this malfunction, can you zip it and send it to me so I can try it? I modified many times that crash the ExtensionManagerService but once I changed it back it's working fine.. I'll have more time to dig more next weekend.
> 
> Thanks a lot @HappyZ , let me know you email address for zip sending and if you need other logs of current devices.

use yz@9pm.me

**Comment by que01** [comment]
> This issue is weird to me as I can't reproduce what happened to you all. If you have the folder that causes this malfunction, can you zip it and send it to me so I can try it? I modified many times that crash the ExtensionManagerService but once I changed it back it's working fine.. I'll have more time to dig more next weekend.

It seems to be because I run command `chmod 0644 *` in /etc/dp_extensions/ ? how to fix it ?

**Comment by HappyZ** [comment]
Possibly. You need to do `chmod 0755 <folder/path>`  for all folders under `/etc/dp_extensions/`.

**Comment by que01** [comment]
> Possibly. You need to do `chmod 0755 <folder/path>` for all folders under `/etc/dp_extensions/`.

........it work!..........please update the readme.md!!!!

**Comment by JacobJacob** [comment]
> > Possibly. You need to do `chmod 0755 <folder/path>` for all folders under `/etc/dp_extensions/`.
> 
> ........it work!..........please update the readme.md!!!!

cool !

**Comment by HappyZ** [comment]
> > Possibly. You need to do `chmod 0755 <folder/path>` for all folders under `/etc/dp_extensions/`.
> 
> ........it work!..........please update the readme.md!!!!

cheers! I have added to readme.md one more line of `cd MyTemplate`

**Comment by que01** [comment]
> > > Possibly. You need to do `chmod 0755 <folder/path>` for all folders under `/etc/dp_extensions/`.
> > 
> > 
> > ........it work!..........please update the readme.md!!!!
> 
> cheers! I have added to readme.md one more line of `cd MyTemplate`

Very thanks for you .  and hope everyone could avoid this problem

**Comment by JacobJacob** [comment]
> > Possibly. You need to do `chmod 0755 <folder/path>` for all folders under `/etc/dp_extensions/`.
> 
> ........it work!..........please update the readme.md!!!!

@que01 did you just change the permission of the MyTemplate folder ? i found  i've delete this folder yesterday.

**Comment by JacobJacob** [comment]
although i've finished  the flash process,  the app installed yesterday , such as Kindle, is still in my DPT-CP1. so funny.

**Comment by que01** [comment]
> > > Possibly. You need to do `chmod 0755 <folder/path>` for all folders under `/etc/dp_extensions/`.
> > 
> > 
> > ........it work!..........please update the readme.md!!!!
> 
> @que01 did you just change the permission of the MyTemplate folder ? i found i've delete this folder yesterday.

i deleted it , and run 'chmod 0644 * '  when the cwd is  /etc/dp_extensions/.  
and i  just change the permission(755) for **/etc/dp_extensions/*** folder

**Comment by HappyZ** [comment]
I have found where the `cache` is that causes the un-recoverable issue. Will update `README.md`.

**Comment by JacobJacob** [comment]
My dpt-cp1 home  Applauncher has come back from yesterday evening lost. 
Thanks a lot for @Antiparadox @HappyZ @que01 
As all your recommendations , i've done the following steps to solve this issue:
1, ADB shell, chmod 0755 /etc/dp_extensions/*
2, install a third party launcher app - nolauncher
3, with nolauncher , launch the function  initialize digital paper in Sony's DPT settings

Thanks all your help.

**Comment by JacobJacob** [comment]
<img width="563" alt="screen shot 2018-12-03 at 23 29 56" src="https://user-images.githubusercontent.com/7627796/49383292-5e39e980-f753-11e8-8c6d-7adad789d550.png">

**Comment by cypresstwist** [comment]
Thank you JacobJacob. It looks amazing.

**Comment by DeeDive** [comment]
> My dpt-cp1 home Applauncher has come back from yesterday evening lost.
> Thanks a lot for @Antiparadox @HappyZ @que01
> As all your recommendations , i've done the following steps to solve this issue:
> 1, ADB shell, chmod 0755 /etc/dp_extensions/*
> 2, install a third party launcher app - nolauncher
> 3, with nolauncher , launch the function initialize digital paper in Sony's DPT settings
> 
> Thanks all your help.

@JacobJacob Hi, how could u push your *.png file to the device? I use the command "adb root“ & ”adb remount" but it does not work. Error : read-only  Thanks:)
