### ISSUE TITLE
About Chinese fonts

### ISSUE THREAD

**Issue by grinning2015** [HappyZ/dpt-tools#110]
i believe there are many chinese users.
do you find that the chinese characters look rather strange on RP1?
i found that some fonts for chinese declared in /system/etc/fonts.xml are missing in /system/fonts

i made some changes to file fonts.xml, and now the chinese web pages rendering effect imroves.
but some chinese characters in APP's UI still look wired.

**Comment by grinning2015** [comment]
>https://pan.baidu.com/s/1SO0ualS7YIIjDSw7N9awQg  pass:1jf3 

`adb push fonts/fonts.xml /sdcard/Download
adb push fonts/fallback_fonts.xml /sdcard/Download
adb push fonts/system_fonts.xml /sdcard/Download
adb push fonts/fonts_split_1_common.xml /sdcard/Download
adb push fonts/fonts_split_2_sku_C.xml /sdcard/Download
adb push fonts/fonts_split_2_sku_J.xml /sdcard/Download
adb push fonts/fonts_split_2_sku_U.xml /sdcard/Download
adb push fonts/fonts_split_3_others.xml /sdcard/Download

adb push fonts/SourceHanSansCN-Bold.otf /sdcard/Download
adb push fonts/SourceHanSansCN-Light.otf /sdcard/Download
adb push fonts/SourceHanSansCN-Regular.otf /sdcard/Download
adb push fonts/SourceHanSansHWSC-Bold.otf /sdcard/Download
adb push fonts/SourceHanSansHWSC-Regular.otf /sdcard/Download
adb push fonts/SourceHanSansJP-Regular.otf /sdcard/Download
adb push fonts/SourceHanSansKR-Regular.otf /sdcard/Download
adb push fonts/SourceHanSansTW-Regular.otf /sdcard/Download
adb push fonts/FZLanTingXiHei.ttf /sdcard/Download

adb.exe shell
su
mount -o rw,remount /system

rename /system/etc/fonts.xml /system/etc/fonts.xml.bak
rename /system/etc/fallback_fonts.xml /system/etc/fallback_fonts.xml.bak
rename /system/etc/system_fonts.xml /system/etc/system_fonts.xml.bak
rename /system/etc/fonts_split_1_common.xml /system/etc/fonts_split_1_common.xml.bak
rename /system/etc/fonts_split_2_sku_C.xml /system/etc/fonts_split_2_sku_C.xml.bak
rename /system/etc/fonts_split_2_sku_J.xml /system/etc/fonts_split_2_sku_J.xml.bak
rename /system/etc/fonts_split_2_sku_U.xml /system/etc/fonts_split_2_sku_U.xml.bak
rename /system/etc/fonts_split_3_others.xml /system/etc/fonts_split_3_others.xml.bak

cp /sdcard/Download/fonts.xml /system/etc/fonts.xml
cp /sdcard/Download/fallback_fonts.xml /system/etc/fallback_fonts.xml
cp /sdcard/Download/system_fonts.xml /system/etc/system_fonts.xml
cp /sdcard/Download/fonts_split_1_common.xml /system/etc/fonts_split_1_common.xml
cp /sdcard/Download/fonts_split_2_sku_C.xml /system/etc/fonts_split_2_sku_C.xml
cp /sdcard/Download/fonts_split_2_sku_J.xml /system/etc/fonts_split_2_sku_J.xml
cp /sdcard/Download/fonts_split_2_sku_U.xml /system/etc/fonts_split_2_sku_U.xml
cp /sdcard/Download/fonts_split_3_others.xml /system/etc/fonts_split_3_others.xml

rm -rf /sdcard/Download/fonts.xml
rm -rf /sdcard/Download/fallback_fonts.xml
rm -rf /sdcard/Download/system_fonts.xml
rm -rf /sdcard/Download/fonts_split_1_common.xml
rm -rf /sdcard/Download/fonts_split_2_sku_C.xml
rm -rf /sdcard/Download/fonts_split_2_sku_J.xml
rm -rf /sdcard/Download/fonts_split_2_sku_U.xml
rm -rf /sdcard/Download/fonts_split_3_others.xml

chown root:root -R /system/etc/fonts.xml
chown root:root -R /system/etc/fallback_fonts.xml
chown root:root -R /system/etc/system_fonts.xml
chown root:root -R /system/etc/fonts_split_1_common.xml
chown root:root -R /system/etc/fonts_split_2_sku_C.xml
chown root:root -R /system/etc/fonts_split_2_sku_J.xml
chown root:root -R /system/etc/fonts_split_2_sku_U.xml
chown root:root -R /system/etc/fonts_split_3_others.xml

chmod 644 /system/etc/fonts.xml
chmod 644 /system/etc/fallback_fonts.xml
chmod 644 /system/etc/system_fonts.xml
chmod 644 /system/etc/fonts_split_1_common.xml
chmod 644 /system/etc/fonts_split_2_sku_C.xml
chmod 644 /system/etc/fonts_split_2_sku_J.xml
chmod 644 /system/etc/fonts_split_2_sku_U.xml
chmod 644 /system/etc/fonts_split_3_others.xml


cp /sdcard/Download/SourceHanSansCN-Bold.otf /system/fonts
cp /sdcard/Download/SourceHanSansCN-Light.otf /system/fonts/
cp /sdcard/Download/SourceHanSansCN-Regular.otf /system/fonts/
cp /sdcard/Download/SourceHanSansHWSC-Bold.otf /system/fonts/
cp /sdcard/Download/SourceHanSansHWSC-Regular.otf /system/fonts/
cp /sdcard/Download/SourceHanSansJP-Regular.otf /system/fonts/
cp /sdcard/Download/SourceHanSansKR-Regular.otf /system/fonts/
cp /sdcard/Download/SourceHanSansTW-Regular.otf /system/fonts/
cp /sdcard/Download/FZLanTingXiHei.ttf /system/fonts/
rm -rf /sdcard/Download/SourceHanSansCN-Bold.otf
rm -rf /sdcard/Download/SourceHanSansCN-Light.otf
rm -rf /sdcard/Download/SourceHanSansCN-Regular.otf
rm -rf /sdcard/Download/SourceHanSansHWSC-Bold.otf
rm -rf /sdcard/Download/SourceHanSansHWSC-Regular.otf
rm -rf /sdcard/Download/SourceHanSansJP-Regular.otf
rm -rf /sdcard/Download/SourceHanSansKR-Regular.otf
rm -rf /sdcard/Download/SourceHanSansTW-Regular.otf
rm -rf /sdcard/Download/FZLanTingXiHei.ttf

chown root:root -R /system/fonts/SourceHanSansCN-Bold.otf
chmod 644 /system/fonts/SourceHanSansCN-Bold.otf
chown root:root -R /system/fonts/SourceHanSansCN-Light.otf
chmod 644 /system/fonts/SourceHanSansCN-Light.otf
chown root:root -R /system/fonts/SourceHanSansCN-Regular.otf
chmod 644 /system/fonts/SourceHanSansCN-Regular.otf
chown root:root -R /system/fonts/SourceHanSansHWSC-Bold.otf
chmod 644 /system/fonts/SourceHanSansHWSC-Bold.otf
chown root:root -R /system/fonts/SourceHanSansHWSC-Regular.otf
chmod 644 /system/fonts/SourceHanSansHWSC-Regular.otf
chown root:root -R /system/fonts/SourceHanSansJP-Regular.otf
chmod 644 /system/fonts/SourceHanSansJP-Regular.otf
chown root:root -R /system/fonts/SourceHanSansKR-Regular.otf
chmod 644 /system/fonts/SourceHanSansKR-Regular.otf
chown root:root -R /system/fonts/SourceHanSansTW-Regular.otf
chmod 644 /system/fonts/SourceHanSansTW-Regular.otf
chown root:root -R /system/fonts/FZLanTingXiHei.ttf
chmod 644 /system/fonts/FZLanTingXiHei.ttf

reboot
`

**Comment by HappyZ** [comment]
you can write a wiki page about it

**Comment by dorapocket** [comment]
Link failed, could you please send it again? Thx!

**Comment by grinning2015** [comment]
> Link failed, could you please send it again? Thx!

Try:
https://pan.baidu.com/s/1G9Zt7npJfBt9ycWCXA0QXQ 
with code:
uxhc

**Comment by janejcw** [comment]
why os can't run the code :  adb. exe shell  how to solve that?

**Comment by yefeiyu** [comment]
The phonetic symbols are garbled, and the Google sans and roboto fonts of Google can't be solved.

![diag](https://user-images.githubusercontent.com/4845104/155491445-3e930548-1cb4-496a-b5cb-3dfec6ced205.png)

**Comment by ZhangHang** [comment]
@grinning2015 @HappyZ 

Thanks！
Have a nice day

**Comment by qzydustin** [comment]
Here is the elegant guide to optimizing Chinese fonts without extra fonts: https://blog.qzydustin.com/posts/sony-digital-paper-chinese/

@HappyZ If you want, you can add the link or content to the wiki.
