### ISSUE TITLE
Ways to Connect through USB ethernet

### ISSUE THREAD

**Issue by jss-cmyk** [HappyZ/dpt-tools#112]
dpt-tools uses wifi to call API.
Is there a way to do it through USB? just like what DPA does.

**Comment by HappyZ** [comment]
janten had an intro to do this: https://github.com/janten/dpt-rp1-py/blob/master/docs/linux-ethernet-over-usb.md

I didn't add it to my implementation.

**Comment by jss-cmyk** [comment]
Great

**Comment by jss-cmyk** [comment]
> janten had an intro to do this: https://github.com/janten/dpt-rp1-py/blob/master/docs/linux-ethernet-over-usb.md
> 
> I didn't add it to my implementation.

put an ipv6 addr in dpt-tools, not working.
even hard-coded the base_url, still not working

**Comment by HappyZ** [comment]
which method you tried exactly didn't work? i can confirm his method works

**Comment by jss-cmyk** [comment]
ifconfig, find ipv6 address like [fe80::xxxxxx%en1]:8443, not working
Using ddms software, the ipv6 address is different, but still not working.
It says, unable to connect to host [fe80xxxx]

**Comment by HappyZ** [comment]
try to ping it, if you cannot ping, that means you did not do it right
