### ISSUE TITLE
Please help, failed  on 0x3 Obtain Android ADB (Root) Access

### ISSUE THREAD

**Issue by flyingfishsg** [HappyZ/dpt-tools#115]
Please help. I exactly follow the ultimate guide to install every thing.  After using fw to install the FwUpdater.pkg, as instructed, I tried to adb devices as instructed "And you can run adb devices on your computer to see if your DPT appears (it may take a while to boot ADBD after DPT boots up, if you have waited for >1min, try to unplug and plug back in the cable, and do adb kill-server && adb devices several times, it eventually will come up! Fully tested)."

But I didn't see any thing. I unplugged and replugged the device and run the adb devices command again. Nothing shows up.  

What happened ? 

I though after obtain Android ADB access, I can directly use the adb commend to install android app without entering the diagnosis  mode. 

Am I right ? What should I do ?

Thank you very much.

**Comment by HappyZ** [comment]
what system were you using?

Windows needs adb drivers

MacOS needs to reboot or logout-and-login (pretty much) every time you want to use it (driver bug)

**Comment by flyingfishsg** [comment]
You rock, Man !  Thank you for your prompt reply. I am using a macbook pro. But after rebooting my macbook pro, I did the whole thing. Even re fw the Fwupdater.  After the device reboot to normal, I tried the adb devices command.  It is the same. Nothing shows up.  

Another thing I do not understand is that every time I closed the old window of the terminal and the new one.  Even I have checked the installation of Python in the new windows. I am not able to run "python dpt-tools.py -ip xxxxxx" as before.  I need to reinstall the home brew and python and "pip install httpsig pyserial urllib3 requests" again in order to successfully to run "python dpt-tools.py" 

I am an illiterate on terminal thing. :-(  

Please help.

**Comment by HappyZ** [comment]
can you check on mac with `sudo dmesg` in terminal before and after you plug in the cable? your device should show up

if so, which version did you use for your dpt? 

regarding python, you can check if `python -V` shows the same version in new terminal vs after homebrew version. if not, you need to set up the environment correctly, or maybe using `which python3` and run `python3` instead (maybe python3.5 or 3.6 depends on your homebrew installation)

**Comment by flyingfishsg** [comment]
Problem sovled.  To help others, I wrote a Chinese article to explain everything I did.

https://zhuanlan.zhihu.com/p/73046759

**Comment by HappyZ** [comment]
I suggest you create a new page in wiki and copy that over to help others, your choice
