### ISSUE TITLE
can't access the Sony DPT-RP1 storage 

### ISSUE THREAD

**Issue by flyingfishsg** [HappyZ/dpt-tools#117]
After following HappyZ's instruction, solved all problems and booted up with the E Ink launcher. After successfully installed some APPs including Koreader, I found out that I had no way to import files to the device.  I can't see the Sony's storage on my MacBook pro.  I downloaded and installed android file transfer app on my mac but failed to connect to the Sony . 
How can I access the internal storage of the hacked Sony device ?   

Many thanks

**Comment by HappyZ** [comment]
usually i just do `adb push` to `/sdcard/` mounting point..

**Comment by flyingfishsg** [comment]
> usually i just do `adb push` to `/sdcard/` mounting point..

Man, it is so pro.  is there anyway we can drag and drop ?

**Comment by HappyZ** [comment]
lol

what if you go to developer mode and change it to storage? i never tried

**Comment by flyingfishsg** [comment]
> lol
> 
> what if you go to developer mode and change it to storage? i never tried

My hero, how to ?   A million thanks

**Comment by HappyZ** [comment]
just go to Android settings, and go to Developer Options and there's USB mode (or similar), change that to USB storage

**Comment by flyingfishsg** [comment]
I went to the Developer options. Only thing relevant is the USB debugging. Can't find other setting related with file transfer or usb storage.  Finally manage to use airdroid to address my problems. Not perfect though.

**Comment by HappyZ** [comment]
not sure but maybe you can also try `android file transfer` ?
