### ISSUE TITLE
dpt-tools connection issue

### ISSUE THREAD

**Issue by yogi08** [HappyZ/dpt-tools#119]
Hi HappyZ,

My firmware is 1.4. after open the DP in normal mode and enable WIFI.

it reports to me the following information:

! Err: did not find  or
[error] Cannot authenticate. Make sure your id, key, and ip addresses are correct.

The following is my commands:
python dpt-tools.py -ip myip

I checked my IP from the router which is correct. How to resolve this issue?

**Comment by 6bigfire** [comment]
ping your device

**Comment by yogi08** [comment]
ping the ip address, return ok. when the DP in diagnosis mode, it also could connect. only the normal mode can not connect.

**Comment by HappyZ** [comment]
Try to find the key and id files manually.

**Comment by yogi08** [comment]
where can I find these files？ what is the key and id represent. is the id be the device id number in digital paper app

**Comment by yogi08** [comment]
I got these files from digital paper app. finally get connected. however , when I install the fw. pkg, it reports to me "unable to update, error code ".
