### ISSUE TITLE
Stuck on welcome screen after restore-bootimg and get-su-bin

### ISSUE THREAD

**Issue by qppq** [HappyZ/dpt-tools#12]
I used both `restore-bootimg` (with boot-1.4.01.16100-mod-happyz-181118.img) and `get-su-bin`. Judging from the output, they both seemed successful (md5sum were also correct). However, after I restart the device it gets stuck on the welcome screen. I don't get a password prompt and don't think I enabled encryption.

I tried to access it through adb and while the device is visible, it is unauthorized even though I have the adbkey (and adbkey.pub) in my .android directory. Restoring the original boot.img.bak works and lets the device boot normally.

EDIT: I just tried to use your boot-1.4.01.16100.img and it also gets stuck on the welcome screen. I noticed that my version (1.2.01.04200, [boot.img.bak.zip](https://github.com/HappyZ/dpt-tools/files/2610632/boot.img.bak.zip)) is pretty old. I could try to update it through the Digital Paper App but I am not sure whether that is safe now that I used your script.

**Comment by HappyZ** [comment]
Oh yea, you should update to the latest version before using the code. Yes, you can still update your DPT via the official app. After doing so, you can try the script again.

**Comment by qppq** [comment]
I was able to obtain adb & sudo after updating to 1.4.01.16100. Thanks!
