### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by qiebin** [HappyZ/dpt-tools#120]
Sony has release new version,1.6.02.06240. hope it can still be brick

 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by HappyZ** [comment]
didn't have time looking into it yet.. but hey, you can unpack the pkg using the tool and check it yourself!

**Comment by qiebin** [comment]
I just freshed the fw,and it works


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by lifuli123** [comment]
这个版本的能成功吗？
在他的列表里，这个版本应该在8月份释放啊？
很好奇。
