### ISSUE TITLE
Error! Unable to update, Error code:900001

### ISSUE THREAD

**Issue by yogi08** [HappyZ/dpt-tools#121]
Hi, When I use fw to update fw.pkg, it reports the above error code as the title shows.

**Comment by HappyZ** [comment]
it's supposed to be like that

**Comment by yogi08** [comment]
ok. when i again use fw to update 1.4 version, it also reports this error and directly entering the previously opened  doc. i checked the memu, no app menu exist. is it means it fails

**Comment by HappyZ** [comment]
I need you to be precise. If you just following the root guide, it should
not give you anything in the menu.

To check if root is successful, 1) reboot and see if there are three bars
showing up during the boot, and 2) check if connect to pc, adb can
recognize your device in normal boot up.

To get the menu hack, you need to follow the app launcher hack wiki.

**Comment by yogi08** [comment]
thanks it works
