### ISSUE TITLE
app luncher

### ISSUE THREAD

**Issue by lifuli123** [HappyZ/dpt-tools#122]
![11111111111111](https://user-images.githubusercontent.com/22239909/61995664-e3e11f80-b0bd-11e9-8853-162a0109ec9e.png)
after reboot(press the power button)
I got the picture below which is different from your result.
when I press the app on the right, there is nothing in it (and I also install koreader)

I only want to brewers the internet and install app. 

I am a new guy and no nothing about this crack，can you help me about my question。thanks very much！！！！

**Comment by HappyZ** [comment]
> I got the picture below which is different from your result.

what does it look like..? you didn't attach the photo after you clicked "Apps"

also, please paste your logcat before and after you clicked "Apps" by connecting your device to pc and run `adb logcat`. I feel like you didn't run things correctly if Apps didn't show you the e-ink-launcher app. Did you install it? Check wiki https://github.com/HappyZ/dpt-tools/wiki/Suggested-Launcher-Mod the first step.

**Comment by lifuli123** [comment]
my dpt version is 1.6.02.06240。
when i click app ，there is nothing show 。

**Comment by lifuli123** [comment]
follow your step exeactlly !!
my dpt sw version is the newest one! 
have you test it on this version.its my fault,sorry !
i only copy your cmd of your demo and i dont konw the meaning of each step.

**Comment by lifuli123** [comment]
fist step CMD used to install is
adb install -r E-Ink-Launcher_0.1.4.apk and at this step only this comand.
second step ,i copy all the second step comamds to the commamd shell at the first time. 
then power off ,power on.
i find click app.,nothing happen.
then repeat the fist step again.
then at the second step,i copy each command of the second step to the comand shell and click enter.power off,power on.click app,still nothing!

**Comment by lifuli123** [comment]
i will test it again and past the figure tomorrow! thanks a lot

**Comment by HappyZ** [comment]
i have tested and it works for version 1.6.02.06240
