### ISSUE TITLE
dbc devices

### ISSUE THREAD

**Issue by lifuli123** [HappyZ/dpt-tools#124]
![image](https://user-images.githubusercontent.com/22239909/62206068-8b629880-b3c3-11e9-9109-23883bd6eef0.png)
![image](https://user-images.githubusercontent.com/22239909/62206101-9e756880-b3c3-11e9-9b09-60ab7560b23a.png)
![image](https://user-images.githubusercontent.com/22239909/62206192-ce247080-b3c3-11e9-8dce-43c64e26e619.png)
I use your new release to re-crack  my DPT ,this time I CANT GET THE DEVICE when use dbc devices.
Still plug and unplug the cable, still can not  GET THE DEVICE.

MY VERSION IS 1.6.02.06240

SORRY TO BOTTHER YOU!!!

**Comment by lifuli123** [comment]
sorry use wrong command string WHICH SHOULD BE ADB .
Repeat this process again,but still find device!!! it is sadly!!!
![Uploading image.png…]()

**Comment by HappyZ** [comment]
adb should run outside of dpt-tools. Go download adb from Android platform
and run it in terminal, without dpt-tools.


Yz

**Comment by HappyZ** [comment]
you can refer to this guide to get adb: https://www.xda-developers.com/install-adb-windows-macos-linux/

and then run it outside of dpt-tools in windows terminal like:
`C:\Users\xxx\> <path_to_adb>/adb.exe devices`

**Comment by lifuli123** [comment]
yes，it's ok！！！
thanks

**Comment by eshion** [comment]
![Uploading 屏幕快照 2019-08-01 01.15.36.png…]()
![Uploading 屏幕快照 2019-08-01 01.16.54.png…]()

I have encountered the same problem and can't to sole it. Any other suggestions?

**Comment by eshion** [comment]
<img width="640" alt="屏幕快照 2019-08-01 01 15 36" src="https://user-images.githubusercontent.com/1287467/62233675-9cc79700-b3fb-11e9-9416-c47c4e1d0b24.png">


<img width="436" alt="屏幕快照 2019-08-01 01 16 54" src="https://user-images.githubusercontent.com/1287467/62233628-86214000-b3fb-11e9-87c0-ac5cac657995.png">

I have encountered the same problem and can't to sole it. Any other suggestions?

**Comment by eshion** [comment]
after I reboot my mac, it's ok!!!

**Comment by HappyZ** [comment]
Yea for macbook there's a bug (blaming Apple). You'll have to log off and
log back in to make it work again.
