### ISSUE TITLE
unfortunately，iwnn ime has stopp

### ISSUE THREAD

**Issue by lifuli123** [HappyZ/dpt-tools#125]
how you guys input，its always give me the error：unfortunately，iwnn ime has stopp

**Comment by HappyZ** [comment]
Try to change you input method in Android settings. I don't remember the
details tho. Search for issues and see if there was one.

**Comment by ganhaoli** [comment]
I have encounter the same question, everytime I enter the search bar ,it says: iwnn ime has stopp.
Once I enter Android settings for input and language, it get crash.
So is there anyway to solve this question？

**Comment by ganhaoli** [comment]
通过安装第三方输入法，并在输入法app中选择默认输入法为IMEChinese，已经解决该问题。

**Comment by 0987363** [comment]
I upgrade to 1.6.50.14130, and crack, root.

Installed third input, selected default input.
But still crash when enter input and language of  android settings.
