### ISSUE TITLE
how to recover，App launcher 停止工作

### ISSUE THREAD

**Issue by Rex-yyb** [HappyZ/dpt-tools#126]
如题，我用官方镜像还原以后，发现菜单无法使用了。请问这个需要怎么刷呢

**Comment by HappyZ** [comment]
https://github.com/HappyZ/dpt-tools/wiki/The-Upgrade-Guide 这里有写

你需要先[重新获得adb](https://github.com/HappyZ/dpt-tools/wiki/The-Ultimate-Rooting-Guide#0x3-obtain-android-adb-root-access) 然后重新刷一遍[launcher mod](https://github.com/HappyZ/dpt-tools/wiki/Suggested-Launcher-Mod)

如果说你想要还原官方系统：需要先用adb删除`/data/system/ExtMgr.db`以及`/data/system/ExtMgr.db-journal`，然后才去刷official image

**Comment by CobainYe** [comment]
> https://github.com/HappyZ/dpt-tools/wiki/The-Upgrade-Guide 这里有写
> 
> 你需要先[重新获得adb](https://github.com/HappyZ/dpt-tools/wiki/The-Ultimate-Rooting-Guide#0x3-obtain-android-adb-root-access) 然后重新刷一遍[launcher mod](https://github.com/HappyZ/dpt-tools/wiki/Suggested-Launcher-Mod)
> 
> 如果说你想要还原官方系统：需要先用adb删除`/data/system/ExtMgr.db`以及`/data/system/ExtMgr.db-journal`，然后才去刷official image

3q,我试试

**Comment by Rex-yyb** [comment]
> https://github.com/HappyZ/dpt-tools/wiki/The-Upgrade-Guide 这里有写
> 
> 你需要先[重新获得adb](https://github.com/HappyZ/dpt-tools/wiki/The-Ultimate-Rooting-Guide#0x3-obtain-android-adb-root-access) 然后重新刷一遍[launcher mod](https://github.com/HappyZ/dpt-tools/wiki/Suggested-Launcher-Mod)
> 
> 如果说你想要还原官方系统：需要先用adb删除`/data/system/ExtMgr.db`以及`/data/system/ExtMgr.db-journal`，然后才去刷official image

adb 需要如何删除，有具体指令吗

**Comment by HappyZ** [comment]
你需要用adb：
```
adb shell mount -o rw,remount /system
adb shell rm -rf /etc/dp_extensions/AndroidSettings
adb shell rm -rf /etc/dp_extensions/Apps
adb shell rm /data/system/ExtMgr.db
adb shell rm /data/system/ExtMgr.db-journal
```
然后用`dpt-tools`刷[official image的mod](https://github.com/HappyZ/dpt-tools/wiki/PKGs-I-Made#officials)

这样就clean了 保险起见最好最后再reset一下device

**Comment by CobainYe** [comment]
我前面没有执行你这边列的前3个指令然后直接刷了官方系统，现在重新连接去执行前3个指令出现error: no devices/emulators found，还用管吗

**Comment by Rex-yyb** [comment]
> 你需要用adb：
> 
> ```
> adb shell mount -o rw,remount /system
> adb shell rm -rf /etc/dp_extensions/AndroidSettings
> adb shell rm -rf /etc/dp_extensions/Apps
> adb shell rm /data/system/ExtMgr.db
> adb shell rm /data/system/ExtMgr.db-journal
> ```
> 
> 然后用`dpt-tools`刷[official image的mod](https://github.com/HappyZ/dpt-tools/wiki/PKGs-I-Made#officials)
> 
> 这样就clean了 保险起见最好最后再reset一下device

我前面没有执行你这边列的前3个指令然后直接刷了官方系统，现在重新连接去执行前3个指令出现error: no devices/emulators found，还用管吗

**Comment by HappyZ** [comment]
写了一下tut： https://github.com/HappyZ/dpt-tools/wiki/The-Unroot-Guide

不管你不是launcher会crash么。。。

**Comment by Rex-yyb** [comment]
> 写了一下tut： https://github.com/HappyZ/dpt-tools/wiki/The-Unroot-Guide
> 
> 不管你不是launcher会crash么。。。

现在暂时没发现有崩溃

**Comment by Rex-yyb** [comment]
请问升级失败。
错误代码：9000001
这个如何处理。@

> 写了一下tut： https://github.com/HappyZ/dpt-tools/wiki/The-Unroot-Guide
> 
> 不管你不是launcher会crash么。。。

请问升级失败。
错误代码：9000001
这个如何处理。

**Comment by Rex-yyb** [comment]
> 写了一下tut： https://github.com/HappyZ/dpt-tools/wiki/The-Unroot-Guide
> 
> 不管你不是launcher会crash么。。。

还有一点就是，现在按照你写的wiki，操作完以后，显示升级失败，然后我使用系统的初始化电子纸，初始化失败。进来以后文件都有在。

**Comment by HappyZ** [comment]
升级失败是正常的 你得看你的系统是不是变成了你刷的版本
你刷完后 还有adb了吗 如果没有的话那就是刷成功了

如果你进diagnosis mode `/root/`下最新的log有说哪里失败了吗 

最后 初始化失败 我不太清楚是为什么 你有log 截图之类的吗

**Comment by Rex-yyb** [comment]
> 最后 初始化失败 我不太清楚是为什么 你有log 截图之类的吗

有很多updater的log，不懂你要哪一个。初始化失败是：我进入系统的初始化电子纸，然后点是，然后进行到一半，机子就自动关机了，再开机的时候，发现并没有删除任何东西。估计factory_reset脚本报错了？log的话需要如何查看，我用vi xx.log  就卡在那边动不了 了。

**Comment by HappyZ** [comment]
要最后一个 数字最大的那个就是最新的

你输入 cat xxx.log 把它print出来吧
