### ISSUE TITLE
Diagnosis with USB mode

### ISSUE THREAD

**Issue by kaleo211** [HappyZ/dpt-tools#127]
Hi,

I think I had done a stupid thing upgrading to the latest firmware of DPT-CP1 using DPA instead of this tool, cause I had rooted the system before. Now I can only stay within the current PDF reader mode, not able to access anything else, including wifi to get connect with MacOS.

I'm using MacOS, and trying to get into `diagnosis` mode, another issue suggested. Even the black squares shows on the screen, it seems the `python3 dpt-tools.py --diagnosis` command still not able to find it with following error message:
```
[info] It is also possible to interact with diagnosis mode with a serial terminal, such as putty.
>>> Black square on the screen? [yes/no]: yes
>>> Enter the serial port [/dev/tty.usbmodem01]: 
[error] Cannot open serial port /dev/tty.usbmodem01 due to module 'serial' has no attribute 'Serial'
```
Anyone else experienced this same problem before? Really appreciate any help!

**Comment by kaleo211** [comment]
The file `/dev/tty.usbmodem01` does exist on the Mac if this matters.

**Comment by elamarkant** [comment]
Use your own tty.usbmodem device path to replace the default /dev/tty.usbmodem01
You can ls /dev/tty.usb* if you know what you are doing

**Comment by HappyZ** [comment]
in terminal just do `ls /dev/tty.usb*` when you plug the device in

another note is MacOS has a bug that if it didn't appear after you plug in the cable, you have to log off and log back in to reload the driver. Then it will appear as normal. It will be the same case later for `adb`

**Comment by kaleo211** [comment]
Hi @HappyZ and @elamarkant 

Thank you for the help 👍 

It looks like it's my own python package error. I have to uninstall serial and install pyserial.
