### ISSUE TITLE
Stuck at "Please wait..."

### ISSUE THREAD

**Issue by elamarkant** [HappyZ/dpt-tools#128]
Hi all,

I upgrade from 1.4 to 1.6 in digtal paper app.
After reboot, I stuck at "Please wait..." dialog.
Is there anyone experienced the same thing?
What happened and should I wait or just press the cancel button in the dialog?

Many Thanks.

**Comment by elamarkant** [comment]
cancel the dialog and rebuild the note template
seems that upgrade may broke the note templates?

**Comment by elamarkant** [comment]
Found answer in
https://www.bountysource.com/issues/74348993-unfortunately-applauncher-has-stopped
many many thanks.

**Comment by HappyZ** [comment]
yep, it does.. but i thought i wrote the instructions?

**Comment by elamarkant** [comment]
Feel sorry to bother you...miss the whole block after "su"...
