### ISSUE TITLE
instructions no longer work with current Mac OS 

### ISSUE THREAD

**Issue by shanenfl** [HappyZ/dpt-tools#129]
Shanes-iMac:dpt-tools-master shane$ python3 dpt-tools.py 
Traceback (most recent call last):
  File "dpt-tools.py", line 8, in <module>
    from python_api.libDPT import DPT
  File "/Users/shaneambers/Downloads/dpt-tools-master/python_api/libDPT.py", line 7, in <module>
    import serial

**Comment by HappyZ** [comment]
you need to install `pyserial` for that

**Comment by shanenfl** [comment]
I installed pyserial, no go .

**Comment by HappyZ** [comment]
when you install via `pip install pyserial`, are you sure you are not installing it to python2 instead of python3?

try `pip --version` to see if it matches with your python3 version

and see if `pip3` works; or to ensure the right installation, do `python3 -m pip install pyserial`

**Comment by HappyZ** [comment]
remove serial packet as well as it may get wrong when `import serial`

closed assuming you have fixed the issue; we can reopen if problem persists

**Comment by shanenfl** [comment]
Shanes-iMac:dpt-rp1-py-master shane$ pip --version
pip 19.1.1 from /Users/Shane/anaconda3/lib/python3.7/site-packages/pip (python 3.7)

**Comment by shanenfl** [comment]
how do you remove 'serial packet'?
