### ISSUE TITLE
Can not connect to Digital Paper app

### ISSUE THREAD

**Issue by friedScale** [HappyZ/dpt-tools#133]
I'm using Windows 10 and the pkg I'm using is 1.6.02.06240

I lost my device Id and authkey file, due to loss of PC datas. so I tried to re-install digital paper app but it can not find my rpt-cp1.
whenever I connect use cable it tries to connect to rpt-cp1 but it silently failed. 

dpt-tools wasn't able to find find my machine without device id, I stuck in the stuation. I can not upgrade/downgrade PKGs or add wifi access point to my rpt-cp1.
(the rpt-cp1 can not find any Wifi access point except that I added via digital paper app in the past)

The diagnosis mode is still accessible, so I tried factory reset but it shows error message like below.
: line 28: DIAG_get_setid: not found
NG

Is there any way to find deviceId manuallly? or anyway to factory reset?

**Comment by HappyZ** [comment]
If you lost your authentication files, you need to reset your device from device settings.

If you want to reset it through diagnosis mode, you need to run `cd /usr/local/bin` and then `./factory_reset.sh`

**Comment by HappyZ** [comment]
also, why not reset it by pressing the reset button for 30s while the device is on?

**Comment by friedScale** [comment]
So  sorry for late response. 

I tried run factory_reset script in diagnosis mode but it shows error message below
: line 28: DIAG_get_setid: not found
NG

I also tried reset it by pushing reset button 30s' but it did not work somehow.

I think I missed something, I'll keep trying to find way. Thank you.

**Comment by Comf0rTS1997** [comment]
I found a way to solve the problem that the digital paper app is not able to find dpt when pairing.

1. Open device manager and check if there's any conflict ports in ports(COM&LPT) section. (For example, maybe there're two devices that were assigned COM3)
2. And, if there's conflict, try to figure out which one is dpt. (You can find when the device was plugged in from properties--> events)
3. Then you should change its port number(in properties -> port settings -> advanced) to any port that is not in use.
4. Save, and unplug the device.
5. Open digital paper app and try to pair again. 

Some background knowledge: https://github.com/janten/dpt-rp1-py/blob/master/docs/linux-ethernet-over-usb.md

**Comment by Comf0rTS1997** [comment]
Maybe you should add this to your guide? I guess you have said this is a known issue. @HappyZ

**Comment by HappyZ** [comment]
Thanks @Cmf0rTS1997  for helping, I'll close this unless issue persists at your end @friedScale
