### ISSUE TITLE
一个疑惑，为什么会有10086.cn这个东东

### ISSUE THREAD

**Issue by yuluhuang** [HappyZ/dpt-tools#134]
![3B614E7B-2CAE-4EDC-A8C6-9E39EB3A6E67](https://user-images.githubusercontent.com/5743499/64488024-fdf14e80-d274-11e9-8607-a805486213fa.png)
首先我要感谢作者的分享，今天偶然发现，傻瓜式操作非常给力。这个10086.cn和brower属同一个应用且不能删除，特此疑问

**Comment by HappyZ** [comment]
不知道呀 感觉可能是给中国团队做的。。

**Comment by yuluhuang** [comment]
已经将其删除
