### ISSUE TITLE
Can not use Digital Pager App to update firmware even if unrooted.

### ISSUE THREAD

**Issue by sanigo** [HappyZ/dpt-tools#138]
After unrooted, the app can connect the device using usb cable. But when trying to update the firmware, it seems that the app can not check for updates.

**Comment by HappyZ** [comment]
There should be no updates if you already flashed the latest firmware.. what do you mean by "the app cannot check for updates"?

**Comment by HappyZ** [comment]
I assumed the issue has been resolved as it's been a while. Please re-open the issue if problem still exists and we can discuss more.
