### ISSUE TITLE
Recover the entire system?

### ISSUE THREAD

**Issue by Antiparadox** [HappyZ/dpt-tools#14]
Hi, I think I have messed up with the AppLauncher entirely, trying to debug but there's simply not enough time since Final seasons are quickly approaching.
Is there anyway to wipe out the entire system to recover the device?
That would help so much!
Great many thanks for your effort!

**Comment by HappyZ** [comment]
Yea, so you can't boot up the system, or you can still?
You can unpack the original pkg (FwUpdate.pkg, I think I posted somewhere), and you get two files: `boot.img` and `system.img`.
If you flash `system.img` to `/dev/mmcblk0p9` it should be recovered.

**Comment by Antiparadox** [comment]
Thanks! Very appreciated, right now I can boot up the system, it's just that the AppLauncher crashes.
could you elaborate more on how to flash the boot_img? I haven't get into stuff much deeper yet...but soon will.
Thanks again!

**Comment by HappyZ** [comment]
Oh if you can still boot up the system, just use `fw` in the tool and you can upload the original pkg.

**Comment by Antiparadox** [comment]
Sorry but I think I do not quite understand your instructions.
Do you mean by updating the firmware using the official pkg?

**Comment by HappyZ** [comment]
Steps are (assuming you are using RP1):

On your computer (MacOS or Linux):

1. Download `https://www.sony.net/Products/DigitalPaperSystem/Software/DP/FwUpdater.pkg`
2. Unpack it using `https://github.com/HappyZ/dpt-tools/tree/master/fw_updater_packer_unpacker` (check README.md)
3. You will get `boot.img` and `system.img`

Then you need to go to diagnosis mode, and:

```
/usr/local/bin/mass_storage
```
This will mount a storage disk on your PC and you can put the `system.img` extracted from pkg.

Then press `ctrl + C` and:
```
mkdir /mnt/sdtmp
mount /dev/mmcblk0p16 /mnt/sdtmp
ls /mnt/sdtmp
```
The file `system.img` shall be there. Then:

```
sync
extract_sparse_file /mnt/sdtmp/system.img /dev/mmcblk0p9
sync
sync
```

This will wipe the entire system.

**Comment by HappyZ** [comment]
> Sorry but I think I do not quite understand your instructions.
> Do you mean by updating the firmware using the official pkg?

Yes that's what I meant.

**Comment by Antiparadox** [comment]
I might be dumb, but
how to use that tool exactly?
Thanks

**Comment by HappyZ** [comment]
> I might be dumb, but
> how to use that tool exactly?
> Thanks

I just updated the instructions above, check again.

**Comment by Antiparadox** [comment]
Many thanks!

**Comment by Antiparadox** [comment]
I am not quite sure about these instructions:
"quote:
Then you need to go to diagnosis mode, and:

/usr/local/bin/mass_storage
This will mount a storage disk on your PC and you can put the system.img extracted from pkg.
"
Could you clarify on this?
Thanks

**Comment by HappyZ** [comment]
Connect your DPT to the computer via USB cable, and run in terminal `python dpt-tools.py --diagnosis` and follow instruction to get into diagnosis mode. 
Then run `/usr/local/bin/mass_storage`. This will mount a storage disk on you computer.
You need to transfer the image `system.img` to the mounted storage disk.
Then eject that disk, and press `Ctrl + C` to stop the previous command.

Then continue what I was saying `mkdir` etc.

**Comment by Antiparadox** [comment]
However, when I am in diagnostic mode, nothing seems to happen after I do /usr/local/bin/mass_storage:

"from terminal:

Supported commands:
    `push-file`         -- transfer file to DPT at 800bps (=100Bps)
    `pull-file`         -- transfer file from DPT
    `backup-bootimg`    -- backup the boot img and download it to local device
    `restore-bootimg`   -- restore the boot img
    `get-su-bin`        -- enable `su` (root) in adb (beta, not well tested)
    `exit`/`quit`       -- leave the tool
    and many unix cmds (do not support less/head)

root #: /usr/local/bin/mass_storage

"
Am I getting something wrong? Really need some help there, thanks!

**Comment by HappyZ** [comment]
After you run the command, it supposes to "hault", waiting for you to kill the process. It is running, just check your computer and look for an additional disk.

What system are you using?

**Comment by Antiparadox** [comment]
Oh, I am so dumb not realizing that, thanks for your patience!
Now that I followed all the instructions,
do I just reboot the system then?

**Comment by HappyZ** [comment]
> Oh, I am so dumb not realizing that, thanks for your patience!
> Now that I followed all the instructions,
> do I just reboot the system then?

Yea after you finish everything, just `reboot &` and quit the app.

**Comment by Antiparadox** [comment]
Thanks, but it seems that the app launcher still crashes after this...
I might be screwed...but is there any other fix?

**Comment by HappyZ** [comment]
huh that's interesting.. have you tried factory reset?

**Comment by HappyZ** [comment]
and can you run `adb logcat` and see if you can find where applaunch crashes

**Comment by Antiparadox** [comment]
sure, but the terminal out put is a bit too long to fit the comment...
Can I email it to you?
Thanks!

**Comment by HappyZ** [comment]
sure, yz@9pm.me

**Comment by Antiparadox** [comment]
sure, I am restoring the boot-img after which I will send the feedback to you
Thanks again for your help today

**Comment by hitmoon** [comment]
@HappyZ  where can i download the FwUpdater.pkg for CP1, my system is damaged and I want to recover to original

**Comment by HappyZ** [comment]
@hitmoon how damaged? what did you do?

please open a new issue so I don't need to keep track on the closed ones

the official FwUpdater.pkg for DPT-CP1 should be accessible at `https://www.sony.net/Products/DigitalPaperSystem/Software/DP/FwUpdater_1.4.02.09061.pkg`

**Comment by HappyZ** [comment]
As a final comment, please check https://github.com/HappyZ/dpt-tools/issues/31 for recovering entire system (without removing caches).

**Comment by duckbill** [comment]
thanks
