### ISSUE TITLE
[PC] adb.exe cannot find devices after flashing fwupdater.pkg

### ISSUE THREAD

**Issue by anlandong** [HappyZ/dpt-tools#140]
Hi Happyz. Thanks for all the great work! I was updating my rp1 firmware yesterday to 1.6.02.06240 and the AppLauncher stopped working. I followed your instruction in the upgrade guide, and flashed the fwupdater.pkg you provided in the ultimate rooting guide for this version. I was able to use fw to flash the firmware, and receiving the "unable to update" message on the rp1. When I tried to use adb.exe to show devices, it just cannot see my devices. I tried rebooting both my rp1 and my PC, use adb kill-server && adb devices multiple times, but still nothing. I'm wondering if you have any idea that would help me to get the adb.exe to recognize the device? Thank you very much. 

![Capture](https://user-images.githubusercontent.com/29109381/67621714-940b1500-f7e0-11e9-8af8-ddc4e3f01f41.PNG)

**Comment by HappyZ** [comment]
does you windows machine recognize other android devices? can you make sure if your windows has driver installed correctly?

**Comment by anlandong** [comment]
Hi. I currently don't have any android device to test on. What driver did you mean? The Sony rp1 driver, or the android adb driver?

**Comment by HappyZ** [comment]
https://adb.clockworkmod.com/

this one

**Comment by HappyZ** [comment]
I assumed the issue has been resolved as it's been a while. Please re-open the issue if problem still exists and we can discuss more.

**Comment by jbschooley** [comment]
I'm having this issue now too... And yes adb does recognize my android
