### ISSUE TITLE
Update firmware 1.6.03.09261, Sony dpt rp1 rooted cannot sync DPA. HELP

### ISSUE THREAD

**Issue by shuoyang234** [HappyZ/dpt-tools#144]
I updated firmware 1.6.03.09261 for Sony Dpt rp1 rooted. After the update is complete, the device could'nt connect to the Digital paper app, press the home button without a menu, so Sony dpt rp1 could'nt wifi on and soft factory reset. Connect the computer to implement python dpt-tools :

" C:\python\dpt>python dpt-tools.py
[error] HTTPSConnectionPool(host='digitalpaper.local', port=8443): Max retries exceeded with url: /auth/nonce/08b098a9-0091-40ba-bf80-ca7541803fd0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03A368E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[error] cannot get nonce
[error] Cannot authenticate. Make sure your id, key, and ip addresses are correct."

Is there a way to hard reset Sony dpt rp1 without a soft factory reset? Help me

**Comment by HappyZ** [comment]
You should be able to connect to wifi automatically still. Find your device
IP address and run 'python dpt-tools.py -ip xxx' and it should connect, so
you can continue fixing the app launcher. Check the upgrade guide plz.

Did you reset device before updating? You shouldn't, as DPA recognizes your
device only if you have the right key, which is cleared if you reset. Same
as dpt-tools. That may be the reason DPA and dpt-tools cannot connect.

You can still use diagnosis mode and flash pkg. Turn on your device
directly into diagnosis mode (use 'python dpt-tools.py --diagnosis'). Then
just look at help and use command 'install-pkg'. Use this to get adb back.
And then recover applauncher, and then register your device with DPA.

Finally, short answer to your question, hard reset can be done by pressing
reset button for 10s of seconds.


happyz

**Comment by shuoyang234** [comment]
My Sony Dpt rp1 works again, thanks HappyZ.

**Comment by HappyZ** [comment]
Glad to hear, happy thanksgiving :)
