### ISSUE TITLE
about the FW update

### ISSUE THREAD

**Issue by lascqy** [HappyZ/dpt-tools#148]
I'm a new beginner and want to root or change language on my DPT-RP1 Japan version.
So I want to make some things clearly (forgive me if someone have asked these).
1. if I flash the device with the modified firmware( whether rooted or not), could I still update the firmware via the official Digital Paper App? or I could only do it manually?
2. if I unroot the device following the guide(flash the official  FW image ), should it act as the original one with any official features like the future FW update via the Digital Paper App?

**Comment by HappyZ** [comment]
1) Yes you can. The only thing is if you had the AppLauncher mod, then it is very likely AppLauncher will crash after the update. You will need to re-gain ADB and redo the AppLauncher mod.
2) Yes

**Comment by lascqy** [comment]
thank you for your  answer  and your work!!
