### ISSUE TITLE
How can i enable otg without touch?

### ISSUE THREAD

**Issue by Micronaive** [HappyZ/dpt-tools#149]
My rp1's touch can't work, so i want to enable otg so that I can use the mouse to control it.  I found some phones can enable otg by add one line of code(# usb otg diskdev_mount usbotg /mnt/usbotg auto /devices/platform/mt_usb /devices/platform/musbfsh_hdrc) to /system/etc/vold.fstab,  dose this has same effect on rp1? How can i do this through diagnosis mode?

**Comment by SweetZone** [comment]
My RP1’s touchscreen sometimes fails to work too, but when I charge it, touchscreen always came back.

**Comment by HappyZ** [comment]
Feel free to build the image yourself. You need to modify the Android system image and it's not modifiable directly through diagnosis (it won't be persistant).
