### ISSUE TITLE
Signer._sign() error

### ISSUE THREAD

**Issue by sartrism** [HappyZ/dpt-tools#15]
I add my data point that I could successfully root my device on Windows. But one thing I had to modify is Line 480 of libDPT.py from _sign(...) to sign(...). Otherwise it makes an error.

According to the latest httpsig package Signer object has no _sign attribute. https://github.com/ahknight/httpsig/blob/master/httpsig/sign.py

**Comment by HappyZ** [comment]
thx fixed
