### ISSUE TITLE
I use linux. Do I have to let my CP1 connect to a WIFI ?

### ISSUE THREAD

**Issue by linux40** [HappyZ/dpt-tools#150]
I saw CP1 could make itself as a access point, so I let my computer connect to the WIFI CP1 provide. I used `avahi-resolve` to get the ip address of `digitalpaper.local` and verified this address and the port `8080` in browser while `dpt-tools` (with `-ip x.x.x.x`) just gave me the following messages:
```
! Err: did not find  or
[error] Cannot authenticate. Make sure your id, key, and ip addresses are correct.
```
Then I read the unofficial linux guidance and got that the guidance recommend me to let CP1 connect another WIFI. But I have to switch on Windows to achieve this because the connection need Digital Paper App. Is there any relevance between the error and the way my computer connect to CP1?

**Comment by HappyZ** [comment]
The error probably isn't because of IP but it cannot find id and key files on you computer. The id and key files are generated by DPA and to use it on a different computer, you'll need to copy the two files. Check https://github.com/HappyZ/dpt-tools/blob/7dc48f45bc746ee43f1dd781fc33e47949dd77bc/python_api/libDPT.py#L606

**Comment by linux40** [comment]
Unfortunately, there is no way to get an id and a key of CP1 on linux. `dpt-rp1-py` does not work for CP1. Then I denoted that there is a digital paper app on android, and this app showed the id as a string of number, and the key displayed on CP1 is also a sequence of number. I saved these numbers in different file, and let `dpt-tools` connect CP1 again. This time, `dpt-tools` shows:
```
[error] https://x.x.x.x:8443/auth/nonce/xxxxxxx ## the number of id
[error] request error 404:
[error] * error_code: 40401
[error] * message: The designated resource was not found.
[error] cannot get nonce
[error] Cannot authenticate. Make sure your id, key, and ip addresses are correct.
```
What is the problem?

**Comment by linux40** [comment]
Oh, I'm wrong. `dpt-rp1-py` does work for CP1, see this [issue](https://github.com/janten/dpt-rp1-py/issues/16) for more informations.

Then I found an excellent [tutorial](https://github.com/janten/dpt-rp1-py/blob/master/docs/linux-ethernet-over-usb.md) to make my CP1 connect to my computer via USB.

Finally, `dpt-tools` detect my CP1. Thank you.
