### ISSUE TITLE
Stylus handwriting to DPApp shows briefly and disappears

### ISSUE THREAD

**Issue by milkmansson** [HappyZ/dpt-tools#152]
Hey HappyZ - first - amazing work.  Legend!

I'm crossposting from here - https://forum.xda-developers.com/general/help/idea-to-root-sonys-e-reader-dpt-rp1-t3654725/page23#post81497485 

I successfully rooted.  I wanted to troubleshoot my drawing tool of choice (OneNote). Sadly I got the same results as other posters on XDA.

I have only one problem, which is that any pencil strokes written (in Sony's app) to a PDF or to a new blank document show up for a moment, but then blink away a few moments afterwards. 
Opening a pre-existing hand-drawn document (one made before I rooted it) all the strokes showed briefly, then were removed completely (the file was left on the system, but effectively was blanked).
The trial PDF documents which ship with the device were also blanked out when i drew on them

I've gone as far as unrooting (leaving diagnosis in place) and this hasn't helped.  Interestingly when i factory reset the device my documents in /sdcard etc are not wiped.  This is factory resetting both before and after my 'unroot'.

Interestingly in Logcat I see many of these after my penstroke finishes:
E/document_foxit( 2647): report_error: 9, cannot set annotation creation time (-9) in add_element
E/document_foxit( 2647): report_error: 9, cannot set annotation modified time (-9) in add_element

There was another complaint somewhere (wanted to trap it again fresh but i've got to re-root to adb) where it complained about not being able to write like this:
(many of these)
E/document_foxit( 2547): report_error: 9, cannot set annotation modified time (-9) in add_element
E/document_foxit( 2547): report_error: 9, cannot set annotation creation time (-9) in add_element
E/document_foxit( 2547): report_error: 9, cannot set annotation modified time (-9) in add_element
W/ContentManager_com.sony.capas.contentmanager.utils.ExportManager$ExportThread$1( 2467): onProgress. progress 0.75.documentId : 9829e721-89c7-4a3d-b9fe-86ace35f765c ThreadID[97]
D/DocumentManager_ExportFile( 2547): ReaderCoreListener::complete(0, false) ThreadID[110]
E/DocumentManager_ExportFile( 2547): exportFile: failed to IDocument::save() ThreadID[110]
E/DocumentManager_ExportFile( 2547): exportFile: failed to IDocument::save(): error: 9, cannot set annotation modified time (-9) ThreadID[110]

And another episode about thumbnails.

Is there something I can do to help with any troubleshooting here?

**Comment by HappyZ** [comment]
Does it happen to all PDFs?  Maybe try to clear the DPT app's cache (and storage)?

**Comment by milkmansson** [comment]
HI HappyZ - will check thisevening (just came back from break) I'll let you know in a few hours!

**Comment by milkmansson** [comment]
Happens to PDF's and handwritten notes.  Have a small selection of commercial and homemade PDFs, as well as the note app (I tend to use graph paper mostly so I'd set that as default.)

Have done Clear Data and Clear Defaults on "DigitalPaperApp" (5.33Mb)  (version listed as 1.6.03.09261-eng.20190926.121755.  Have also done so for "CreateNotePro" 2.65Mb (version listed as 1.0) and this didn't help either.

Is there anything I can do to help diagnose this?  Thanks!!  (Sorry for delay - had to find quiet time to reroot etc)

**Comment by HappyZ** [comment]
If you have the full log it would be helpful.

From your log, it seems document with ID 9829e721-89c7-4a3d-b9fe-86ace35f765c is problematic (warnings, not errors). I wonder if that's related. You can go to your sdcard and find this folder. See if deleting that would address the problem. I suggest you back up the original documents first before doing so.

**Comment by HappyZ** [comment]
Close this as it's a long time ago.
