### ISSUE TITLE
输入rawdata --set_dump=boot_mode < /dev/urandom reboot  之后就不能连接dpt-rp1了

### ISSUE THREAD

**Issue by LoveSeriously** [HappyZ/dpt-tools#155]
设备管理器显示由之前的DPT-RP1 变为 Linux File-CD Gadget USB Device，
adb shell也连接不上，dpt-tools.py也连接不上了。

这是设备
![1580929598713](https://user-images.githubusercontent.com/52035617/73874112-dcc97400-488d-11ea-8810-79a88e296a97.jpg)

这是设备管理器
![image](https://user-images.githubusercontent.com/52035617/73873854-6298ef80-488d-11ea-91d1-3a10e53e8272.png)

这是命令行
![image](https://user-images.githubusercontent.com/52035617/73873917-82301800-488d-11ea-97f4-7d4e2586fed6.png)
![image](https://user-images.githubusercontent.com/52035617/73873976-9e33b980-488d-11ea-9644-c8f5bfff1f93.png)
![image](https://user-images.githubusercontent.com/52035617/73873947-93792480-488d-11ea-8e0b-d98e4b018e62.png)

**Comment by HappyZ** [comment]
You'll need to use the right serial port. For windows, it should be COMxx
