### ISSUE TITLE
install-pkg hangs using diagnosis mode

### ISSUE THREAD

**Issue by phsamuel** [HappyZ/dpt-tools#156]
I accidentally upgraded my dpt-rp1 after root. The AppLauncher crashes as other mentioned. 

I followed the upgrade guide and tried to apply the 3rd step of the rooting guide (the system version is 1.6.03.09261). The wifi didn't work and so I tried to use the diagnosis mode to install (using Mac Catalina). But the installation hangs (waited for a night already) and stuck with a black rectangle at the center and another black rectangle at the upper left corner (instead of three bars). I didn't dare to touch it for the moment. Any suggestions are welcome! 
![IMG_2576](https://user-images.githubusercontent.com/5240193/74539869-661f1d00-4f04-11ea-8b0e-62feaa911ca3.JPG)

**Comment by phsamuel** [comment]
It seems the problem was due to insufficient charge. Since the AppLauncher was not open. I didn't know how much charge I had. After I unplugged the usb adapter. It eventually asked me to charge the digital paper and is able to tun on again (AppLauncher is still not working). But I think I will charge overnight and try to go through the upgrade guide again. Thanks much for making this possible!

**Comment by HappyZ** [comment]
The 3 bars in the end would be your large black block. Yes, if the device is not charged beyond 60 I believe it will not continue flashing. I'm not sure about the behavior when you left with low power and use diagnosis mode to flash the image. It possibly checks battery as well. In any case, if you feel it stucks at flashing, you can check this https://github.com/HappyZ/dpt-tools/wiki/Unbrick-and-or-Skip-Uploaded-PKG. As long as you can get into diagnosis mode, you are safe to do whatever.

**Comment by phsamuel** [comment]
Thanks for the link! luckily it allows me to get into diagnosis mode again
and I can flash the image again. Everything is working great again! Thanks
for the tool again. It is super helpful!
