### ISSUE TITLE
Backup LadyHack Cracked Firmware, HELP NEEDED!

### ISSUE THREAD

**Issue by ghost** [HappyZ/dpt-tools#160]
I have a device currently is using LadyHack's 1500rmb cracked firmware. I am looking for a way where I can dump the whole system. This will be used for educational purpose only. My plan is to backup the whole system before and after activating the cracked firmware. I failed to connect device to adb and is thinking about using Titanium Backup

It seems that the only thing they did really well is with customizing ReLauncher. Before activating, LadyHack's version of ReLauncher is locked and will prompt to a page where I have to connect internet to verify and activate. After activation, it will work seamlessly.

Some feature I found with LadyHack's version of ReLauncher
1. Include App Launcher and file manage system.
2. In file manage system, you are able to view the original file name for files that are encrypted by Sony
3. Able to add icon to home button dropped down menus.

What I found interesting is that no matter I activate or not, I am able to bypass their activation lock and use the cracked android system, but ReLauncher will remained locked.

**Comment by sekkit** [comment]
use dd if=/dev/partitionname of=/mnt/xxx command to backup all partitions, as for large partition, use dd if=/dev/partitionname | gzip >  /mnt/xxx/back.gz (xxx is the sdcard mount point)
after you exported all the partitions, sent them to seckkit@gmail.com, I'll help you to decrypt it.

**Comment by eonminion** [comment]
> use dd if=/dev/partitionname of=/mnt/xxx command to backup all partitions, as for large partition, use dd if=/dev/partitionname | gzip > /mnt/xxx/back.gz (xxx is the sdcard mount point)
> after you exported all the partitions, sent them to [seckkit@gmail.com](mailto:seckkit@gmail.com), I'll help you to decrypt it.

**Comment by ghost** [comment]
> use dd if=/dev/partitionname of=/mnt/xxx command to backup all partitions, as for large partition, use dd if=/dev/partitionname | gzip > /mnt/xxx/back.gz (xxx is the sdcard mount point)
> after you exported all the partitions, sent them to [seckkit@gmail.com](mailto:seckkit@gmail.com), I'll help you to decrypt it.

Do you have skype or wechat? So we can further talk about this? I have send you information by your email.
