### ISSUE TITLE
1.6.50.14130 firmware is released!

### ISSUE THREAD

**Issue by junoh-moon** [HappyZ/dpt-tools#163]
Hello guys, today I opened digital paper app and got a notification about new firmware. It's version is 1.6.50.14130.

**Comment by koreaseoul** [comment]
I saw it, too. A lot of people were waiting for it.

**Comment by koreaseoul** [comment]
New files are needed quickly. Many people will want to update. I always thank HappyZ for his work.

**Comment by HappyZ** [comment]
I'll take a look this weekend. What new features they announced?

**Comment by myliyifei** [comment]
> I'll take a look this weekend. What new features they announced?

https://www.sony.jp/digital-paper/update/dpt-rp1_cp1/ver1_6_5_feature.html

**Comment by Kilo433** [comment]
already updated and successfully rooted
![DP_20200404_1306](https://user-images.githubusercontent.com/63138107/78419131-38896100-7675-11ea-93b8-cf2d5fd7804f.png)

**Comment by HappyZ** [comment]
Updated
