### ISSUE TITLE
my touchscreen didn't work randomly, but when i charge it, the touchscreen always come back, is it a software or hardware issue ?

### ISSUE THREAD

**Issue by SweetZone** [HappyZ/dpt-tools#166]
hi

the first time my DP1's touchscreen failed is with 1.6 firmware, i updated it to 1.6.50 yesterday, nothing changed

when i charge it, the touchscreen always come back 

is it a software or hardware issue ?

**Comment by HappyZ** [comment]
If you flash it back to before 1.6 firmware, and problem exists, then it is a hardware issue. Otherwise, it would be a software issue. I tend to think it is a hardware problem as I remembered someone also got irresponsible touchscreen. #107

**Comment by HappyZ** [comment]
And similar to before
```
cd /usr/local/bin
./tp_print_touch_data.sh > /root/test.log
```
then touch your screen several times. Finally, press ctrl +C to stop
then
```
cat /root/test.log
```
What does it print?

**Comment by SweetZone** [comment]
> And similar to before
> 
> ```
> cd /usr/local/bin
> ./tp_print_touch_data.sh > /root/test.log
> ```
> 
> then touch your screen several times. Finally, press ctrl +C to stop
> then
> 
> ```
> cat /root/test.log
> ```
> 
> What does it print?

unfortunately, the second morning after flashed to 1.6.50, touchscreen never come back. Failed to run tp_print_touch_data.sh in diagnosis mode 

flashed back to 1.4, didn’t work 

it’s a early version hardware bug

so i sent it to repair service

**Comment by SweetZone** [comment]
Yes, it's a hardware problem. My RP1 has been repaired now
