### ISSUE TITLE
How to upgrade and root

### ISSUE THREAD

**Issue by JoeKays** [HappyZ/dpt-tools#168]
Hi,
I want to upgrade a currently NOT-rooted RP1 with version 1.6.03 to 1.6.50 and root it.

Do I have to follow step 0x3 of the rooting guide and flash the package for 1.6.03 and then follow the upgrade guide to update to 1.6.50?

Or can I just use the 1.6.50 PKG in step 0x3 of the rooting guide and root+upgrade in a single step?

Thanks!

**Comment by HappyZ** [comment]
You can directly go for 1.6.50

**Comment by JoeKays** [comment]
First of all: thank you for your work! The adb root seems to have worked perfectly!

Now the problem: I did try to directly go to 1.6.50. I cloned the master branch of this repo last week and yesterday flashed the file in the working tree under `fw_updater_packer_unpacker/pkg_example/flashable_mod_boot_img_1.6.50.14130/FwUpdater.pkg`
and everything happened as described in the wiki.
However after reboot the version number still reads 1.6.03 and the undo/redo functionality that should have come with 1.6.50 is not there.
What could have gone wrong?

Thanks in advance!

**Comment by HappyZ** [comment]
That seems like it's not flashed correctly. I feel like you did something wrong.  Did you just flash the boot img? You should upgrade to latest system first, and then flash boot img etc. 

When I say "you can directly go for xxx", I meant you can directly upgrade the system to the latest, either using my modded official package, or through official upgrades. Only then flash the corresponding boot img mod.

**Comment by JoeKays** [comment]
Thank you, I noticed that I did it wrong, maybe the Ultimate Rooting Guide is a bit confusing together with the Linux guide.

I thought that since there were version numbers for the ADB root hack image that it contained the firmware + the hack.
But now I understood that it only contains the hack (actually it's obvious from the file size).

Maybe you can add a note somewhere that the firmware packages are different from the adb root hack packages. It is also additionally confusing now, because there appeared devices with the 1.6.50 firmware that have the security flaw patched already and cannot be rooted. 
You mention that this is not a problem in the wiki, but it is not exactly clear that you can safely flash the 1.6.50 firmware package and then do the adb hack afterwards, that's why I wanted to make sure and directly flashed the 1.6.50 adb hack package thinking that it would also update the firmware... :facepalm: 

Anyway thank you very much for providing this and also giving support to stupid people ;)
