### ISSUE TITLE
Can you add Xposed to the image? Or give an instruction how to install it?

### ISSUE THREAD

**Issue by ultraboy** [HappyZ/dpt-tools#17]
3rd party apps are too fade to see. After google it, I belive Xposed would enable us to optimize that?

**Comment by HappyZ** [comment]
I had a discussion with shankerzhiwu earlier. It is not difficult to install xposed, with a few system-wise modifications. 

But we have not figured out an easy way to let it work robustly. 

Also we both agreed it would be a lot of work to change system framework for better font size and darker displays, while not affecting the original system apps.

This is why I have not released anything yet. I hope to release anything that is stabler to use at this stage, so people do not have to wipe systems out etc. every time things broke.

**Comment by ultraboy** [comment]
Thank you for your hard work, I am looking forward for it

**Comment by HappyZ** [comment]
xposed can be installed easily when you install the xposed framework app

the problem is it has a busybox itself, and its script will call `busybox reboot` which halts the system (when you uninstall). if it happens, you'll have to wait until battery drains to reboot the device..

**Comment by HappyZ** [comment]
refer to #59
