### ISSUE TITLE
Possible to unlock a DPT RP1 without wifi

### ISSUE THREAD

**Issue by obsoletemachines** [HappyZ/dpt-tools#173]
hi, i bought a used DPT RP1 supposedly with a dead battery, off ebay, but no its actually locked. Is there a way to flash it via ethernet (via USB) to get it working?  I can't get the ID to access via DPT-tools diagnose.

**Comment by HappyZ** [comment]
My understanding is:
- If it's already rooted and you have diagnosis mode, then yes - basically just need to reset.
- If it has adb root but no diagnosis mode, then theoretically yes - basically gain access to diagnosis mode and continue
- If it's locked and no diagnosis mode enabled before, then no - you need access to standard FW flashing APIs, which requires a valid connection to the system (using the correct id and key)

**Comment by HappyZ** [comment]
Almost forgot but you can press reset key for 30s ish and reset the device as well..

**Comment by obsoletemachines** [comment]
hi, i have tried the reset and checked the reset button works mechanically but so far not managed to get it to hw reset. Every-time it just powers on and returns to the lock screen.
