### ISSUE TITLE
Plz help, I kicked my dpt rp1 into diagnosis mode, but I can not kick it back. the computer wont recognize it anymore

### ISSUE THREAD

**Issue by Delsinhaha** [HappyZ/dpt-tools#176]
THX for your work!
The computer just won't recognize it as adb device any more.

**Comment by Delsinhaha** [comment]
It shows up as a Linux File-CD Gadget USB Device in devicemanager when connected.

**Comment by HappyZ** [comment]
If in diagnosis mode, lightly press reset once. It will reboot.
