### ISSUE TITLE
Android ADB (Root) Access PKG for CP1 on 1.4.01.16100

### ISSUE THREAD

**Issue by Zhanghan95** [HappyZ/dpt-tools#177]
Hi @HappyZ,

I was following your guide in [this link](https://github.com/HappyZ/dpt-tools/wiki/The-Ultimate-Rooting-Guide). Now I am at step **0x3 Obtain Android ADB (Root) Access**. My CP1's system version is 1.4.01.16100, but I just found there is no PKG download link for CP1 on that system version (there's a link for RP1 tho). Can you point me to a PKG for CP1 on 1.4.01.16100 that I can use?

Thank you and have a nice holiday!

**Comment by Zhanghan95** [comment]
Additional question:

Is it alright for me to update my CP1 through official update now? I followed your guide and only did step **0x1** and **0x2** (I am able to get into diagnosis mode). Digital Paper App prompts me to update to latest version(1.6.50.14130) I think you have a PKG for CP1 on that version, but will official update break my system because of changes I've already made?

**Comment by HappyZ** [comment]
It won't change. You can follow the upgrade guide in wiki: first do
official upgrade and then fix launcher crash if applicable. As far as I
know 1.6.50.14130 does not affect anything on diag partition.

**Comment by Zhanghan95** [comment]
Thank you, I update to 1.6.50.14130 through official update, and the following steps were successful.

Appreciate the help!
