### ISSUE TITLE
I flashed a wrong version, is it bricked?

### ISSUE THREAD

**Issue by Yaming9** [HappyZ/dpt-tools#178]
I'v made a mistake, my rp1 is version 1.2, and I flashed a 1.6.03.09261 pkg, now it is stuck in "welcome" screen. Is it bricked?

It can be boot into diagnose mode with a black square in the middle if I press HOME button when boot.

I didn't read the instructions carefully, it dose said don't processed when the version is not match, T T.

**Comment by HappyZ** [comment]
You can fix it. Just use the modified official PKG. Flash that first, then
flash the mods with adb. Check guide on how to upgrade.

**Comment by Yaming9** [comment]
Thanks a lot for your reply!

I see, use upgrade method3 in diagnose mode, right?

I tried to connect in diagnose mode, it said failed to login, what should I do?

>>> Black square on the screen? [yes/no]: yes
>>> Enter the serial port [/dev/tty.usbmodem01]: COM1
[error] failed to login..
[info] got out of diagnosis

**Comment by Yaming9** [comment]
I tried to login manually with root/12345, it logged in, the password is right.

**Comment by HappyZ** [comment]
Can you try command line with '-d' so it prints debug info? I suspect it's
because you weren't in a clean state as your device has been in the
diagnosis mode.

Lightly press reset button to turn device off. Then redo the steps to get
into diagnosis mode.

If you could still follow method#2 it will be easier.

**Comment by Yaming9** [comment]
>>> Enter the serial port [/dev/tty.usbmodem01]: COM1
[debug] b''
[error] failed to login..
[info] got out of diagnosis

debug info is b"

I haven't obtained adb access yet, so I think I cannot use method#2?

Or is there any instruction on flashing a pkg using serial terminal directly?

**Comment by HappyZ** [comment]
Source code is fairly straightforward. If you know what you are doing then
go ahead and follow. It isn't difficult to do.

I've never tried windows with the tool so it might be why it didn't work
OOB.

**Comment by Yaming9** [comment]
I see, I think I can try in a Mac or just follow the source code.

I think I have all the information now, thanks a lot for your time, and appreciate for your great work!
