### ISSUE TITLE
Will this work for DPT-S1?

### ISSUE THREAD

**Issue by Jimw338** [HappyZ/dpt-tools#179]
Will this work for the DPT-S1 or only the newer (!) RP1 and CP1 devices?  I found the article from back in 2015 that a person was offering to "hack for money" [1] - but that was back in 2015.  I specifically got an S1 for 1) the expansion slot, and 2) figuring that an older model would be more likely to be able to be hacked..

[1] https://the-digital-reader.com/2015/11/13/sony-dpt-s1-hacked-now-runs-android/

**Comment by HappyZ** [comment]
No this does not. It only works for RP1/CP1 manufactured before Sept. 2019.
