### ISSUE TITLE
Problems during installation

### ISSUE THREAD

**Issue by ghostwheel** [HappyZ/dpt-tools#18]
Just reporting on problems, so others can avoid falling into same holes.
I did everything on a macbook, 10.11.6, and with python 3.6

1. To find IP of device, click settings , wifi settings, and then on the wifi network you are connected to.
2. After running for first time, answered "disabled the id check already?" -> no.
I got "request error 401:, error code 40100 failed to upload file.

At this point I'm not sure what was wrong, I tried various things, among them device reboot.
I rand command 'root' again, this time answering "yes" to the question "have you disabled id check". And, then all seemed successful. 

3. When trying diagnosis, I had an error "module 'serial' has no attribute 'Serial'. This was solved by
`pip3 uninstall serial`, `pip3 install pyserial`

4. My device was at /dev/tty.usbmodem1

5. If you are in diagnosis mode (black square), and want to reboot, click on the hidden reset button near the power button on the DPT.

6. Finally I managed to run diagnosis mode. But, something happend, and every command returned 
`[error] (6,'Device not configured)`
exiting, disconnecting the USB cable, reconnecting and restarting the diagnosis command on the mac fixed that.

7. It would be good to explain better what it means to 'use python_api/assets/adbkey to authenticate device'. I'm not sure if I did the right thing... I copied it to ~/.android, but what should I do?

**Comment by ziegfeld** [comment]
I met 401 and 40100 previously too. but not seeing things like you later.

for your 7:
yes copy that, then type "adb killserver" then "adb devices" you should see the device with id and usable (you can do adb push, adb install et al), not anymore "unauthorized".

**Comment by WangJunChen567** [comment]
I used 'push-file' to copy `python_api/assets/adbkey` to folders `~/.android`, `~/.android/adb_keys`, `adb_keys`, `/data/misc/adb/adb_keys`, 
however after rebooting, `adb devices` still output `unauthorized`, and `abd shell` output `error: device unauthorized. This adb server's $ADB_VENDOR_KEYS is not set`.

**Comment by HappyZ** [comment]
> 2. After running for first time, answered "disabled the id check already?" -> no. I got "request error 401:, error code 40100 failed to upload file.

thx for reporting it. Can you tell it a bit more? When it says it?

> 3. If you are in diagnosis mode (black square), and want to reboot, click on the hidden reset button near the power button on the DPT.

you can just type `reboot &` and exit the program.

> 4. Finally I managed to run diagnosis mode. But, something happend, and every command returned
>    `[error] (6,'Device not configured)`
>    exiting, disconnecting the USB cable, reconnecting and restarting the diagnosis command on the mac fixed that.

It usually happens because of unstable disconnections (poor cables etc.) while uploading img that's too big. We'll have a better way to upload later. 

> 5. It would be good to explain better what it means to 'use python_api/assets/adbkey to authenticate device'. I'm not sure if I did the right thing... I copied it to ~/.android, but what should I do?

Sure. I'll change README.md soon to clarify.

> I used 'push-file' to copy python_api/assets/adbkey to folders ~/.android, ~/.android/adb_keys, adb_keys, /data/misc/adb/adb_keys, however after rebooting, adb devices still output unauthorized, and abd shell output error: device unauthorized. This adb server's $ADB_VENDOR_KEYS is not set.

You shall not do it in diagnosis mode. `python_api/assets/adbkey` is put to `~/.android` in your own computer..

**Comment by ghostwheel** [comment]
> 
> > 1. If you are in diagnosis mode (black square), and want to reboot, click on the hidden reset button near the power button on the DPT.
> 
> you can just type `reboot &` and exit the program.

Yes, the problem was that I managed to get into diagnosis mode on the DPT side, but the computer couldn't connect, and so I wanted to exit diagnosis mode... 
I think that was when I had problems with the serial connection because I installed `serial` instead of `pyserial`...

**Comment by HappyZ** [comment]
Ah I see :) 
I'm making a newer version to leverage direct pkg flashing. So hopefully we will only need to go to diagnosis once. Stay tuned.
