### ISSUE TITLE
Can I install Kindle app?

### ISSUE THREAD

**Issue by yuta-hidaka** [HappyZ/dpt-tools#182]
I want to read e-book on kindle what I bought .

Someone try to install kindle on dpt ??

**Comment by yuta-hidaka** [comment]
I solved own just install apk.

And It works !!

Thank you for guys who greatest software ever.

This apk worked for me.
https://apk.gold/download?file_id=601829/amazon-kindle

Replase template to below.
`com.amazon.kindle`

**Comment by shiner-chen** [comment]
> I solved own just install apk.
> 
> And It works !!
> 
> Thank you for guys who greatest software ever.
> 
> This apk worked for me.
> https://apk.gold/download?file_id=601829/amazon-kindle
> 
> Replase template to below.
> `com.amazon.kindle`

I installed the kindle apk, and then sync my account and download the book, but cannot open the book. How to deal with this problem? Thanks a lot!

**Comment by yuta-hidaka** [comment]
Hi  ! @shiner-chen 

Did you use same apk ??

All of the book could not open?

If can not open is there something error message ??
