### ISSUE TITLE
Usable Xposed and AppSettings apk for CP1-1.6.50.14130?

### ISSUE THREAD

**Issue by nicoster** [HappyZ/dpt-tools#183]
Hi there, 

Thanks to @HappyZ and other contributors. 
I successfully rooted my CP1. but I cannot find a usable Xposed apk for it. I tried a few builds like:

```bash
% ll *xposed* 
-rw-r--r--@ 1 nickr  staff   788771 Apr 10 15:28 de.robv.android.xposed.installer-1.apk
-rw-r--r--@ 1 nickr  staff   728857 Apr 13 15:12 de.robv.android.xposed.installer_v32_de4f0d.apk
-rw-r--r--  1 nickr  staff    70569 Nov 17  2014 de.robv.android.xposed.mods.appsettings_v14_f64729.apk
-rw-r--r--  1 nickr  staff   162840 Nov 17  2014 de.robv.android.xposed.mods.appsettings_v29_70ccc5.apk
-rw-r--r--  1 nickr  staff  3561425 Dec 18  2017 xposed-v89-sdk22-arm.zip
```

Some say `Xposed is not (yet) compatible with Android SDK version 22 or your processor architecture (armeabi-v7a)
CANNOT LINK EXECUTABLE DEPENDENCIES: library "libdvm.so" not found`

the other won't install the framework. I did try to install it manually according to the post here:
https://forum.odroid.com/viewtopic.php?t=21445

But the AppSettings crashes when I tried to customize the settings for an app (like WeRead or Kindle)

I know this isn't really an issue for the rooting but hope someone here might have a solution. Thanks.

**Comment by stanleyws** [comment]
use xposed installer for lollipop from this post:
https://forum.xda-developers.com/t/official-xposed-for-lollipop-marshmallow-nougat-oreo-v90-beta3-2018-01-29.3034811/
you need appsettings reborn, not old appsettings. also you need to install version 1.1 (later versions require xposed framework v90 and higher). BTW skyolin helper works better than appsettings IMO.

**Comment by whmzsu** [comment]
My DPT RP1 installed the xposed installer version 3.1.5. It worked with lollipop, api 22 framework . And also I install the   skyolin helper  2.5 , also worked too.

**Comment by nicoster** [comment]
I managed to run the skyolin on my CP1. 
the command `adb reboot recovery` saved my life. 

Thanks to @stanleyws @whmzsu

**Comment by yefeiyu** [comment]
> 

Could you give me the version 1.1 of Xposedinstall apk? Thank you. please send it to my email: yefeiyu@gmail.com.
