### ISSUE TITLE
Does rooting allow me to bypass the Digital Paper app?

### ISSUE THREAD

**Issue by Abomasium** [HappyZ/dpt-tools#185]
It seems like the Digital Paper app might soon be no longer compatible with the latest versions of Windows and Mac, because the whole product line is discontinued. So there may be a need to bypass the DP app in the future, and wondering if rooting will allow for that!

**Comment by HappyZ** [comment]
You don't need rooting to sync up. Check out janten's tool: https://github.com/janten/dpt-rp1-py this is a command line python tool to replace DPT app.

And the original DPT app link for MacOS: https://www.sony.net/Products/DigitalPaperSystem/Software/DPA-Mac/DigitalPaperApp_1.4.5.00034.dmg
