### ISSUE TITLE
找了一个RP1的维修手册 发现里面有个软件可以修改SKU 不知能否用过命令行实现？

### ISSUE THREAD

**Issue by xiaoyuzz** [HappyZ/dpt-tools#187]
3-1. Start the Test Mode
　　 Procedure：
　　　1. Execute DCAforTestMode-1.0.00.xxxxx.jar.
　　　　※ The JRE (Java Runtime Environment) and the Digital Paper App must have been installed.
　　　2. Connect the device to the PC (on which DCAforTestMode-1.0.00.xxxxx.jar is running) with a USB cable.
　　　3. Check that “Ready” is shown at the lower left of the DCA for Test Mode screen, select “Launch Test Mode”, and
　　　　 then click the [Run task] button.

**Comment by yefeiyu** [comment]
What is this for?

**Comment by xiaoyuzz** [comment]
> 

test mode can be replace region（SKU） J=JAPAN U=USA  C=CHINA

**Comment by G1916578** [comment]
可以分享一下维修包吗
