### ISSUE TITLE
Stuck in diagnosis mode and adb/dpt-tools can not connect device

### ISSUE THREAD

**Issue by hyhou** [HappyZ/dpt-tools#189]
Hi,

I rooted my dpt before and installed the launcher and some apps. Then after a while, the touch is no longer working.
So I decided to fix it. I first try the dpt-tools and find it can not connect the device. (I changed computer since last time I use dpt-tools).
But the adb can connect, so I used the adb shell to execute the command from this wiki : https://github.com/HappyZ/dpt-tools/wiki/diagnosis-mode-in-terminal

And then sad story comes, the device can not be deteced by adb or dpt-tools now. I tried to install the adb driver and nothing works.
The device is now recognized as Linux File -CD Gadget USB device.

I read over all the issues and notice some one used Serial to connect the device.
I installed the RealTerm software to connect the COM7(where the device is showed in my DeviceManager).

Now I see the familiar  FPX-1010 like following:
<img width="365" alt="屏幕截图 2022-08-27 012249" src="https://user-images.githubusercontent.com/7356244/186958936-6eb0c4ba-447f-41fd-969a-c195274cbf79.png">

And I got stuck here, I tried to login with root/root, root/(empty), xxx, nothing works, I can not login inside.
And I have no lock at all.
I also tried to press reset for 30 seconds, no luck, it just boots to diagnosis with black squre in center.
Does anyone know what should I type in to continue.?
OR are there any other way that I can easily quit the diagnosis mode to explore other methods?

Thanks!
BR

**Comment by HappyZ** [comment]
not sure if you have resolved it. If you have checked the source code here https://github.com/HappyZ/dpt-tools/blob/master/python_api/libInteractive.py#L342, the password is 12345 and username is root if you didn't modify anything. 

The guide https://github.com/HappyZ/dpt-tools/wiki/diagnosis-mode-in-terminal should be carefully used. It must have stuck into the diagnosis mode now. Run `rawdata --set_dump=boot_mode < /dev/zero` so it reset the boot mode.

**Comment by HappyZ** [comment]
Close this but feel free to reopen if you have any followup question or it didn't resolve.
