### ISSUE TITLE
Unable to enter diagnosis mode

### ISSUE THREAD

**Issue by qianbo-x** [HappyZ/dpt-tools#199]
Thank you very much for your work. However, I am still encountering some issues and would like to seek your advice.
![image](https://github.com/user-attachments/assets/7376c1a9-df06-4706-a177-8f92050610af)
I followed steps 1-4 to enter diagnosis mode, but the black square did not appear at step 4. Instead, the screen flickered (briefly turned black) and then shut down. Do you know how to resolve this issue?
Thank you again for your time.

**Comment by qianbo-x** [comment]
All set, thank you!

**Comment by LvAoAo** [comment]
> All set, thank you!

Hello bro, how do you get it? I met the same problem you described.

**Comment by qianbo-x** [comment]
原装的系统好像没有这个模式，要装作者发出来的某个版本来着，建议按照作者的教程来。

**Comment by LvAoAo** [comment]
可以问下你现在用的是mac系统装的dpa吗，我装了1.4.7的新版dpa和能找到的老板1.4.3 dpa，然后用usb都没法和电脑相连。
我的电脑是macbook pro m1。

**Comment by LvAoAo** [comment]
我明白了，我这可能是买的比较晚，20年后期或者21年才买的，所以这个方法没法破解。谢谢
