### ISSUE TITLE
are you there？

### ISSUE THREAD

**Issue by baolitoumu** [HappyZ/dpt-tools#2]
you can see xda

**Comment by HappyZ** [comment]
No I was too busy lately and I only knew xda has someone tried USB method and got into the diagnosis mode. But YES! I just saw it, fantastic work! I knew USB/web interface is the way! So happy someone did it!! I'll need to personally verify it, and then I'll update the README later tonight to reflect this. Thanks for posting letting me know.

**Comment by baolitoumu** [comment]
i already into 
![image](https://user-images.githubusercontent.com/14047916/48592325-cda59000-e982-11e8-8923-baa8555c1090.png)

**Comment by baolitoumu** [comment]
So happy someone did it (:

**Comment by HappyZ** [comment]
nice! I'll try it soon

**Comment by HappyZ** [comment]
how do you turn off the device if it enters diagnosis mode? long pressing power button can't turn it off.. and I haven't changed the password yet..

**Comment by HappyZ** [comment]
oh nvm figured it out.. just press once the reset button; great

**Comment by HappyZ** [comment]
ok it works and i have added a script to automatically do this
