### ISSUE TITLE
Magisk Support

### ISSUE THREAD

**Issue by sekkit** [HappyZ/dpt-tools#21]
more customization for apps.

**Comment by HappyZ** [comment]
I'll check it out, but so far I have no plans to add additional packages/frameworks. If it helps on font and DPI etc., maybe.

**Comment by sekkit** [comment]
Install Xposed over Magisk, may improve the stability.....that's what I am testing now.
In my opinion, Xposed to change individual app's dpi is much better than taobao's approach. Modifying sony's app is unlegal as well as troublesome for upgrading.

**Comment by sekkit** [comment]
The problem is:
Magisk successful installed on DPT, then select Xposed framework, install, reboot. U never gonna boot into system again. Wierd.

**Comment by ziegfeld** [comment]
DPI settings:
in addition to font settings in "android system settings - display and -accessiblity", you can use adb:

`
    adb shell
>> wm size
Physical size: 1650x2200
>> wm density
Physical density: 160
>>   wm density 207
>>   wm density
Physical density: 160
Override density: 207
//wm size reset
//wm desity reset
`
credit: https://www.hi-pda.com/forum/viewthread.php?tid=2432969&page=4&extra=#pid49697263 

Xposed can be installed easily; xKindleMod and Xposed Edge Pro are tested too. See the link above for instructions and discussions (in Chinese).

**Comment by sekkit** [comment]
appsettings not working though

**Comment by HappyZ** [comment]
refer to #59
