### ISSUE TITLE
Poor Battery life? 

### ISSUE THREAD

**Issue by Antiparadox** [HappyZ/dpt-tools#22]
I wonder if anyone encounters the same issue:
Ever since I rooted this device and installed a few Apps, the battery life is noticeably shorter, and even with Force Shutdown some app still has dangling processes running on background.
So is there a way to change app permissions? I explored Android settings, but there seems to be no such options.
Any ideas?
Thanks!

**Comment by HappyZ** [comment]
Possibly the apps were running in the background? This is Android 5.1.1 and I don't think permission control is implemented in this version. I have never tried, but there is a Battery Savor mode in Battery settings, top right corner. Let us know if it works to extend battery life.

**Comment by Antiparadox** [comment]
Nice catch, but this mode cannot be activated for some unknown reason.

**Comment by ziegfeld** [comment]
Disable WIFI, that is the main drainer.
Greenify and IceBox apps would also help

**Comment by HappyZ** [comment]
closing as there's no further discussions
