### ISSUE TITLE
Failed to upload shankerzhiwu_changepwd pkg

### ISSUE THREAD

**Issue by JMartJonesy** [HappyZ/dpt-tools#26]
After trying to add get root privileges to my dpt rp1 I get an authentication error. I am not sure if you are eluding to this in your **w_updater_packer_unpacker - Automation to pack/unpack pkg** section and if so how would I get file explorer privileges to my rp1 so that i can modify the file you mention? 

```
[info] Please make sure you have charged your battery before this action.
[info] Thank shankerzhiwu (and his/her anonymous friend) a lot on this hack!!!All credits go to him (and his/her anonymous friend)!
>>> Have you disabled the id check already? [yes/no]: no
[info] fw updating in progress.. do NOT press anything..
>>> After your DPT reboots, shows `update failure` message, connects back to WiFi, etc., press `Enter` key to continue
[info] Congrats! You are half-way through! You have disabled the OTG ID check
[info] fw updating in progress.. do NOT press anything..
[error] https://192.168.1.35:8443/system/controls/update_firmware/file
[error] request error 401:
[error] * error_code: 40100
[error] * message: Authentication is required.
[error] failed to upload file
[error] Failed to upload shankerzhiwu_changepwd pkg
```

**Comment by sekkit** [comment]
obviously, it says u haven't disabled the id check.

**Comment by JMartJonesy** [comment]
I was under the assumption that the reset would turn off the id check as it clearly states in the output i post `You have disabled the OTG ID check`

**Comment by HappyZ** [comment]
you already did, just type `yes` to bypass it and do the next step, i'll fix it
