### ISSUE TITLE
How to change the lock screen wallpaper?

### ISSUE THREAD

**Issue by alps2006** [HappyZ/dpt-tools#27]

**Comment by HappyZ** [comment]
it is from the framework-res.apk so it's not so easy to replace

**Comment by alps2006** [comment]
thank you very much.  i have changed the lock screen wallpaper.

copy the framework-res.apk to computer,  then replace the "res/drawable-mdpi-v4/im_digitalpaper_stamp.png" file by winrar.

**Comment by HappyZ** [comment]
=.= ok sounds good
