### ISSUE TITLE
USB OTG

### ISSUE THREAD

**Issue by sekkit** [HappyZ/dpt-tools#28]
when u plugin a usb device to DPT, it'll work as OTG.
when u plugin DPT to computer, it'll be recognized as USB drive.

**Comment by ziegfeld** [comment]
I just recalled I have an OTG cable, so I can help testing.

**Comment by HappyZ** [comment]
Wouldn't think this is a useful feature anyways.. if you are interested you can do it. Closed for no further discussions.
