### ISSUE TITLE
Bluetooth support

### ISSUE THREAD

**Issue by sekkit** [HappyZ/dpt-tools#29]
Could u extract bluetooth module from hacked fw?

**Comment by HappyZ** [comment]
I can't do much these days, but I'll keep an eye on it. Taobao pkg has those which is great!

**Comment by p4s2wd** [comment]
The taobao seller did include a Bluetooth apk into /system/app, you can put the fold Bluetooth into your /system/app from Taobao's system.img as following:

root# pwd
/mnt/system/app

 root# ls -al Bluetooth
total 104
dr-xr-xr-x   4 root  wheel   4096 Dec 10 11:48 .
dr-xr-xr-x  55 root  wheel   4096 Nov  1 14:35 ..
-r--r--r--   1 root  wheel  35673 Dec 10 11:48 Bluetooth.apk
dr-xr-xr-x   2 root  wheel   4096 Sep  6 13:58 arm
dr-xr-xr-x   3 root  wheel   4096 Sep  6 13:58 lib

**Comment by sekkit** [comment]
@p4s2wd have u test it?

**Comment by p4s2wd** [comment]
> @p4s2wd have u test it?
I can connect most of Bluetooth device on my dpt-rp1 such like my Iphone and Xiaomi Box.

**Comment by sekkit** [comment]
great, this issue can be closed

**Comment by sekkit** [comment]
@p4s2wd I copied Bluetooth folder to /system/app, but the bluetooth sharing keeps crashing.
I set the permission to 0644, what's missing in my steps?

**Comment by ziegfeld** [comment]
@sekkit could you please recheck that you have all the files inside that folder's subfolders?
1. arm: `-r--r--r--  1 root  wheel   2.7M Nov 28 21:45 Bluetooth.odex`
2. lib/arms:  `lr-xr-xr-x  1 root  wheel    31B Apr 10  2018 libbluetooth_jni.so@ -> /system/lib/libbluetooth_jni.so`
  this is a symlink so please make sure you copied the actual file:
 `-rw-r--r--  1 abc  staff    88K Dec 13 18:07 libbluetooth_jni.so`

@p4s2wd I am in the same situation now, MacBook connected as well as an android phone. 
But MacBook would not let me share file, saying "The devices does not have the neccesary services"

Edit: with @p4s2wd we figured this out. Use the /app/Bluetooth folder from new 1211 system image would just do it. Now you can use bluetooth keyboard with it, verifiedly. But as for sharing files from your cellphone or laptop, RP1 has pop up showing "incoming file" but no way for us to accept it..

**Comment by sekkit** [comment]
@ziegfeld I copied Bluetooth folder and libbluetooth_jni.so to the coresponding location, but file permission is messed up, no lr-xr-xr-x. changing to 0644, still crashes.
also when I run: ls -ltotal 72
drwxr-xr-x    4 root     root          4096 Apr 10  2018 .
drwxr-xr-x   56 root     root          4096 Dec 14 07:48 ..
-rw-r--r--    1 root     root         57102 Apr 10  2018 Bluetooth.apk
drwxr-xr-x    2 root     root          4096 Apr 10  2018 arm
drwxr-xr-x    3 root     root          4096 Apr 10  2018 lib
it's like this.

Update: finally did it. Must not overwrite the symlink, use the original one solved the problem.

**Comment by ziegfeld** [comment]
@sekkit sorry about that false info  on symlink :D
still rp1has no way to accept incoming files shared; later in menu from Bluetooth upper right corner it shows that file was cancelled.
we need to figure it out for  file transfer.
I don't know how to test sound/ HID(?) either.

**Comment by HappyZ** [comment]
a35d60a498e43f6008c07de8cb910e330ce28609 is added to ease the process
