### ISSUE TITLE
i have a another fw from taobao

### ISSUE THREAD

**Issue by baolitoumu** [HappyZ/dpt-tools#3]
you can put email ,i will send you

**Comment by HappyZ** [comment]
oh sure thx, email is yz@9pm.me

**Comment by HappyZ** [comment]
looks like it is not a standard pkg provided officially. this pkg is an encrypted/compressed version.. interesting.. why taobao fw does not use the standard pkg format to update

**Comment by HappyZ** [comment]
close this. there's no way to decrypt this pkg.
