### ISSUE TITLE
App launcher

### ISSUE THREAD

**Issue by zejian-li** [HappyZ/dpt-tools#30]
The example provided works for the system browser app. However how can we get the intent name of an arbitrary app ?

**Comment by p4s2wd** [comment]
You can get the intent name with following command once the application is active in UI.

dumpsys window | grep  mCurrentFocus | grep launchable-activity

**Comment by zejian-li** [comment]
> You can get the intent name with following command once the application is active in UI.
> 
> dumpsys window | grep mCurrentFocus | grep launchable-activity

dumpsys window | grep mCurrentFocus will suffice.
