### ISSUE TITLE
Thank you for your work.

### ISSUE THREAD

**Issue by yanjunhui** [HappyZ/dpt-tools#33]
Thank you for your work. 
I'm very sorry that your equipment has turned brick.
So far, is there a list of functions that are sure to be completed without any bad effects? I hope to make safe changes to my DPT.
I'm from China. I think I can do some work, If you need
thank you.

**Comment by ziegfeld** [comment]
Pal, for an easy guide step-by-step in Chinese and your question,
register to see this https://www.hi-pda.com/forum/viewthread.php?tid=2432969
mainly page 4, esp. post 170.

**Comment by HappyZ** [comment]
Right now nothing I posted will cause a bad effect, i.e. un-recoverable brick. Thanks for helping though. I'll let you know if needed.

**Comment by HappyZ** [comment]
@ziegfeld feel free to make changes to the readme if process isn't clear.
