### ISSUE TITLE
[Need Test] Enable mass_storage in normal boot

### ISSUE THREAD

**Issue by HappyZ** [HappyZ/dpt-tools#34]
Although in diag mode it is already used, this boot img will enable mass_storage in normal boot mode. Test it out and see if it works.

[boot-1.4.01.16100-mod-181214.img.zip](https://github.com/HappyZ/dpt-tools/files/2681187/boot-1.4.01.16100-mod-181214.img.zip)

**Comment by sekkit** [comment]
tested, adb unable to connect, saying unauthorized device.

**Comment by HappyZ** [comment]
oh right, i removed adb_keys in this img; i'll put it back for now; but mass_storage works or not?

**Comment by sekkit** [comment]
> oh right, i removed adb_keys in this img; i'll put it back for now; but mass_storage works or not?

no mass_storage pops up in Mac. Windows untested yet.

**Comment by HappyZ** [comment]
guess this not working yet, will need to take a closer look at it this weekend
