### ISSUE TITLE
[Need Test] Enable mass storage in normal boot

### ISSUE THREAD

**Issue by HappyZ** [HappyZ/dpt-tools#36]
Expected behavior:
while booting in normal mode, pc should have mass storage popped up

~~[boot-1.4.01.16100-mod-181214-152910.zip](https://github.com/HappyZ/dpt-tools/files/2681757/boot-1.4.01.16100-mod-181214-152910.zip)~~ tested, not working.

~~[boot-1.4.01.16100-mod-181214-205356.img.zip](https://github.com/HappyZ/dpt-tools/files/2682361/boot-1.4.01.16100-mod-181214-205356.img.zip)~~ still not work

[boot-1.4.01.16100-mod-181214-205902.zip](https://github.com/HappyZ/dpt-tools/files/2682363/boot-1.4.01.16100-mod-181214-205902.zip) confirmed working

[2018-12-21] Flashable pkg (while in normal boot up mode) for above boot.img is [FwUpdater.pkg](https://github.com/HappyZ/dpt-tools/blob/master/fw_updater_packer_unpacker/pkg_example/flashable_mod_boot_img/FwUpdater.pkg) here. Make sure you have patched your updater bash.

also this should not affect adb service

if not working, post your `getprop sys.usb.config` and `getpropersist.t.sys.usb.config` here in adb, and specify which one you have tried.

Known issue:
Even if I have set persist..sys.usb.config to `acm,hid,adb,mass_storage` in default.prop, there must exist some other script that change it back to `acm,hid,adb`.
I can't figure out what did this.
But the ugly version forces to add `mass_storage` in `init.pxa1908.usb.rc`, which shall be working for sure.. I just don't like the dirty hack personally..
If you are an experienced developer, please let me know why the system didn't take `acm,hid,adb,mass_storage` (source code [here](https://github.com/HappyZ/dpt-boot-img/tree/1.4.01.16100-mod)).

**Comment by ziegfeld** [comment]
For the record, I tried the 1st rev with HappyZ but usb mass_storage did not pop up automatically as expected. 

@HappyZ is going to update this and **need another volunteer with DPT-RP1/CP1 for testing.**

**Comment by nyanadassana** [comment]
Tested, it would not pop up the mass_storage in MacOS 
get prop:

(edited to shrink it a bit more)
[persist.sys.usb.config]: [acm,hid,adb]
...
[sys.usb.config]: [acm,hid,adb]
...
[sys.usb.state]: [acm,hid,adb]
...

**Comment by HappyZ** [comment]
thx I'll check a bit more

for the record, manual typing works; wonder why persist.sys.usb.config isn't changed

before this comment, `boot-1.4.01.16100-mod-181214-152910.zip` has been tried

**Comment by HappyZ** [comment]
@nyanadassana  since you asked, I would appreciate if you can try the two new boot.img I modded. It will not affect your usage of the device.

**Comment by sekkit** [comment]
@HappyZ tested, last boot.img works in Mac

**Comment by nyanadassana** [comment]
@sekkit it won't pop up the mass storage for both boot.img. 
@HappyZ It seems adb getprop is not working as before

**Comment by HappyZ** [comment]
@nyanadassana  you are using windows? 
and what does it say when you run `adb shell getprop` on PC, or `getprop` inside adb shell?

**Comment by sekkit** [comment]
That last boot.img will cause DPT unable to connect to WIFI by DigitalPaperApp, has anyone tried that?

**Comment by HappyZ** [comment]
@sekkit the boot.img shouldn't change anything on wifi, check if reboot resolves it. check logcat why wifi crashes

**Comment by nyanadassana** [comment]
Wifi working in my place. 
@HappyZ  I am using Mac, it's seems adb can't connect to the device any more, when I type "adb devices" no answer. I even tried restore-bootimg with the "boot-1.4.01.16100-mod-happyz-181118.img" .no adb convection.

**Comment by nyanadassana** [comment]
I tried with your old version of restore-bootimg, which take about 20 mins to flash, works now.

**Comment by nyanadassana** [comment]
[persist.sys.usb.config]: [acm,hid,adb]
...
[sys.usb.config]: [acm,hid,adb]
...
[sys.usb.state]: [acm,hid,adb]

**Comment by nyanadassana** [comment]
Second img boot-1.4.01.16100-mod-181214-205902, after reboot, a drive named Untitled shows, inside have a file a coped into it previously: boot.img.bak. adb shell getprop says this:
...
[persist.sys.usb.config]: [acm,hid,adb]
...
[sys.usb.config]: [acm,hid,adb]
...
[sys.usb.state]: [acm,hid,adb]
...

**Comment by nyanadassana** [comment]
Then, within the new system.img, the file master can find the folder 'Usb 存储 文件中转'

**Comment by HappyZ** [comment]
> I tried with your old version of restore-bootimg, which take about 20 mins to flash, works now.

Can you let me know what you did before which isn't working? 
If you followed the newer script instructions, is it not booting up (with either boot.img I shared)?

**Comment by nyanadassana** [comment]
If I follow the new script instructions, the flash only takes 1 second.
It will boot (with the 1gb new system.img), just can't get adb working.(with both of your boot.img)

**Comment by HappyZ** [comment]
ok this sounds like the boot.img isn't successfully flashed in your device with the new mass storage method. It probably is due to you didn't eject the disk so DPT diagnosis cannot mount the drive correctly. I'll either enhance the script later to correctly identify if that happens, or just make a flashable pkg later.

**Comment by ziegfeld** [comment]
Tried this, works as magic!
Good thing about this boot.img is:
**both adb and mass storage works at the same time!**

When you hit "unmount mass storage", the adb still works.

**Comment by ZenCooper** [comment]
This is probably dumb question but...

When I copy a file to this mass storage area, where is it stored on actual Android partition? I want to copy some ROM files for an emulator app to /sdcard via mass storage.

**Comment by ZenCooper** [comment]
My understanding is that "normal" boot mode and "diagnosis" boot mode works on separate OS partition but this "untitiled" mass storage seems to share same data area...

**Comment by ziegfeld** [comment]
@ZenCooper yes same place.
/tmp/updater

**Comment by ultraboy** [comment]
Newest img do not work on my win10 pro 1809. Can see a usb stick, but it is gray. Win+R, then type d:/, it tell me to insert a disc..

**Comment by ultraboy** [comment]
Also, I am using #37 system image.

**Comment by HappyZ** [comment]
Thanks @ultraboy, can you open up a new issue instead of this one. You can refer to this issue.

And regarding the usb stick being gray, I think it is related to windows specific issues. I have not used windows for a while, but have you tried disconnect, reboot, and retry? If it happens consistently, it may be 1) windows cannot recognize the format of the usb drive (not very likely.. but may happen); or 2) the drive has bad sectors and cannot be correctly recognized. Usually 2) requires reformatting. But I don't have the device in hand, so I can't precisely tell you about the command.
