### ISSUE TITLE
Increase the speed of file transfers with usb ethernet.

### ISSUE THREAD

**Issue by shankerzhiwu** [HappyZ/dpt-tools#4]
By adding `ecm` to `/sys/devices/virtual/android_usb/android0/functions`, a 100Base-T ethernet over usb can be enabled.

Commands for reference: 

```
cp /usr/local/bin/usb_target.sh /tmp
sed -i 's/acm,mass_storage/acm,mass_storage,ecm/' /tmp/usb_target.sh
/tmp/usb_target.sh &
```

After that, the USB device will be detached and re-attached with an ethernet interface. The tty in the USB modem should be logged in again.

**Comment by HappyZ** [comment]
great! thanks for that!

**Comment by HappyZ** [comment]
used mass_storage
