### ISSUE TITLE
Re-running `root` cmd after `patch-updater-bash` causes brick and cannot get into diagnosis mode

### ISSUE THREAD

**Issue by mumunimu** [HappyZ/dpt-tools#44]
Hi,first of all, thank you for your effort ,Unfortunately, After restarting with the root command last night, my device did not respond. I pressed the reset button. Now the device has not been successfully reset and I can't enter the system. The diagnostic mode is also inaccessible. The yellow light of the power button keeps flashing, and the power button can turn off the device. Press the reset button can shut down.
There is no response after connecting the computer with usb, the device manager does not detect it.
Is my equipment bricked?Is there a way to return to the normal system interface? thank you very much

**Comment by HappyZ** [comment]
what did you run? what is you procedure exactly

**Comment by mumunimu** [comment]
press the reset and power button , he power button yellow light flashing, there is nothing on the screen , waited for a few hours, digital paper app also Can't connect,Did not respond after connecting to the computer，Device manager has nothing.

**Comment by HappyZ** [comment]
no i meant what did you do before it appears to be bricked

**Comment by mumunimu** [comment]
i failed to obtain shell sudo access,so I thought that the previous step was wrong, so I re-run the root command.The above happened when I restarted.

**Comment by HappyZ** [comment]
were you doing it in diagnosis mode or in normal mode? what are the steps you did "re-run"?

and did you do `patch-updater-bash`?

**Comment by mumunimu** [comment]
I successfully ran the root and diagnostic commands for the first time. It seems to be correct except for get-su-bin before I re-run the root command.

**Comment by mumunimu** [comment]
yes,i did patch-updater-bash

**Comment by HappyZ** [comment]
So you were in diagnosis mode? and you followed everything and ran `get-su-bin`, but it says failed? What failure message it says?

And then what did you do? you reboot into normal mode, re-start the root diagnosis etc. procedure?

Are you able to get into diagnosis mode at all? if you can't, then unfortunately it is permanently bricked unless you have hardware access to the emmc.

**Comment by mumunimu** [comment]
The commands I have entered are generally like this：
python dpt-tools.py -id C:\Users\a\dpt-tools\deviceid.dat -k  C:\Users\a\dpt-tools\privatekey.dat -ip 192.168.43.182

root
no
enter
diagnosis
yes
com8
patch-updater-bash
backup-bootimg
restore-bootimg
get-su-bin


root
then the  above happened

**Comment by mumunimu** [comment]
The usb data cable has been pulled out, and now it can't enter the diagnostic mode.
So is there any other way?

**Comment by HappyZ** [comment]
hmmmm what did the second root says. did it finish flashing the first one, or both.

**Comment by mumunimu** [comment]
There is no black box on the screen now, only the power button is flashing, I don't think it is in the diagnostic mode, I have pressed reset several times,,,

**Comment by mumunimu** [comment]
The second root command was stuck at the time of waiting for the restart.

**Comment by HappyZ** [comment]
when you turn it on normally, does it power off by itself?

reset doesn't work as it relies on the success of entering diagnosis mode first of.. (yea I know sony did this so wrong..) if you can't get into diagnosis any more, I can't help.. if you still have your warranty, describe it as hardware failure and ask for exchange

**Comment by mumunimu** [comment]
Is there any hope to solder the usb otg cable into diagnostic mode in this case? Can you save if  entered in the diagnostic mode?

**Comment by HappyZ** [comment]
yes, if you can get into diagnosis mode, your system can always be saved

**Comment by mumunimu** [comment]
I will wait for a few days to have a usb otg cable and send you feedback. Many thanks

**Comment by HappyZ** [comment]
I have discussed with `shankerzhiwu` and we conclude re-flashing the hacked pkgs may, but theoretically should not disable diag mode. Here are the detailed questions:

1) After you finish `get-su-bin`, what errors did you get? Did you get any errors in previous steps? Most critically, did you get errors when you patch the updater bashes?
2) When you run second time `root`, were you in the normal boot mode (just to confirm)?
3) When you turn on the device **normally**, does the yellow light flash 12 sec ish and stop flashing (turning off the device)? Or it boots up normally, but just stuck at the welcome screen.
4) When you turn on the device in **diag mode**, no square appears, but what happens after then? The device turns off by itself?

**Comment by mumunimu** [comment]
1.I am running in the cmd window, the  logs are not saved.I can't tell the error log accurately.
2.I have no idea ...
3.After press the power button, The screen will flash, it seems to have a backlight, but it is blank, the yellow light flashes for several hours and does not stop or turn off until you press the reset button.The screen is always blank
4. I cannot turn on the device in diag mode now,The only hope I have now is that it can trigger  diag mode with the USB otg line. I still have to wait a few days to know if this method work

**Comment by mumunimu** [comment]
When the device cannot enter the system interface, can dpt-tool  communicate with the device to make it enter diagnostic mode?

**Comment by HappyZ** [comment]
email me at yz at 9pm.me and we can chat in Chinese..

**Comment by HappyZ** [comment]
closed as this has been confirmed a brick.
modified step guide to emphasize not to repeat this
