### ISSUE TITLE
set the language to Chinese

### ISSUE THREAD

**Issue by yanjunhui** [HappyZ/dpt-tools#45]
My DPT-CP1 is an American version. I just want to set the language to Chinese. What do I need to do?

**Comment by sh-miller** [comment]
refer to https://github.com/HappyZ/dpt-tools/issues/37,  @ziegfeld  provide the system.img,  flash it,  then can setup language to Chinese, this in my DPT-RP1 works well, I'm not sure  it can   same applies on DTP-CP1.

**Comment by HappyZ** [comment]
if you already hacked it, just run `adb shell am start -a android.settings.LOCALE_SETTINGS`
otherwise, you need to first root and get diagnosis mode, and then obtain adb access, and finally run the adb command above.

**Comment by HappyZ** [comment]
assuming this has been resolved
