### ISSUE TITLE
-bash: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by worldzhang2010** [HappyZ/dpt-tools#46]
thanks u all!
I encountered a problem in the second step, 

Installing collected packages: pycryptodome, httpsig, pyserial
Successfully installed httpsig-1.3.0 pycryptodome-3.7.2 pyserial-3.4
root@worldzhanggram:~# python dpt-tools.py -ip <192.168.1.139>
-bash: syntax error near unexpected token `newline'

how to solve this? thank you very much!

**Comment by HappyZ** [comment]
you should type `python dpt-tools.py -ip 192.168.1.139`, no bracket

and you shouldn't need root permission to run this tool..

**Comment by worldzhang2010** [comment]
thanks  again! i will try again.

**Comment by HappyZ** [comment]
assuming this has been resolved
