### ISSUE TITLE
help! I followed every procedure and no error appears, but 'adb devices' can not find the device

### ISSUE THREAD

**Issue by phyytang** [HappyZ/dpt-tools#47]
Hi,
Thanks for the great tool. I have an issue that 'adb devices' can not find the rp1 in Mac OS. I can use the tool Serial to login in the diagnosis mode and mount /dev/mmc* and add new files. 

I was trying to add the Browser, but did not find the /data/system to backup the 'ExtMgr.db'. May I ask which  file or directory should I mount to access '/data/system'.

Thanks a lot for your time.

**Comment by HappyZ** [comment]
does `adb devices` at least tell you there is any device?

if not, consider a different cable, or port
and keep it unconnected, try `adb kill-server` and reconnect it

operating in diagnosis mode is not recommended but doable, data partition (in diag mode) can be accessed via `mkdir /mnt/data && mount -t ext4 /dev/mmcblk0p17 /mnt/data`

**Comment by phyytang** [comment]
thanks a lot for the quick reply.

**Comment by phyytang** [comment]
'adb devices' does not tell me anything, just empty after the line 'List of devices attached'.

**Comment by HappyZ** [comment]
> 'adb devices' does not tell me anything, just empty after the line 'List of devices attached'.

in this case it may be a problem of your cable, or port, or something else. I know a lot of `adb` issues out there. This would be out of my areas, unfortunately.. you can try a different machine and see if similar problem exists

**Comment by phyytang** [comment]
Thanks!

It looks that I can not mount the /mmcblk0p17, the above command returns error, although /mmcblk0p9 can be mounted.

root@FPX-1010:/mnt# mount -t ext4 /dev/mmcblk0p17 /mnt/data
mount: mounting /dev/mmcblk0p17 on /mnt/data failed: Invalid argument

I guess maybe my device is not fully rooted.  Anyway, I can live with current state. thanks a lot for the help.

**Comment by HappyZ** [comment]
Ah interesting.. I was told it shall work. Your device is fully rooted. It's just the `adb` thing didn't work out well between your device and computer with the cable. If your device is wirelessly connected, you can also refer to https://stackoverflow.com/questions/14357705/adb-over-wireless.

**Comment by phyytang** [comment]
Thanks for the suggestion. It did not work, neither.  

I managed to download and install some eink launcher, gesture app and 'root explorer' through the Browser, and used 'root explorer' to locate the two files and backup them.

**Comment by sisyphose** [comment]
This problem has also occurred with one of my devices. After the crack is completed, everything is normal, but the adb is not recognized.
Happyz， would you communicate  with me in Chinese？ give me an email？

**Comment by HappyZ** [comment]
Another possibility is you did not successfully flash the boot.img I modded. Instead you flashed the old backed up one. This can be caused by an unsuccessful mount. I suggest after you back up the boot img, remove the backed up boot img in the drive, and restart to diagnosis mode. And then follow the procedure.

@sisyphose  you can send me an email at yz@9pm.me

**Comment by v6v** [comment]
I have the same problem. And I found the error is rename in the `Finder` gives the file `boot.img.bak.img`...
After I redo the process again, everything went all right.
Besides, when do a recovery, pay attention to the md5, maybe you can find something : )

**Comment by HappyZ** [comment]
Thanks for supporting my guesses. I have made an early release of the customized pkg to flash the modded boot.img. In near future, we will use `fw` and flash these customized pkgs like the official ones. Current process is still way too complicated, and sometimes problematic.

**Comment by gitchhub** [comment]
restore-bootimg 
[info]/mnt/sdtmp already exist,we are fine
[info]boot.img.bak MD5:87086....0c5b

it seems the MD5 changed . I copied the file "boot-1.4.01.16100-mod-happyz-181214.img" to the disk and rename it to "boot.img.bak" and i confirm the MD5 is the same as your provided.  I confused that why the MD5 changed....

Is there any problem ?  "adb devices"  list no device

thanks for your tool

**Comment by HappyZ** [comment]
Eject the device, reboot into diagnosis mode again, and retry this step. It
may be the sdtmp is not successfully ejected..


Yz

**Comment by gitchhub** [comment]
thanks a lot for the quick reply.
I tried it twice and the result was the same as before. i found the MD5 was the same as  the boot.img.bak generated by backup-bootimg. i am sure that i copy the file you modified to the dpt-rp1 disk and eject the disk and begin restore img...
could you tell me why is that ...

**Comment by HappyZ** [comment]
After rebooting the device, mounting the disk, is the image the same as the
old one, or the new one? If it's the new one, after you reboot, and skip
the backup process, directly do restore, it should work.

**Comment by gitchhub** [comment]
i copyed the new one to the disk , but after restore-bootimg, it become the old one .

**Comment by gitchhub** [comment]
the new one ,about 11M . i did restore. but MD5  is the old one.
The log is shown below.

.root #: restore-bootimg
> Upload boot img? [yes/no]: yes
[info] Your computer shall have mounted a disk.
[info] Please copy your `boot.img.bak` there.
When done, plz eject disk and press Enter to continue..
> Confirm to continue? [yes/no]: yes
[info] /mnt/sdtmp already exist, we are fine
[info] boot.img.bak MD5: 87086ea02cd9f80777961e9039db0c5b
[info] Fingercrossing.. Do NOT touch the device!
[info] 
4+0 records in
4+0 records out
16777216 bytes (16.0MB) copied, 0.425838 seconds, 37.6MB/s
root@FPX-1010:~# 
[info] Success!

**Comment by mYmNeo** [comment]
Did you use the USB cable which rp1 provides? If not, you can try another USB cable. After changing the USB cable, it resolved.

**Comment by HappyZ** [comment]
I'm making a flash-able pkg so you don't need to go through all the complicated steps. Stay tuned.

**Comment by gitchhub** [comment]
> Did you use the USB cable which rp1 provides? If not, you can try another USB cable. After changing the USB cable, it resolved.

thank you for your advice. I tried several USB cable, but none of them worked...

**Comment by gitchhub** [comment]
> I'm making a flash-able pkg so you don't need to go through all the complicated steps. Stay tuned.

looking forward to your new tools

**Comment by HappyZ** [comment]
@gitchhub if you have done the patch, I have updated the wiki on step 0x5 Obtain Android ADB Access (Optional, Subject to Change). Follow the `easy way`. 

Also, if you are using DPT-RP1, I suggest you try to patch the updater script using script in the `develop` branch, before you flash any PKGs. Right now I need some script confirmation on DPT-CP1 to merge it into main branch.

**Comment by HappyZ** [comment]
closed, we have a flashable PKG now. should not have any problems on flashing it (if patch is applied successfully)

**Comment by gitchhub** [comment]
It worked . I can use the browser in DPT-RP1. Thank you .

发送自 Windows 10 版邮件应用

发件人: HappyZ
发送时间: 2019年1月31日 1:30
收件人: HappyZ/dpt-tools
抄送: gitchhub; Mention
主题: Re: [HappyZ/dpt-tools] help! I followed every procedure and no errorappears, but 'adb devices' can not find the device (#47)

@gitchhub if you have done the patch, I have updated the wiki on step 0x5 Obtain Android ADB Access (Optional, Subject to Change). Follow the easy way.
Also, if you are using DPT-RP1, I suggest you try to patch the updater script using script in the develop branch, before you flash any PKGs. Right now I need some script confirmation on DPT-CP1 to merge it into main branch.
