### ISSUE TITLE
Digital Paper App can not work after root.

### ISSUE THREAD

**Issue by sanigo** [HappyZ/dpt-tools#49]
It did happen after flash boot image, before that it was ok.

**Comment by HappyZ** [comment]
thanks, I assume wirelessly it should work, correct? it's just the cable didn't work. 

If so, this is a known issue, which I should mark. 

If you want, you can restore your back up boot image (after making changes). It will disable adb and mass storage features, but the DPA via usb would work again. The tradeoff would be obvious.

**Comment by sisyphose** [comment]
> thanks, I assume wirelessly it should work, correct? it's just the cable didn't work.
> 
> If so, this is a known issue, which I should mark.
> 
> If you want, you can restore your back up boot image (after making changes). It will disable adb and mass storage features, but the DPA via usb would work again. The tradeoff would be obvious.

One of my devices also encountered this problem, and re-flashing does not solve the problem. Finally I paid for zhishulin to brush his rom solved.
I guess, our package only changed the  part of the system, zhishulin updated all system .

**Comment by HappyZ** [comment]
> > thanks, I assume wirelessly it should work, correct? it's just the cable didn't work.
> > If so, this is a known issue, which I should mark.
> > If you want, you can restore your back up boot image (after making changes). It will disable adb and mass storage features, but the DPA via usb would work again. The tradeoff would be obvious.
> 
> One of my devices also encountered this problem, and re-flashing does not solve the problem. Finally I paid for zhishulin to brush his rom solved.
> I guess, our package only changed the part of the system, zhishulin updated all system .

Interesting. Based on the `boot.img` I got from them, I didn't find any thing. Maybe it's in their `system.img`. Once I got my device back (late Jan), I'll take a look.

**Comment by sanigo** [comment]
Yes it did work wirelessly.

**Comment by HappyZ** [comment]
I can't repeat this. What is your system OS? Windows?

**Comment by HappyZ** [comment]
summarize in #58
