### ISSUE TITLE
Sharing two taobao-pkg, including one from @LadyHack which I believe quite elegant

### ISSUE THREAD

**Issue by xiyuemu** [HappyZ/dpt-tools#52]
Hi, I managed to get two pkg files from TaoBao, I think the one from @LadyHack is quite elegant and well-designed. You could surely get my point from this picture.
![apk](https://user-images.githubusercontent.com/46369844/50719510-fa9b3700-10d7-11e9-845c-38b1b2b1588e.png)
I have uploaded these to [DropBox ](https://www.dropbox.com/sh/qyd65t4oe4u95mu/AABsjCaVvi2Qpq31pYOaqoX6a?dl=0)
Hope it could help you guys. But I must be clear, @LadyHack sell her service at taobao.com for about 1500RMB，I do not have her permission for reverse-engineering, and I don't even need to ask because it will certainly be a waste of time.
Others might want to explore some [eink-friendly app](http://o.ladyhack.cn:88/einkapp/), aslo from @LadyHack. I feel a little guilty but I think she have earned herself a great deal already.

**Comment by HappyZ** [comment]
This is actually a very neat thing to have: one button for a customized app launcher rather than modifying the official launcher, one button for setting, and finally one button for file management

I like this.

**Comment by sekkit** [comment]
Anyway to unpack the pkg? it says encrypted.
** decrypt it via ./key.private
RSA operation error
4332987840:error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error:crypto/rsa/rsa_pk1.c:243:
4332987840:error:04065072:rsa routines:rsa_ossl_private_decrypt:padding check failed:crypto/rsa/rsa_ossl.c:477:

**Comment by sh-miller** [comment]
@xiyuemu   good job !!!   thanks for your sharing,      did you flashed the pkg ?    if i flash the pkg into dpt-rp1  ,  it  will need i input the verify code ,   in other words   the pkg is protected    ?

**Comment by sekkit** [comment]
@sh-miller how u flash them? I just failed. Also unpacking the pkg file throws an error. I mean not the CSDN file, ladyhack's version.

**Comment by xiyuemu** [comment]
> @xiyuemu good job !!! thanks for your sharing, did you flashed the pkg ? if i flash the pkg into dpt-rp1 , it will need i input the verify code , in other words the pkg is protected ?

She did somehow encrypted the firmware, and it was sent to her customers to upgrade devices hacked and sold by her, I'm one of those who have paid 1500RMB and I have no clue how to extract her pkg. She is probably selling this as a job, got every reason to protect the profit.

**Comment by sekkit** [comment]
@xiyuemu could u just dump the whole system image? boot.img&system.img, thx.
seckkit#gmail#com

**Comment by xiyuemu** [comment]
> @xiyuemu could u just dump the whole system image? boot.img&system.img, thx.
> seckkit#gmail#com

sorry, you may wait for someone else, because I have flashed back to the official firmware.

**Comment by sh-miller** [comment]
> @sh-miller how u flash them? I just failed. Also unpacking the pkg file throws an error. I mean not the CSDN file, ladyhack's version.

@sekkit    I  not plan to fresh it, i guess it will protected.

**Comment by HappyZ** [comment]
close this to not mislead users to flash these

they did have online tracking to validate if you bought their services

study purpose only
