### ISSUE TITLE
USB not Working with DPA

### ISSUE THREAD

**Issue by sekkit** [HappyZ/dpt-tools#53]
for some strange reasons, DPA suddenly stopped working with RP1. only wifi can connect to DPA.
no matter I plug into windows or mac, not recognizeable. Diagnosis mode still works.  

PS: This problem was unnoticed which I believe it due to WiFi still working so we just ignored that bug. 

Update: factory_reset.sh, executing this script will be able to connect again.

**Comment by HappyZ** [comment]
I'll take a look when I get the device back

**Comment by HappyZ** [comment]
Q: to clarify, is it working for some days (with usb & wifi), and then `suddenly` it fails to connect with usb? WiFi works any how? https://github.com/HappyZ/dpt-tools/issues/54 @Zack-Q says none works. I wonder.

**Comment by sekkit** [comment]
> Q: to clarify, is it working for some days (with usb & wifi), and then `suddenly` it fails to connect with usb? WiFi works any how? #54 @Zack-Q says none works. I wonder.

Yes, exactly.
Only USB is affected, no matter windows or mac.
If previously got Wifi setup, then it'll connect through WiFi anyhow.

My boot.img is very old one created from you. I remember using ur latest version will definitely cause the issue. The old one seems to be partial working.
The working duration is uncertain. One time I just installed an app called Handshaker and reboot, then DPA stopped working.
Another time I tried to dd partition to /mnt/sdtmp, but it costs so long time(gzip dd)，so I left home and returned an hour later.  typed in reboot, and oops, DPA not working anymore.
The reason is unknown.

**Comment by v6v** [comment]
In my case, DPA not working through both USB or WIFI. 
I can only use `https://github.com/janten/dpt-rp1-py` tool to sync my pdfs to `dpt-rp1` through WIFI.
Since this way works, I believe maybe some problem about how DPA recognize `dpt-rp1`...

**Comment by HappyZ** [comment]
This is weird... If you can use his tool, then DPA shall also work.. as
they use the same way to communicate. Maybe DPA lost your key? Have you
reinstalled DPA before?

**Comment by v6v** [comment]
I have not reinstalled DPA before.
I think maybe the `broadcast/search` step makes the distinction?
After all, I specify IP for the python tool and DPA need to search for itself.

**Comment by HappyZ** [comment]
> I have not reinstalled DPA before.
> I think maybe the `broadcast/search` step makes the distinction?
> After all, I specify IP for the python tool and DPA need to search for itself.

Possible. I'll get my device back the end of Jan. After then I'll take a look at this and gain more insight. Stay tuned.

**Comment by qz-lab** [comment]
> for some strange reasons, DPA suddenly stopped working with RP1. only wifi can connect to DPA.
> no matter I plug into windows or mac, not recognizeable. Diagnosis mode still works.
> 
> PS: This problem was unnoticed which I believe it due to WiFi still working so we just ignored that bug.
> 
> Update: factory_reset.sh, executing this script will be able to connect again.

I ran the `factory_reset.sh` in the diagnosis mode, which locates in `/usr/local/bin`. I have to say, it's really a terrible idea.

The device shut down and the yellow LED kept blinking. I couldn't turn it on and had to push the reset button. Now, the app does recognize the device, with everything erased!!!

**Comment by HappyZ** [comment]
starting a new issue to summarize current findings
#58
