### ISSUE TITLE
Method to Unpack shankerzhiwu_changepwd.pkg & the other one.

### ISSUE THREAD

**Issue by sekkit** [HappyZ/dpt-tools#56]
It always says 
    /tmp/AES256.key not found.
   Or invalid hex key value.

Anybody know how to decrypt that pkg?

**Comment by HappyZ** [comment]
you shall not "decrypt" it, and not using my script to try to decrypt it

his pkg works by providing a malformed key that is at maximum 256 length

the hack works by leveraging the fact that you can actually execute code in block ` `` `. If you look at the binaries, you'll find with decryption it is actually a small block of code
