### ISSUE TITLE
CP1 user: need to see some information in diagnosis

### ISSUE THREAD

**Issue by HappyZ** [HappyZ/dpt-tools#57]
**TL;DR.** Please help post the result in diagnosis mode with the following command:

```
cat /proc/bus/input/devices
```

And also, run the following (after which press your home button and power button)
```
/usr/local/bin/keyscan &
```

Then please paste the results here.

I'm working on preventing a permanent brick. The logic is to detect key pressing event and bypass the update pkg after you get the diagnosis mode working. In this way, even if you have a malformated pkg that causes a software stuck somewhere, we can always bypass it by pressing the HOME key. I can get the key event in RP1 but I'm not sure if CP1 is the same. 

Thanks for your help.

**Comment by pwliao** [comment]
cat /proc/bus/input/devices
```
I: Bus=0019 Vendor=0000 Product=0000 Version=0000
N: Name="pxa27x-keypad"
P: Phys=
S: Sysfs=/devices/platform/soc.2/d4000000.apb/pxa27x-keypad/input/input0
U: Uniq=
H: Handlers=kbd event0 input_boost
B: PROP=0
B: EV=100013
B: KEY=1000 40000800 400 0 0 0
B: MSC=10

I: Bus=0018 Vendor=0000 Product=0000 Version=0000
N: Name="atmel_mxt_ts"
P: Phys=i2c-3-004b/input0
S: Sysfs=/devices/platform/soc.2/d4000000.apb/d4013800.i2c/i2c-3/3-004b/input/input1
U: Uniq=
H: Handlers=kbd event1 input_boost input_boost
B: PROP=0
B: EV=b
B: KEY=1c00 0 0 0 100000 0 0 0 0 0 0
B: ABS=6e18000 0

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="twl6030_pwrbutton"
P: Phys=twl6030_pwrbutton/input0
S: Sysfs=/devices/platform/soc.2/d4000000.apb/d4010800.i2c/i2c-1/1-0049/twl6030_pwrbutton/input/input2
U: Uniq=
H: Handlers=kbd event2 input_boost
B: PROP=0
B: EV=3
B: KEY=100000 0 0 0
```

I run `/usr/local/bin/keyscan > /tmp/keyscan.log &`, and then I pressed home button. After that `/tmp/keyscan.log` is empty. Did I do something wrong?

**Comment by HappyZ** [comment]
thanks, can you just run `/usr/local/bin/keyscan &` and paste the results here.. I guess the buffer isn't flushed 
press HOME and also POWER

**Comment by pwliao** [comment]
I ran it and pressed home button and power button, but nothing was shown on the screen.
<img width="274" alt="20190209" src="https://user-images.githubusercontent.com/12989753/52517389-cc2fef00-2c75-11e9-9f34-5982205aa870.PNG">

**Comment by HappyZ** [comment]
after you entered, just press enter key multiple times (after you pressed power and home button) it will show up; thank you very much

**Comment by pwliao** [comment]
It still didn't show up.

**Comment by HappyZ** [comment]
Nvm, this info is good enough for me.


Thanks again.


Yz
