### ISSUE TITLE
All user: debugging for DPA not working

### ISSUE THREAD

**Issue by HappyZ** [HappyZ/dpt-tools#58]
I can't repeat what happens to you. I can access DPA and mass storage at the same time..

 So if yours didn't work, please clarify:
* ***What operating system you use***, e.g., Windows, MacOS, Linux
* ***What device you have?*** (RP1 or CP1)
* ***Did it work before*** (using the same mod)?
* ***Which part not working*** (USB, WiFi, Bluetooth, etc.)?
* ***Does dpt-tools.py or janten's authentication work?***
* ***Other details***

It appears to be something in `/data/` partition. Need more info.

**Comment by HappyZ** [comment]
by @sekkit:
* ***What operating system you use*** Windows or Mac
* ***What device you have?*** RP1
* ***Did it work before*** yes
* ***Which part not working*** USB
* ***Does dpt-tools.py or janten's authentication work?*** unknown
* ***Other details***
```
My boot.img is very old one created from you. I remember using ur latest version will definitely cause the issue. The old one seems to be partial working.
The working duration is uncertain. One time I just installed an app called Handshaker and reboot, then DPA stopped working.
Another time I tried to dd partition to /mnt/sdtmp, but it costs so long time(gzip dd)，so I left home and returned an hour later. typed in reboot, and oops, DPA not working anymore.
The reason is unknown.
```

**Comment by HappyZ** [comment]
by @v6v:
* ***What operating system you use***
* ***What device you have?***
* ***Did it work before***
* ***Which part not working*** USB and WiFi
* ***Does dpt-tools.py or janten's authentication work?*** yes
* ***Other details***
```
I have not reinstalled DPA before.
I think maybe the broadcast/search step makes the distinction?
After all, I specify IP for the python tool and DPA need to search for itself.
```

**Comment by HappyZ** [comment]
by @sanigo:
* ***What operating system you use***
* ***What device you have?***
* ***Did it work before***
* ***Which part not working*** USB
* ***Does dpt-tools.py or janten's authentication work?***
* ***Other details***
```
It did happen after flash boot image, before that it was ok.
```

**Comment by HappyZ** [comment]
by @sisyphose:
* ***What operating system you use*** 
* ***What device you have?***
* ***Did it work before*** yes
* ***Which part not working***
* ***Does dpt-tools.py or janten's authentication work?***
* ***Other details***
```
One of my devices also encountered this problem, and re-flashing does not solve the problem. Finally I paid for zhishulin to brush his rom solved.
I guess, our package only changed the part of the system, zhishulin updated all system .
```

**Comment by sekkit** [comment]
Tips: run factory_reset.sh solved this problem for me. Only reflashing doesn't work at all. u need to wipe out mmcblk0p17

**Comment by HappyZ** [comment]
@sekkit, `factory_reset.sh` will clear everything.. I am more curious where the root problem is. Based on your feedback, it occurs in `/data/` partition then. So it is not because of the `boot.img` mod.

**Comment by nyanadassana** [comment]
What operating system you use Mac
What device you have? rp1
Did it work before yes 
Which part not working usb
Does dpt-tools.py or janten's authentication work? yes
 it's works yesterday, but today only bluetooth works. I am using your newest boot.img together with the original system.img

update: today bluetooth also will not connect.

**Comment by sh-miller** [comment]
What operating system you use : Mac
What device you have? rp1
Did it work before : unknow, 
Which part not working  : wifi &  usb
Does dpt-tools.py or janten's authentication work? yes

today, I  used  the `factory_reset.sh` in the diagnosis mode, which locates in `/usr/local/bin`.  
 but , the app does  NOT recognize the device yet ,  but system is reseted,   so it how to root it again  ?

**Comment by HappyZ** [comment]
> What operating system you use : Mac
> What device you have? rp1
> Did it work before : unknow,
> Which part not working : wifi & usb
> Does dpt-tools.py or janten's authentication work? yes
> 
> today, I used the `factory_reset.sh` in the diagnosis mode, which locates in `/usr/local/bin`.
> but , the app does NOT recognize the device yet , but system is reseted, so it how to root it again ?

you still have access to diagnosis mode, so you can just re-do `get-su-bin` to get root in Android. Do NOT re-flash the diagnosis access pkgs.

Sadly I still can't repeat this and my DPA recognizes my rp1 still. I guess it has something to do with things modified in `/data/` partition.. maybe I should install more apps to see if I can repeat it

**Comment by HappyZ** [comment]
another related issue #62 
```
dpt-tools.py still work
...
until just now I re-flash the original system.img I mentioned before. suddenly it can connect again.
no devices when I try adb devices. I didn't see my device in adb for a Long time.
update : after few hours, again it can't connect with the DPA.
...
I boot into the diagnosis mode, And I did the the factory reset by: /usr/local/bin/factory_reset.sh
mount the storage partition by boot-recover,
copy the official PKGs modified by happyZ.
reboot.
now it's working! thanks again
```


In short, I suspect DPA stops working because of changes in user space (/data partition). So a factory reset should solve the issue. However, the cause still remains unclear.

**Comment by HappyZ** [comment]
this kinda annoys me as the issue is already here for 1 month.. yet I have never experienced problems like this.. probably it is because i never install apks other than supersu.. i'll try to install other apps lately to see if i can repeat the problem

**Comment by HappyZ** [comment]
Ok I think there's a conflict between mass_storage and acm. Mine works when DPA connects the mass_storage stops functioning. I published a PKG with only adb mods.
