### ISSUE TITLE
RP1 vs CP1

### ISSUE THREAD

**Issue by HappyZ** [HappyZ/dpt-tools#6]
I currently do not have CP1 and I cannot confirm it works the same there. The tool is written and tested for RP1. 

If CP1 has a different firmware (boot.img), then the ones I put in there may not work. Ping me if you have CP1 firmware.

**Comment by mingming1222** [comment]
@HappyZ  hi,  I have a DPT-CP1 and I backed up boot.img
that firmware version is 1.4.02.09061

[boot.img.zip](https://github.com/HappyZ/dpt-tools/files/2612084/boot.img.zip)

**Comment by mingming1222** [comment]
i use boot-1.4.01.16100-mod-happyz-181118.img success boot cp1.  it works! so i think the boot.img is same as RP1.

**Comment by HappyZ** [comment]
When I get time I'll check your uploaded boot.img to double confirm. But thanks for trying it out and confirm it works!

**Comment by HappyZ** [comment]
Ok confirmed the boot img is exactly the same 👍
