### ISSUE TITLE
Fail to use both taobao and csdn pkg shared in #52

### ISSUE THREAD

**Issue by DeeDive** [HappyZ/dpt-tools#61]
I have tried packages shared in #52 using fw function in dpt-tools. But after reboot, I got error message "Unable to update " with error code "900001" and there was nothing changed in my device. Does anyone know the reason? Thanks:)

**Comment by HappyZ** [comment]
they are not using standard pkg format and they have their own encryptions, you cannot flash theirs

fyi they also have online validations that track your device status (as a protection of pirating their efforts), so I do not recommend to touch their systems
