### ISSUE TITLE
How should I input the path after >>>fw?

### ISSUE THREAD

**Issue by yefeiyu** [HappyZ/dpt-tools#65]
```
>>> fw
[info] Please make sure you have charged your battery before this action.
>>> Please enter the pkg file path: 
```
My computer is MacOS. Thanks

**Comment by HappyZ** [comment]
just type the file path.. or you can just drag the file into the terminal on Mac and the path is entered automatically

then press Enter to confirm the input

unless you are saying you cannot type?

**Comment by yefeiyu** [comment]
Thanks! Solved.

**Comment by yefeiyu** [comment]
It's success install the PKG of bluetooth although it's appear `900001` error after reboot.
```
[info] fw updating in progress.. do NOT press anything..
[info] Success!
```
But I can't connect my bluetooth keyboard.
1, Use dpt-rp1 built-in bluetooth, the configuration dialog pops up, but there is no option to operate to connect.
2, Use Launcher's configuration, The Bluetooth keyboard device is displayed and it is not successful after clicking the connection. The messenger is `Can't communicate with FILCO Bluetooth Keyboard.`

**Comment by HappyZ** [comment]
You should use Android settings > Bluetooth to connect.

**Comment by yefeiyu** [comment]
I am use Android Setting, but can not connect.

**Comment by yefeiyu** [comment]
I reinstall the Bluetooth PKG (shows `unable update 90001`), but it is still failure with messenger `Can't communicate with FILCO Bluetooth Keyboard.`
(The SU install with the same way (shows the same messenger  `unable update 90001`), but can open normally)

**Comment by yefeiyu** [comment]
I update taobao IMG (1G size),  [ installed many Launcher(This way seems to be no use)] , and still can not connected with my Bluetooth Keyboad.
Now I reflashed Bluetooth PKG, tomorrow morning I will retry.
```
>>> fw
[info] Please make sure you have charged your battery before this action.
>>> Please enter the pkg file path: /Users/char/gh/dpt-tools/fw_updater_packer_unpacker/pkg_example/flashable_bluetooth_hid/FwUpdater.pkg 
>>> Pleae confirm /Users/char/gh/dpt-tools/fw_updater_packer_unpacker/pkg_example/flashable_bluetooth_hid/FwUpdater.pkg is the pkg file to use [yes/no]: yes
[info] fw updating in progress.. do NOT press anything..
[info] Success!
```

**Comment by HappyZ** [comment]
Just to confirm, have you patched the update script?

And can you please post the logs under /root/updater_xxx.log in diagnosis
mode?

For your error, does your dpt pair with other Bluetooth devices? I'm not
clear about the FILCO error but I'll search it online later tonight.

**Comment by yefeiyu** [comment]
I didn't know where is the `update script?`

**Comment by HappyZ** [comment]
Flashing these PKG I made needs to patch the update script as I said in the
wiki. Check
https://github.com/HappyZ/dpt-tools/wiki/The-Ultimate-Rooting-Guide

**Comment by yefeiyu** [comment]
I follow the step of "DIY Launcher App, ADB Tricks", and I installed the Google Play store form `com.android.vending_9.0.15.apk`
`com.google.android.gms_12.2.17_(234-186052348)-12217234.apk`
 but device shows the messenger:

`The 'AppLauncher' had stopped running.`
`The 'Setting' had stopped running.`

**Comment by HappyZ** [comment]
If you have tried step 5 written there, then it means your modifications have some typos. I do not recommend users who had no knowledge about linux to try to edit these.

**Comment by yefeiyu** [comment]
2 months ago, when I rooted the dpt, I remembered that I had patched the update script.
Now I patched it again. I will retry to connect Keyboard tomorrow.

My /root folder is empty, there has not update***.log.

**Comment by yefeiyu** [comment]
> If you have tried step 5 written there, then it means your modifications have some typos. I do not recommend users who had no knowledge about linux to try to edit these.

Ok, the AppLauncher and Setting `run error` is solved after I reinstall, which reason is that I did not modify the ****(star flower).

I strictly follow the 5 steps of the tutorial, the `error` disappeared, but the app icon did not appear.
I did not know how should to modify the name of the ****(is the Android app intent name).
And I can not delete this 2 files,`ExtMgr.db ExtMgr.db-journal`, Once I restart the dpt it will appear again.

**Comment by yefeiyu** [comment]
Asked more:
If we modify the Bluetooth mode so that it can be typed by Keyboard, can Bluetooth still connect headphones and play sounds? For example, if we use the `Kindle`.app to tip and listen the pronunciation of a new word, can `dpt` play the word's pronunciation through the Bluetooth headset?

**Comment by HappyZ** [comment]
when your dpt restarts, the files suppose to re-appear; maybe you have permission errors reading the folder you created - check the permissions closely

I never tested headset so I can't give more input.

**Comment by yefeiyu** [comment]
Still can't connect Bluetooth Keyboard.

**Comment by HappyZ** [comment]
I need the logs at `/root/updater_xxx.log` to understand what is going on

**Comment by HappyZ** [comment]
close this since we got extensive discussions in #31
