### ISSUE TITLE
Please, Can you help me? my dpr-rp1 is bricked!

### ISSUE THREAD

**Issue by 6bigfire** [HappyZ/dpt-tools#68]
my dpr-rp1 is bricked!
i tryed root twice, and made all the mistakes that in your report!
please
thakyou!

**Comment by yefeiyu** [comment]
You should wite more details

**Comment by yefeiyu** [comment]
You should wite more details

**Comment by HappyZ** [comment]
@6bigfire sorry busy lately.. what are the steps you were doing? what do you mean by "made all the mistakes that in your report"

**Comment by 6bigfire** [comment]
I have used dpt-tools for root, and selected “yes” when the question is “did you already canceled the id check?”
the screen display ”Updating formware…” for a long time, so I reseted the dpt-rp1
now the power led will blink when I pushed the power button, but no any usb devices appear, and nothing display.

Thank you very much for your reply!
发件人: HappyZ <notifications@github.com>
发送时间: 2019年3月2日 8:19
收件人: HappyZ/dpt-tools <dpt-tools@noreply.github.com>
抄送: H <hyman.huo@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [HappyZ/dpt-tools] Please, Can you help me? my dpr-rp1 is bricked! (#68)


@6bigfire<https://github.com/6bigfire> sorry busy lately.. what are the steps you were doing? what do you mean by "made all the mistakes that in your report"

**Comment by HappyZ** [comment]
@6bigfire how did you reset the dpt?

Also, is it still blinking? If so, you should be able to press the `reset` button once to turn the device completely off. It might be the first time you pressed `reset` that turns off the device, but DPT has not finished unpacking the PKG.

If you are sure it is off (no light blinking), what happens when you press the power button again to turn on device?

**Comment by 6bigfire** [comment]
Yes，i reset It, turned the device power off and The led no light blinking. wait for A few seconds, repushed The power button, It's still blinking after power on.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: HappyZ <notifications@github.com>
发送时间: Sunday, March 3, 2019 2:00:32 PM
收件人: HappyZ/dpt-tools
抄送: H; Mention
主题: Re: [HappyZ/dpt-tools] Please, Can you help me? my dpr-rp1 is bricked! (#68)


@6bigfire<https://github.com/6bigfire> how did you reset the dpt?

Also, is it still blinking? If so, you should be able to press the reset button once to turn the device completely off. It might be the first time you pressed reset that turns off the device, but DPT has not finished unpacking the PKG.

If you are sure it is off (no light blinking), what happens when you press the power button again to turn on device?

―

**Comment by 6bigfire** [comment]
I reset the device by the reset button.

发件人: HappyZ <notifications@github.com>
发送时间: 2019年3月3日 14:01
收件人: HappyZ/dpt-tools <dpt-tools@noreply.github.com>
抄送: H <hyman.huo@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [HappyZ/dpt-tools] Please, Can you help me? my dpr-rp1 is bricked! (#68)


@6bigfire<https://github.com/6bigfire> how did you reset the dpt?

Also, is it still blinking? If so, you should be able to press the reset button once to turn the device completely off. It might be the first time you pressed reset that turns off the device, but DPT has not finished unpacking the PKG.

If you are sure it is off (no light blinking), what happens when you press the power button again to turn on device?

**Comment by HappyZ** [comment]
based on what you described I guess it stuck at trying to go into diagnosis mode but failing to do so.

correct if I am wrong:

in your first round, you answered `yes` to the first question so it bypasses to disable OTG ID check, which means you see immediately `Congrats! You are half-way through! You have disabled the OTG ID check`. Then it tries to flash the second PKG, and it stuck at `updating firmware`?

and then, you `long pressed` reset and the device just turns off, or it successfully resets?

**Comment by 6bigfire** [comment]
I think it was flashed the second PKG, but wasn’t flashed the first PKG.

I tried the OTG cable today, but it was no use.

Thank you for your reply!

发件人: HappyZ <notifications@github.com>
发送时间: 2019年3月4日 1:24
收件人: HappyZ/dpt-tools <dpt-tools@noreply.github.com>
抄送: H <hyman.huo@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [HappyZ/dpt-tools] Please, Can you help me? my dpr-rp1 is bricked! (#68)


based on what you described I guess it stuck at trying to go into diagnosis mode but failing to do so.

correct if I am wrong:

in your first round, you answered yes to the first question so it bypasses to disable OTG ID check, which means you see immediately Congrats! You are half-way through! You have disabled the OTG ID check. Then it tries to flash the second PKG, and it stuck at updating firmware?

and then, you long pressed reset and the device just turns off, or it successfully resets?

**Comment by 6bigfire** [comment]
I mean I might be made all the mistake what in the chapter 0x4 in “The rooting guide”
[cid:image001.png@01D4D295.B02A9DD0]
0x4 Patch the Updater Script
In the shell, type patch-updater-bash. It is necessary to prevent a permanent brick if you flashed a malfunctioned PKG.
Once done, do NOT got back to step 0x2 and re-run the command. It may cause a permanent brick, as someone reported.
If this step fails, do NOT power off your device. If you did power off/reboot, you may have a permanent brick. Stay inside diag mode, and manually correct the failed file(s) in /usr/local/bin/(using bash files in assets as an example, and make sure the permission of updater_check.sh and start_eufwupdater.sh are 755 and the ownership is 1496.1496).
Up till here, you have full control over your device (rooted).


发件人: HappyZ <notifications@github.com>
发送时间: 2019年3月4日 1:24
收件人: HappyZ/dpt-tools <dpt-tools@noreply.github.com>
抄送: H <hyman.huo@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [HappyZ/dpt-tools] Please, Can you help me? my dpr-rp1 is bricked! (#68)


based on what you described I guess it stuck at trying to go into diagnosis mode but failing to do so.

correct if I am wrong:

in your first round, you answered yes to the first question so it bypasses to disable OTG ID check, which means you see immediately Congrats! You are half-way through! You have disabled the OTG ID check. Then it tries to flash the second PKG, and it stuck at updating firmware?

and then, you long pressed reset and the device just turns off, or it successfully resets?

**Comment by yefeiyu** [comment]
You can't express your problem clearly enough, we can't judge the behavior or and the mistakes you made, and we even can't understand the specific performance of the mistakes.
Please add three [lower letter of the `~` key] symbols each to your reference at the begin and end of the quote block, it will make the statement clearer.

**Comment by 6bigfire** [comment]
我能说中文么，root的时候选错了，可能只刷了第二个包，结果设备一直显示updating formware后就没响应了，我手工重启了设备，结果最终导致了现在设备完全白屏没反应，只有电源键和复位键有用，按了电源键电源灯会闪硕，桶一下复位就关机了，按home键按电源键结果一样，屏幕始终一片空白，很像是程序根本起不来。今天也尝试做了根OTG线，想试试看程序卡在什么环节了，结果依然没有变化，设备没有反应，接在电脑上不论怎么开关设备，也检测不到任何USB设备。
谢谢，盼望回复。

发件人: yefeiyu <notifications@github.com>
发送时间: 2019年3月4日 22:04
收件人: HappyZ/dpt-tools <dpt-tools@noreply.github.com>
抄送: H <hyman.huo@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [HappyZ/dpt-tools] Please, Can you help me? my dpr-rp1 is bricked! (#68)


You can't express your problem clearly enough, we can't judge the behavior or and the mistakes you made, and we even can't understand the specific performance of the mistakes.

**Comment by HappyZ** [comment]
只刷第二个包（change diagnosis password）应该也是能过的。。 除非非常巧合你在执行破解改密码的时候重启了设备，导致更改密码的时候把`/etc/passwd`改坏了。。
你OTG插上了也进不去从侧面证实了这点
如果你有保险就走保险免费换吧。。
如果没有 那你除非拆机整emmc 不然就是砖了

拆机拆emmc有可能拆下来就上不上去了彻底从soft brick变成了hard brick。。

因为发生了很多起由于制作的破解pkg误操作的问题 加上我的script也不能完全避免变砖 我们想稍微研究一下 具体就是想找一个没有保险 愿意冒险拆机拆emmc的人 你要愿意的话你可以给我单独发邮件yz@9pm.me

**Comment by 6bigfire** [comment]
😭😭😭Let me Think about it, thank you very much!
让我先哭一会儿😭

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: HappyZ <notifications@github.com>
发送时间: Thursday, March 7, 2019 5:55:11 AM
收件人: HappyZ/dpt-tools
抄送: H; Mention
主题: Re: [HappyZ/dpt-tools] Please, Can you help me? my dpr-rp1 is bricked! (#68)


只刷第二个包（change diagnosis password）应该也是能过的。。 除非非常巧合你在执行破解改密码的时候重启了设备，导致更改密码的时候把/etc/passwd改坏了。。
你OTG插上了也进不去从侧面证实了这点
如果你有保险就走保险免费换吧。。
如果没有 那你除非拆机整emmc 不然就是砖了

拆机拆emmc有可能拆下来就上不上去了彻底从soft brick变成了hard brick。。

因为发生了很多起由于pkg导致的事故 shankerzhiwu想找一个没有保险 愿意冒险拆机拆emmc的人 你要愿意的话我帮你搭线寄给他 你可以给我单独发邮件yz@9pm.me<mailto:yz@9pm.me>

**Comment by 6bigfire** [comment]
您好，在电路板上就没有发现在线下载的接口吗？比如UART，ISP，JTAG……
is UART/ISP/JTAG on board?

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: H hyman <hyman.huo@outlook.com>
发送时间: Thursday, March 7, 2019 9:49:01 AM
收件人: HappyZ/dpt-tools; HappyZ/dpt-tools
抄送: Mention
主题: Re: [HappyZ/dpt-tools] Please, Can you help me? my dpr-rp1 is bricked! (#68)

😭😭😭Let me Think about it, thank you very much!
让我先哭一会儿😭

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: HappyZ <notifications@github.com>
发送时间: Thursday, March 7, 2019 5:55:11 AM
收件人: HappyZ/dpt-tools
抄送: H; Mention
主题: Re: [HappyZ/dpt-tools] Please, Can you help me? my dpr-rp1 is bricked! (#68)


只刷第二个包（change diagnosis password）应该也是能过的。。 除非非常巧合你在执行破解改密码的时候重启了设备，导致更改密码的时候把/etc/passwd改坏了。。
你OTG插上了也进不去从侧面证实了这点
如果你有保险就走保险免费换吧。。
如果没有 那你除非拆机整emmc 不然就是砖了

拆机拆emmc有可能拆下来就上不上去了彻底从soft brick变成了hard brick。。

因为发生了很多起由于pkg导致的事故 shankerzhiwu想找一个没有保险 愿意冒险拆机拆emmc的人 你要愿意的话我帮你搭线寄给他 你可以给我单独发邮件yz@9pm.me<mailto:yz@9pm.me>

**Comment by HappyZ** [comment]
nah, there is one, but bootloader time is set to 0 --> you can never be fast enough to get into it, theoretically..

**Comment by 6bigfire** [comment]
请问这个是EMMC在线下载程序的端子吗？我看到网上CP1的拆机图中这个位置是焊接了一个端子座的，但是却没有任何连接。
[Image]
获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: HappyZ <notifications@github.com>
发送时间: Thursday, March 7, 2019 2:10:44 PM
收件人: HappyZ/dpt-tools
抄送: H; Mention
主题: Re: [HappyZ/dpt-tools] Please, Can you help me? my dpr-rp1 is bricked! (#68)


nah, there is one, but bootloader time is set to 0 --> you can never be fast enough to get into it..

―

**Comment by HappyZ** [comment]
im back! so busy.. sorry for the late reply. i can't see your image, for this question you shall ask @shankerzhiwu

**Comment by 6bigfire** [comment]
Thank you very much！I will continue to look for，thank you！

发件人: HappyZ <notifications@github.com>
发送时间: 2019年3月18日 3:02
收件人: HappyZ/dpt-tools <dpt-tools@noreply.github.com>
抄送: H <hyman.huo@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [HappyZ/dpt-tools] Please, Can you help me? my dpr-rp1 is bricked! (#68)


im back! so busy.. sorry for the late reply. i can't see your image, for this question you shall ask @shankerzhiwu<https://github.com/shankerzhiwu>

**Comment by 6bigfire** [comment]
Hello my dear friend, I have a friend can help me redownload emmc program, but I don’t know how to get the original rom file.
Can you send me a set of rom files? Or tell me where can I get it.
Thank you very much!

发件人: HappyZ <notifications@github.com>
发送时间: 2019年3月18日 3:02
收件人: HappyZ/dpt-tools <dpt-tools@noreply.github.com>
抄送: H <hyman.huo@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [HappyZ/dpt-tools] Please, Can you help me? my dpr-rp1 is bricked! (#68)


im back! so busy.. sorry for the late reply. i can't see your image, for this question you shall ask @shankerzhiwu<https://github.com/shankerzhiwu>

**Comment by shankerzhiwu** [comment]
Could you please resend the image you sent 17 days ago. I'll check if it is the download interface. Please do not send an image via e-mail attachments, but directly send on the web interface of github. Thanks!

**Comment by 6bigfire** [comment]
> Could you please resend the image you sent 17 days ago. I'll check if it is the download interface. Please do not send an image via e-mail attachments, but directly send on the web interface of github. Thanks!

I found the interface near the emmc chip, it looks like the emmc bus interface, but I haven't the schematic to check the pin defined.
![interface](https://user-images.githubusercontent.com/21056561/54924807-14fee700-4f48-11e9-860f-c283d0ac4e94.jpg)

**Comment by shankerzhiwu** [comment]
Hi, it seems that the interface is related to the eMMC chip. However without the schematic and thus the pin definition, I don't think it can be utilized to flash the eMMC chip. Desoldering the eMMC chip and using an eMMC programmer should probably work.

**Comment by 6bigfire** [comment]
> Hi, it seems that the interface is related to the eMMC chip. However without the schematic and thus the pin definition, I don't think it can be utilized to flash the eMMC chip. Desoldering the eMMC chip and using an eMMC programmer should probably work.

Thank you for your reply, can you tell me where can I get the rom file and flash tools, I have a friend can help me to desoldering the eMMC chip. And I also wanna try biger ROM size chip too

**Comment by shankerzhiwu** [comment]
For flash tools, I believe your friend should have related tools for reading and writing eMMC chips. With proper tools, the eMMC chip can be connected to a computer like an SD card, and can be modified with WinHEX (on windows) or dd (on *nix).

For the ROM file, I cannot provide you such an image, because there is data which is unique for each device. You cannot directly dump the ROM data from others' devices into your device. You can do a full dump of your eMMC chip and I'll help you to recover it to the original state or see what is exactly broken. I'll be very thankful for you because I and HappyZ have no idea why your operation brought your device into a brick.

**Comment by shankerzhiwu** [comment]
Be careful about desoldering and re-soldering the eMMC chip, because the PCB board is very thin  and can easily get over heated.

**Comment by 6bigfire** [comment]
Thank you very much！I will be careful to do that.
My friend is working in PCB soldering factory. We can find the experienced fellow to help us.
And I found an eMMC change service for smartphone in Taobao, May be they can help me too.

**Comment by shankerzhiwu** [comment]
And another reminder. If you want to replace the eMMC chip itself rather than repairing its content, be sure to also copy the two eMMC boot partitions, or the device will refuse to startup. However, as far as I know, eMMC flash tools can seldom deal with boot partitions.

**Comment by 6bigfire** [comment]
OK，I will buy a new chip to repaire the device. when I desoldered the original chip and read the contents successed，I will contact you first before solder the new chip.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: shankerzhiwu <notifications@github.com>
发送时间: Tuesday, March 26, 2019 9:06:36 PM
收件人: HappyZ/dpt-tools
抄送: H; Mention
主题: Re: [HappyZ/dpt-tools] Please, Can you help me? my dpr-rp1 is bricked! (#68)


And another reminder. If you want to replace the eMMC chip itself rather than repairing its content, be sure to also copy the two eMMC boot partitions, or the device will refuse to startup. However, as far as I know, eMMC flash tools can seldom deal with boot partitions.

―

**Comment by 6bigfire** [comment]
The eMMC chip has been removed.
![dpt-rp1 eMMC pads](https://user-images.githubusercontent.com/21056561/55678364-dcd5ac00-592a-11e9-8984-d821f6874b82.jpg)

**Comment by 6bigfire** [comment]
Definition of solder pad for DPT eMMC chip.
![dpt-rp1 eMMC pads define](https://user-images.githubusercontent.com/21056561/55678383-4eadf580-592b-11e9-90ab-253c28efb0be.jpg)

**Comment by 6bigfire** [comment]
> 
> 
> And another reminder. If you want to replace the eMMC chip itself rather than repairing its content, be sure to also copy the two eMMC boot partitions, or the device will refuse to startup. However, as far as I know, eMMC flash tools can seldom deal with boot partitions.

I don't have an eMMC programmer. I bought an eMMC reader from Taobao and a compatible Toshiba 128G eMMC chip （THGBMHT0C8LBAIG）before. But the reader can not support the chip work after eMMC 5.0 standard, so I'm waiting for the available reader to arrive.
![unworked eMMC reader](https://user-images.githubusercontent.com/21056561/55695289-947dc300-59ea-11e9-8742-bf6d07d78ecc.jpg)

**Comment by 6bigfire** [comment]
> And another reminder. If you want to replace the eMMC chip itself rather than repairing its content, be sure to also copy the two eMMC boot partitions, or the device will refuse to startup. However, as far as I know, eMMC flash tools can seldom deal with boot partitions.

Hi Shankerzhiwu，My new eMMC reader is working properly. All partitions can be opened in WinHex. The directory and file structure of partitions can also be seen. Please tell me what to do next. My mailbox, hyman.huo@outlook.com
Thank you very much，I will waiting for your reply！

**Comment by HappyZ** [comment]
closed as we figured out the reason.

this is related to Windows only: when you clone the git, it may change the script newline byte `\n` into `\r\n`. This in the update script will brick the device and stops it from booting into diagnosis mode.

However, we no longer have this issue as I have packed all scripts inside the installable PKG file. Cheers.

**Comment by 6bigfire** [comment]
Congratulation! Cheers!

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: HappyZ <notifications@github.com>
发送时间: Wednesday, April 10, 2019 4:11:45 AM
收件人: HappyZ/dpt-tools
抄送: H; Mention
主题: Re: [HappyZ/dpt-tools] Please, Can you help me? my dpr-rp1 is bricked! (#68)


Closed #68<https://github.com/HappyZ/dpt-tools/issues/68>.

―
