### ISSUE TITLE
Instructions for changing the standby screen

### ISSUE THREAD

**Issue by tacosundae** [HappyZ/dpt-tools#69]
Well I spent some hours digging and figured out how the standby screen is managed. It seems that I should have looked in the issues first and saved myself some time as this is already discussed in #27 .

I did gather a bit more detail though and thought I would share it here.

The screen is rendered at boot by com.android.server.power.PowerManagerService . PowerManagerService calls configChanged in com.sony.infras.standbyscreenmanager.StandbyScreenManager . StandbyScreenManager renders a layout to a bitmap and sets the standby screen by calling setStandbyScreenBitmap in com.sony.infras.dp_libraries.systemutil.SystemUtil$EpdUtil. These classes can be found in /system/framework/arm/services.odex .

The layout is defined in /system/framework/framework-res.apk at /res/layout/screen_standby.xml . This layout refers to @drawable/img_digitalpaper_stamp which can be found at /res/drawable-mdpi-v4/img_digitalpaper_stamp.png. It also refers to @string/STR_SCRLINE_1001 which is the "Pressing the power button" line at the top. This can be found in /res/values/strings.xml.

Easy mode is to just replace /res/drawable-mdpi-v4/img_digitalpaper_stamp.png in framework-res.apk with your own image and then reboot the device. But since this is rendered from a layout you can get fancy with it if you like.

Step by step:
- Pull the apk from the device through adb.
  `adb pull /system/framework/framework-res.apk`
- Decode the apk with apktool.
  `apktool decode framework-res.apk`
- Make whatever modification you intend to the resources mentioned above.
  `cp ~/new-image.png framework-res/res/drawable-mdpi-v4/img_digitalpaper_stamp.png`
- Rebuild the apk with apktool keeping the original signature and manifest.
  `apktool build --copy-original framework-res`
- Push the rebuilt apk to a location on the device that happy's adbd has write permission to.
  `adb push framework-res/dist/framework-res.apk /storage/sdcard0`
- Remount the system partition read-write.
  `adb shell su -c "mount -o rw,remount /system"`
- Backup the original for easy fix if things go wrong.
  `adb shell su -c "cp -p /system/framework/framework-res.apk /system/framework/framework-res.apk.bak"`
- Move the new apk into place.
  `adb shell su -c "mv /storage/sdcard0/framework-res.apk /system/framework/framework-res.apk"`
- Fixup the ownership and permissions
  `adb shell su -c "chown root:root /system/framework/framework-res.apk"`
  `adb shell su -c "chmod 0644 /system/framework/framework-res.apk"`
- Finally reboot the device

If all went well your modifications should be visible after the device reboots. 

If all did not go well you will be stuck at the spinning arrows. You should still be able to adb shell in and put the original back in place and ensure the ownership and permissions are as above. As soon as this is done the boot will complete.

![20190301_122231](https://user-images.githubusercontent.com/4822400/53658315-0d387500-3c1e-11e9-99b2-d89e5f85ca68.jpg)

**Comment by yefeiyu** [comment]
Thank you for your works.

**Comment by HappyZ** [comment]
this is awesome! I like "DIGITAL POOPER" lol

if you don't mind, please copy your stuff into wiki, which I believe is a better place for a tutorial :)

**Comment by tacosundae** [comment]
Done, should have thought of that earlier.

**Comment by HappyZ** [comment]
closed as it is in tutorial now, thx @tacosundae

**Comment by linux40** [comment]
Thank you. The standby screen on my machine shifts to left after some operations and I don't know the reason. And this shift induces a black strip on the right side of the screen. At last, I have to modify `screen_standby.xml` to change the color of the whole screen to black, so hide the problem.
