### ISSUE TITLE
About Proper Donations

### ISSUE THREAD

**Issue by kitsek** [HappyZ/dpt-tools#70]
Hi, I noticed there were some people selling dpt-tools for 499 yuan by remote-control. 
Have they ever donated to this project I wonder?
It seems most of them will spend more than 30mins to an hour to finish ROOT process. Some of them sold more than 100 units of dpt-tools at high price. Strongly doubt whether it's a violation of Open Source protocols.

**Comment by HappyZ** [comment]
Wow.. I didn't know that.. Even a single charge would be way beyond all donations I got.. so nope I guess not.

Regarding your question: selling is permitted under MIT license. It should be okay to sell/modify my tool, except they should include the copyright notice. I can't control this much, as MIT is a permissive license. I do hope they will acknowledge our efforts here. 

Thanks a lot for the notice. The original idea is for study purpose, and that no one needs to pay for the hack. (In a sense, we did lower the cost among all sellers). But as I said, you can't control it.

(fyi the root process should take literally <5minutes..)

Regarding your title question, PayPal is the method I provide. I don't know how to set up WeChat donations :)

**Comment by yefeiyu** [comment]
It's need to download and register WeChat or Alipay on mobile phone, bind a bank card, generate the QR code, and then put the picture here.

**Comment by HappyZ** [comment]
that's cool.. I never tried that

I added it to the wiki page :)

**Comment by yefeiyu** [comment]
You better add it to the `README.md`, and put it at the top of the page.
