### ISSUE TITLE
how to quit from diagnosis and reboot to normal system?

### ISSUE THREAD

**Issue by samos1808** [HappyZ/dpt-tools#71]
Hi, HappyZ,
thanks a lot. I have successfully root my dpt-rp1.
but I don't know how to quit the diagnosis mode which you have not mentioned in your guide.
now the machine's light is blinking, I don't know how to do with it.
how to quit from diagnosis and reboot to normal system?
thanks

**Comment by HappyZ** [comment]
in the tool type `reboot &` (if you already exit the tool, use `python dpt-tools.py --diagnosis`)

or lightly press the RESET button once in diagnosis mode, it will power down - then press POWER to boot up

**Comment by samos1808** [comment]
thank you. Happyz.
