### ISSUE TITLE
i can not understand this step

### ISSUE THREAD

**Issue by samos1808** [HappyZ/dpt-tools#72]
> Download FwUpdater.pkg from this example.
> Boot into normal system, use fw in the tool to update with the downloaded PKG*. After update, it will say update failure, but it is actually flashed.

1.Boot into normal system.   how to boot into normal system when I was in a diagnosis mode?
2.fw in the tool.    what tool? fw is a command? or something else?
3,how to "use fw in the tool to update with the downloaded PKG"
**is that mean? :**
first connecting to computer, in terminal of computer:
`python dpt-tools.py -id 188.34.23.22`
and then:
`fw FwUpdater.pkg`

**Comment by HappyZ** [comment]
All the rest steps are for normal system. 

> > Download FwUpdater.pkg from this example.
> > Boot into normal system, use fw in the tool to update with the downloaded PKG*. After update, it will say update failure, but it is actually flashed.
> 
> 1.Boot into normal system. how to boot into normal system when I was in a diagnosis mode?

#71 check

> 2.fw in the tool. what tool? fw is a command? or something else?

use `python dpt-tools.py -ip xxx` and then type `fw`

> 3,how to "use fw in the tool to update with the downloaded PKG"
> **is that mean? :**
> first connecting to computer, in terminal of computer:
> `python dpt-tools.py -id 188.34.23.22`
> and then:
> `fw FwUpdater.pkg`

Correct. After you do `fw`, it will ask you for the file path. Just enter the file path of the pkg file.

**Comment by samos1808** [comment]
haha , I got the first question's answer.
just type reboot in diagnosis mode.
` reboot `

**Comment by HappyZ** [comment]
thanks for the feedback, and I have updated the wiki

**Comment by samos1808** [comment]
thank you, HappyZ.
great work you have done.

**Comment by samos1808** [comment]
and I have another feedback
after this command:
` python dpt-tools.py --diagnosis`
and follow steps to enter diagnosis, and got the question:
> black square on the screen? [yes/no]:

and I type:
` yes`
then, system prompts: 
> enter the serials port [/dev/tty.usbmodem01]:

the default answer /dev/tty.usbmodem01 does not work in window 10 system. in device manager of my computer I found this device is com5. so I type:
`com5`

**Comment by HappyZ** [comment]
changed wiki based on your feedback
