### ISSUE TITLE
Two Problems, help

### ISSUE THREAD

**Issue by sixis2010** [HappyZ/dpt-tools#76]
hi, I've used dpttools for jailbreaking my device
Previously it worked well, but sometime later the Digital Paper app stopped working by not recognizing through USB. But luckily I can still connect through WIFI. Also I flashed Bluetooth pkg.
And I tried to restore the original firmware and it says AppLauncher stopped working, Bluetooth stopped working etc. And I wanna try jailbreak again, but finally my device got stuck on booting screen, never had a chance to boot into OS.

Im kinda depressed, what's happening?

**Comment by HappyZ** [comment]
patpat, you have multiple things tried so let's sort it out..

first of all, are you still able to get into diagnosis mode?

second, when you say it sucks at boot screen, can your computer see the usb connection and connect via adb?

**Comment by HappyZ** [comment]
If you stuck at boot screen, are you able to use `adb`? If so, try the wiki on the suggested mod: https://github.com/HappyZ/dpt-tools/wiki/Suggested-Launcher-Mod

**Comment by HappyZ** [comment]
let me know if you have fixed it

**Comment by sixis2010** [comment]
Im bak.
I just couldn't enter diagnosis mode and tried everything I can search of.
Except for getting a OTG cable which is way too complicated for me.

Finally I SOLD it to a Xianyu dude who claimed that he can fix it himself. As a bricked device.
Now I feel much better get rid of this complex tool.
Anyway, I've an another NotePro reader with backlight now. Which saves my time of digging around.

Thanks anyway, for your efforts into this project.

**Comment by HappyZ** [comment]
Good for you.
