### ISSUE TITLE
mingw64

### ISSUE THREAD

**Issue by ghost** [HappyZ/dpt-tools#77]
xxxxx@DESKTOP-QV2HMLF MINGW64 /c/dpt-rp1-py-master
$ dptrp1 --client-id deviceid.dat --key privatekey.dat --addr 172.30.1.8 list-documents
Traceback (most recent call last):
  File "C:/Users/gkhs1/AppData/Local/Programs/Python/Python37/Scripts/dptrp1", line 161, in <module>
    with open(args.client_id) as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'deviceid.dat'

what problem? what should i do for solving ??
please answer . thanks

**Comment by HappyZ** [comment]
that is dptrp1 issues, please refer to their github
