### ISSUE TITLE
Have someone tested the updated method on Windows10?

### ISSUE THREAD

**Issue by ya0guang** [HappyZ/dpt-tools#78]
I plan to root my rp1 but I'm not sure if it can be used on Win10.
My dpt is still in warranty. But it was bought in another country, so using it is a bit troublesome.
By the way, I saw there are several commits today, are all things done now? Or I should wait for a while? Since I see the root section in the root guide is still subject to change.
If no one else try this, I would like to try it on Win10 :)

**Comment by HappyZ** [comment]
it should work fine with windows, as you need nothing but just update firmwares

**Comment by ya0guang** [comment]
I've tested and it works well with my Win10 and python 3.7.2. Thanks a lot!
