### ISSUE TITLE
2+1 records in /out

### ISSUE THREAD

**Issue by ghost** [HappyZ/dpt-tools#79]
Right rooting have to records 2+1 records in /out? 
[](url)
My results was 0+1 records in /out 
i do not know why was that 
and i failed. 
do u know why was that?
what is the means that 2+1 records?

**Comment by HappyZ** [comment]
Need a bit more details.

**Comment by HappyZ** [comment]
Maybe you can get the log and take a photo of the record and mark where this happens. I have no idea what you mean by 2+1 records in/out

**Comment by ghost** [comment]
at the last step in mingw64,
>Confirm to continue? [yes/no]: yes
[info]/tmp/sdtmp already exist, we are fiem
[info]/tmp/sdtmp/boot.img.badk MD5:1867e8378c68753224677 ........
[info] Fingercrossing Do NOT touch the device!
[info]
2+1 records in 
2+1 records out
11239424 bytes (10.7MB) copied , ........
root@FPX-1010:#
[info]Success!
that is the right resuts that iknow
 
but my results is 0+1 records in 
                           0+1 records out 
then reboot , no bootimage appear just blank white screen.
so i restored firt bootimg.bak file upload, 
that was 4+0 records in
    4+0 records out 
and my dpt goes back to first screen that was before rooting.


why my wrong rooting that records 0+1?

...

**Comment by HappyZ** [comment]
are you trying to change the boot image? 

when you copy the img to the disk, eject properly. best is after you copied, reboot dpt first, and check if in the disk it is the correct img, and then recover

0 means no file found

**Comment by hyunky** [comment]
Can u explain how do eject???

**Comment by hyunky** [comment]
What mean eject disk????

**Comment by hyunky** [comment]
And  one more question,,
When i update pkg file JB JB2 ...
Dpt cp1 appear 
Error 900001
Is it okay ???
That is concerned with upper issue???

**Comment by hyunky** [comment]
When eject disk 
Should i do hardware safety eject that usually do when we use plastick usb ?
Is it same???

**Comment by HappyZ** [comment]
I suggest you to use my PKGs instead of using the script to manually do the boot img update.

**Comment by hyunky** [comment]
Where is the PKGs????

**Comment by HappyZ** [comment]
READ THE WIKI before what you are actually doing. If you have questions not stated in the wiki, clearly state what you are doing, and what you did wrong.

Just fyi, you should learn to respect people when you type multiple question marks.

**Comment by ghost** [comment]
I ‘m sorry for lots of question.
Thank u for answering!!!!
And thank u for developing!!!

**Comment by HappyZ** [comment]
closed as wiki should have explained all necessary steps; if further questions rise, please start a new issue and describe it specifically
