### ISSUE TITLE
adb does not recognize the device

### ISSUE THREAD

**Issue by zye1996** [HappyZ/dpt-tools#81]
Hi, it seems that I successfully update the firmware (as the rp1 is connected as a mass storage device). But I cannot find the device through adb devices command. Is there any advice?

**Comment by HappyZ** [comment]
can you try a different cable, or restart adb server via `adb kill-server && adb start-server`? If you are on linux, it seems you need sudo permission to see devices via `adb devices`.

Or, you can go into the diagnosis mode, mount the system partition, and check the log there to see if adbd is started.

**Comment by zye1996** [comment]
I checked the wire and it should be no problem. Could you give me more detailed description about how to find the log file in diagnosis mode?

**Comment by zye1996** [comment]
And the devices is shown as a USB serial device on the computer instead of an Android device. Is it what supposed to be?

**Comment by HappyZ** [comment]
It supposes to have the serial connection for DPA. What if you flashed the
one without mass storage?


I'll take a close look tomorrow when I get home.

**Comment by zye1996** [comment]
I did both but neither PKGs work

**Comment by HappyZ** [comment]
what did it say when you run `adb devices`? just empty list?

I looked into the image but didn't find anything suspicious.  If you exit DPA, restart the device but keep the cable connected, will `adb devices` show you anything?

FYI, what system were you using? MacOS?

**Comment by zye1996** [comment]
I get an empty list from **adb devices**. I tried both Windows and Ubuntu. Let me try what you suggest and get back to you.

**Comment by zye1996** [comment]
adb still shows nothing. how would adb search through devices attached and check whether the devices is enabled adb?

**Comment by HappyZ** [comment]
Sometimes the cable does not have data pin connected and you can only charge it via the cable. Just to confirm if you can use the same cable for DPA connections before. 

In your Ubuntu, what does `lsusb` say after you plug in?

**Comment by HappyZ** [comment]
@zye1996 I just tested many more times, and it indeed can be slow to load up the adbd module since I've used an in-secured version (rooted on its own). In my "not working" case, I have to wait for a minute or two after the device turns on.. You just have to be patient and keep trying `adb kill-server && adb start-server && adb devices`. 

And `lsusb` and `dmesg` on ubuntu can tell you more info.

**Comment by HappyZ** [comment]
closed as there are no further discussions. similar findings are already discussed in wiki rooting guide. The idea is if current pkg does not work (slow start on the insecured adbd), then user can try the old pkg with a fixed adb key provided before. Check wiki and #87 for more details.
