### ISSUE TITLE
About AppLauncher stop issue

### ISSUE THREAD

**Issue by kzmain** [HappyZ/dpt-tools#84]
Dear HappyZ.
Thanks you very much for your tool. I cracked it successfully, however I encounter a problem.

I modified .`/system/app/AppLauncher/AppLauncher.apk` to check if it can change width or numbers of icon. Moreover I forgot to backup it. Now it shows "AppLauncher Stopped" when I click home button.

I already used system resetting and --diagnosis mode to recovery but this situation still happens.

After I ran `adb logcat | grep "launcher"` it shows:

> E/AndroidRuntime( 4902): 	at com.sony.apps.applauncher.presentation.presenter.impl.LaunchMenuPresenter.initialize(LaunchMenuPresenter.java:117)
> E/AndroidRuntime( 4902): 	at com.sony.apps.applauncher.presentation.presenter.impl.LaunchMenuPresenter.<init>(LaunchMenuPresenter.java:37)
> E/AndroidRuntime( 4902): 	at com.sony.apps.applauncher.presentation.service.impl.LaunchViewService.initialize(LaunchViewService.java:122)
> E/AndroidRuntime( 4902): 	at com.sony.apps.applauncher.presentation.service.impl.LaunchViewService.onCreate(LaunchViewService.java:46)
> W/ActivityManager( 2143): Process com.sony.apps.applauncher has crashed too many times: killing!
> W/ActivityManager( 2143): Killing 4902:com.sony.apps.applauncher/u0a14 (adj 0): crash
> W/ActivityManager( 2143): Spurious death for ProcessRecord{38a0a1d 4902:com.sony.apps.applauncher/u0a14}, curProc for 4902: null
> W/BroadcastQueue( 2143): Unable to launch app com.sony.apps.applauncher/10014 for broadcast Intent { act=com.sony.infras.DPExtensions.MenuKeyHandler.MENU_KEY_PUSHED flg=0x10 }: process is bad
> W/BroadcastQueue( 2143): Unable to launch app com.sony.apps.applauncher/10014 for broadcast Intent { act=com.sony.infras.DPExtensions.MenuKeyHandler.MENU_KEY_PUSHED flg=0x10 }: process is bad

May you help me? Or give me a copy of original `AppLauncher.apk` to have a try? Thank you very much.

**Comment by HappyZ** [comment]
here is the original AppLauncher apk and its odex: 
[AppLauncher.tar.gz](https://github.com/HappyZ/dpt-tools/files/3036855/AppLauncher.tar.gz)


make sure you set it to the correct permission (0644) and ownership (root:root)

**Comment by kzmain** [comment]
@HappyZ Thank you very much for your help.
I solved this problem by replaced `AppLauncher.apk` given by you.

Step 1: Replace the `AppLauncher.apk` in dpt-rp1
adb shell su -c "mount -o rw,remount /system"
adb push <original AppLauncher.apk local on pc> /storage/sdcard0
adb shell su -c "mv /storage/sdcard0/AppLauncher.apk /system/app/AppLauncher/AppLauncher.apk"
adb shell su -c "chown root:root /system/app/AppLauncher/AppLauncher.apk"
adb shell su -c "chmod 0644 /system/app/AppLauncher/AppLauncher.apk"

Step 2: Re-initial AppLauncher.apk
Follow instruction of ["Suggested Launcher Mod" ](https://github.com/HappyZ/dpt-tools/wiki/Suggested-Launcher-Mod) in wiki

Step 3: Reboot

**Comment by kzmain** [comment]
But an interesting thing is that when I try to recovery the system by offical pkg. (By fw method). It did do something (like updating GUI), but finally it said failed to recover and gave a error message. Furthermore it made adb mode no longer work it seems reset some setting and the AppLauncher.apk still not work at that time. May these can give you some help.

**Comment by HappyZ** [comment]
yes, error message always appears as we did not change any version numbers - which is checked by the system.

adb shall work, except it's now slow to load (my guess is due to insecured adbd version)..
