### ISSUE TITLE
Reduced pen accuracy on CP1

### ISSUE THREAD

**Issue by xaelectronics** [HappyZ/dpt-tools#85]
CP1 - Pen location accuracy is significantly decreased around the edges of the screen after flashing custom FW. Accuracy in the center of the screen is fine. Calibration does not help.

Reflashing to original FW fixes the issue.

**Comment by HappyZ** [comment]
which one were you flashed that affected pen accuracy?

**Comment by xaelectronics** [comment]
Tried both pkgs, [without mass storage](https://github.com/HappyZ/dpt-tools/tree/master/fw_updater_packer_unpacker/pkg_example/flashable_mod_boot_img_no_mass_storage) and [with](https://github.com/HappyZ/dpt-tools/tree/master/fw_updater_packer_unpacker/pkg_example/flashable_mod_boot_img).

**Comment by HappyZ** [comment]
this is interesting.. i compared the boot partitions, and CP1 and RP1 do not have difference in terms of the software configurations.. I would hope more people report a similar issue to confirm. I don't have a device, but can you show a screenshot or photo image how bad it is on the edge of the screen?

**Comment by xaelectronics** [comment]
https://www.youtube.com/watch?v=huYzbFvKKVw

First two strokes in the top left are drawn exactly along the vertical graph line but appear shifted to the right. You can watch the video in slow motion to see it more clearly. Writing in the bottom right corner is completely screwed up.

I think it's related to the difference in display size. When I flash your custom FW, the update message that shows up is off center and partially off screen.

**Comment by HappyZ** [comment]
I only find one single kernel object in cp1 package that differs from rp1 and im not sure if it is related to your problem. Try this PKG: https://github.com/HappyZ/dpt-tools/blob/master/fw_updater_packer_unpacker/pkg_example/flashable_mod_boot_img_no_mass_storage_cp1/FwUpdater.pkg

If it doesn't solve the problem, I would have no idea why it happens. Let me know.

**Comment by HappyZ** [comment]
https://github.com/HappyZ/dpt-boot-img/commit/6929d2eeaec88ee2a6d0df06a2b3e93cde15dd91
here shows the only difference in git

**Comment by HappyZ** [comment]
@xaelectronics does it work?

**Comment by iuyo5678** [comment]
I also met the same problem, and finally had to use the official firmware....

**Comment by HappyZ** [comment]
firmware is being updated and both device firmwares are unified, closed as I expect there are no more issues related to the script; any further inaccuracy issue shall direct to the dpt company
