### ISSUE TITLE
lock screen not work  

### ISSUE THREAD

**Issue by seanlvjie** [HappyZ/dpt-tools#86]
I installed E-Ink-Launcher_0.1.4.apk, but the lock screen button doesn't work.

could you help ?

**Comment by HappyZ** [comment]
can you give more details? what machine you were using? what you mean by "doesn't work"?

**Comment by seanlvjie** [comment]
The machine is SONY DPT-RP1.

after installing E-Ink-Launcher_0.1.4.apk,  there is a button in the home screen, named Lock Screen.  I click but the RP1 didn't locked by design.

**Comment by HappyZ** [comment]
ah, i see.. yea.. this would be related to e-ink-launcher itself.. mine also didn't work.

you should report this issue there

closed.
