### ISSUE TITLE
Am I bricked T_T?

### ISSUE THREAD

**Issue by elamarkant** [HappyZ/dpt-tools#88]
Sorry to bother you ~~>_<~~

My device is _CP1 with fw version 1.4.02.09061._
MacOS
I've cloned the repo and did things follow the rooting guide.

Flashed 
_https://github.com/HappyZ/dpt-tools/blob/master/fw_updater_packer_by_shankerzhiwu/pkg_example/hack_basics/fw.pkg_
and then
_https://github.com/HappyZ/dpt-tools/blob/master/fw_updater_packer_unpacker/pkg_example/flashable_mod_boot_img_no_mass_storage_cp1/FwUpdater.pkg_

Every time I got rebooted and error message
_"Unable to update error code 900001"_

Then I tried diagnosis command and here's all the action and output
_>>> diagnosis
[info] Steps to enter diagnosis mode:
[info] 1. Turn off DPT
[info] 2. Hold HOME button
[info] 3. Press POWER button once. Then light blinks yellow
[info] 4. Release HOME button, a black square will show up
[info] 5. Connect to computer
>>> Black square on the screen? [yes/no]: yes
>>> Enter the serial port [/dev/tty.usbmodem01]: /dev/tty.usbmodem01
[error] Cannot open serial port /dev/tty.usbmodem01 due to [Errno 2] could not open port /dev/tty.usbmodem01: [Errno 2] No such file or directory: '/dev/tty.usbmodem01'

/dev/tty.usbmodem1
^C[error] 
[error] cannot get nonce
[error] Cannot reauthenticate, did you reboot into normal mode?
[error] Client id filepath: /Users/yuxiangzhai/Library/Application Support/Sony Corporation/Digital Paper App/DigitalPaperApp/ws043a428114aa44d382cb536d248f3b9a/deviceid.dat
[error] Client key filepath: /Users/yuxiangzhai/Library/Application Support/Sony Corporation/Digital Paper App/DigitalPaperApp/ws043a428114aa44d382cb536d248f3b9a/privatekey.dat_

When I typed "/dev/tty.usbmodem01" it said no such file, and after I checked it was "/dev/tty.usbmodem1" so I typed it as the output showed...and wait a little time and
type _"control+c"_       T_T
and I've got an orange blinked power led CP1...four square on screen and no key have effect...
usb pluggeg-in with orange-red blinked power led
adb devices with no device

I haven't touched the reset key once...
Am I bricked...?

**Comment by HappyZ** [comment]
you are not :)

it's just in diagnosis mode

restart the tool via `python dpt-tool.py --diagnosis`

and no need to press the button, just directly answer yes and fill in `/dev/tty.usbmodem1`

you shall be able to get into diagnosis mode

I did not allow a second chance of inputing serial port which is why you encounter this..

regarding your prior question: `Unable to update error code 900001` is always shown, even if you succeeded.

**Comment by HappyZ** [comment]
once you confirmed you are in diagnosis mode, it is safe to press `reset` button once (lightly) to turn off the device. then you can press "power" button to turn the device back on

or equivalently, just use the tool and type "reboot &" in the command line and quit the tool

**Comment by elamarkant** [comment]
Many thanks!
Thank god you didn't allow a second chance...
I've rebooted successfully into normal mode.
Maybe I should learn some python to figure it out and not bother you again.
Thanks again.

**Comment by stevenvo** [comment]
I was also stuck in diagnosis mode and this wiki saved my bricked device! https://github.com/HappyZ/dpt-tools/wiki/diagnosis-mode-in-terminal

particularly: 

```
rawdata --set_dump=boot_mode < /dev/zero
reboot
```
