### ISSUE TITLE
How to restore the backed-up system.img 

### ISSUE THREAD

**Issue by tartakis** [HappyZ/dpt-tools#90]
After many failed attempts to update my DPT-RP1 to the newest firmware, I ended-up in a situation where after powering on following message appears:

> Unfortunately, USBDeviceSwitcher has stopped

 followed by the "Please wait" box. And it stops there for ever. I tried to restore the system.img I backed-up but I think it fails. This is the output I am getting:
```
> Is it a sparse image? [yes/no]: yes
> Confirm to continue? [yes/no]: yes
[info] /mnt/sdtmp already exist, we are fine
[info] /mnt/sdtmp/system.img MD5: 55d788734c7ea48e9a29b0efcc2c59ed
[info] Fingercrossing.. Do NOT touch the device!
[info] 
Invalid sparse file.
failed to extract sparse file.
root@FPX-1010:~# 
[info] Success!
```
What am I doing wrong?

**Comment by HappyZ** [comment]
First of, the error usually occurs when you have problems in user data
space, not system. You probably should try to reset first.


How did you back up?

If you used dd, then you should answer no to the qurdtion on sparse file.


I'll release an update this weekend, for both new firmware as well as
easier device recovery. You probably can wait for it till tomorrow, before
you try something unrecoverable.

**Comment by vznoopy** [comment]
I also noticed a problem before updating the new firmware.

Prior to this, I modified the RP1 according to the guidelines, and there was nothing unusual.（with mass storage）

I changed a new router these days and changed the Wi-Fi name, which means that RP1 can't connect to Wi-Fi and need to reset Wi-Fi through the computer. 

However, I found that using the Digital Paper App to connect to the Mac via USB failed without any error message.

In addition, using the Digital Paper App to connect via Wi-Fi hotspot or Bluetooth is successful.
ADB is also successful.

Is this problem related to mass storage?

**Comment by HappyZ** [comment]
I updated the code, wiki and the new firmware. Please see https://github.com/HappyZ/dpt-tools/wiki/The-Upgrade-Guide for upgrading instruction.

**Comment by HappyZ** [comment]
@vznoopy not sure if it common here butI found a funny problem regarding "cannot find adb" and "cannot use DPA via usb cable" and "cannot find /dev/tty.usbxxx" on MacOS. It is NOT the problem of the mod, but the problem of the MacOS system... if you unplug the cable, log out, log back in, and plug the cable in, you will be able to connect..

**Comment by HappyZ** [comment]
@tartakis if problem is solved, can you close the issue?

**Comment by tartakis** [comment]
@HappyZ issue resolved, thanks!
