### ISSUE TITLE
official pkg archive (05/18/2019)

### ISSUE THREAD

**Issue by HappyZ** [HappyZ/dpt-tools#92]
Results obtained from curl https://www.sony.net/Products/DigitalPaperSystem/Software/DP/info.xml

As of the day this is created, DPT-RP1 and DPT-CP1 finally have unified version number `1.6.00.15110`.

URI="https://www.sony.net/Products/DigitalPaperSystem/Software/DP/FwUpdater.pkg"

You can flash the officials, after which you might need to reset the device for a clean setup.

For modded official PKGs and other PKGS, please refer to https://github.com/HappyZ/dpt-tools/wiki/PKGs-I-Made/.

**Comment by HappyZ** [comment]
from old firmware to `1.6.00.15110`, following new features added:

　- Opening a page from Table of Content (PDF Bookmark)
　- Document copy on the digital paper unit
　- Opening a page from the page history
　- Zooming in on a document by pinching operation
　- Switching the pen color from “blue/red” to “black/red”
　- Add landscape Graph template
　- Modified the bugs.

**Comment by qz721** [comment]
Have you tried this update on a hacked device? The third-party apps can still run as before? @HappyZ

**Comment by HappyZ** [comment]
Read the update guide in wiki.

**Comment by Enzo-Liu** [comment]
After the upgrade, it can not start the app launcher . (using the `Full system mod for v1.6.00.15110`)
Always displayed `Unfortunately, App Launcher has stopped.`...
And it still has the old apps(like `KOReader`) I installed. 

So I think maybe it has not wiped the old system data?

I will try to get into diagnose and do a factory reset latter...

**Comment by HappyZ** [comment]
@Enzo-Liu do https://github.com/HappyZ/dpt-tools/wiki/Suggested-Launcher-Mod

Key steps are to on `/data/system/ExtMgr.db` and `/data/system/ExtMgr.db-journal`

Essentially, you need to follow the wiki updates Method 1

**Comment by Enzo-Liu** [comment]
Many thanks!
After getting `adb`, just apply the method you mentioned, and everything fixed.

**Comment by alps2006** [comment]
@HappyZ

I  referred following wiki to upgrade my dpt1 to 1.6.00.15110.

>Method 1
>This method should not wipe your apps and data, but always remember to backup first.
>Step 1: do the official update (you can only do it exactly ONCE). It will remove adb functions and AppLauncher will likely crash.
>Step 2: re-do the 3rd and 4th step from this guide

I  found  a problem that don't list devices with command `adb devices`. 
Eventually, I resolved it by `re-do the 2nd and 3rd and 4th step from this guide`

I guess my cracked version is too old.

**Comment by ghostwheel** [comment]
I noticed that the Android version is Lollipop. Was 1.4 also Lollipop?

**Comment by HappyZ** [comment]
> @HappyZ
> 
> I referred following wiki to upgrade my dpt1 to 1.6.00.15110.
> 
> > Method 1
> > This method should not wipe your apps and data, but always remember to backup first.
> > Step 1: do the official update (you can only do it exactly ONCE). It will remove adb functions and AppLauncher will likely crash.
> > Step 2: re-do the 3rd and 4th step from this guide
> 
> I found a problem that don't list devices with command `adb devices`.
> Eventually, I resolved it by `re-do the 2nd and 3rd and 4th step from this guide`
> 
> I guess my cracked version is too old.

You used the official update and thus adb were removed. That is why you have to re-do 3 and 4. I don't think you need to root and get diagnosis mode again.


> I noticed that the Android version is Lollipop. Was 1.4 also Lollipop?

The version didn't change. 1.4 and 1.6 are the same Android 5.1.

**Comment by lisai9093** [comment]
URI="https://www.sony.net/Products/DigitalPaperSystem/Software/DP/FwUpdater.pkg" no longer give you 1.6.00.15110 version. Instead it will only give you 1.4.01.16100 for RP1

**Comment by HappyZ** [comment]
> URI="https://www.sony.net/Products/DigitalPaperSystem/Software/DP/FwUpdater.pkg" no longer give you 1.6.00.15110 version. Instead it will only give you 1.4.01.16100 for RP1

interesting.. did they lifted the update as there might be some problems?? hopefully someone who has time will correct the address for us; i don't have time for it now

**Comment by pwliao** [comment]
1.6.00.15110 is not available now.
There is an announcement on sony's website.
https://www.sony.jp/digital-paper/info/20190617.html
https://pro.sony/cn/service/20190627.shtml

**Comment by HappyZ** [comment]
> 1.6.00.15110 is not available now.
> There is an announcement on sony's website.
> https://www.sony.jp/digital-paper/info/20190617.html
> https://pro.sony/cn/service/20190627.shtml

thanks, i've updated wiki to alert people

**Comment by pwliao** [comment]
Sony released `1.6.02.06240` firmware for DPT-RP1 and DPT-CP1.

**Comment by DeeDive** [comment]
1.6.02.06240 is available

**Comment by HappyZ** [comment]
I'm aware of it. I won't be available until the end of July tho.

**Comment by richardhyy** [comment]
I’m on 1.6.02.15110(rooted) now. Can I upgrade to 06240 using the official pig? 
:)

**Comment by HappyZ** [comment]
you can try it at your own risk. otherwise, please patiently wait for someone else's confirmation. I don't know what has been changed yet. We only know the new version, if flashed, didn't fix the bug that enables diagnosis mode.
