### ISSUE TITLE
How to Remove Cyan Background of Framebuffer Rendering

### ISSUE THREAD

**Issue by kitsek** [HappyZ/dpt-tools#93]
To capture a snapshot in DPA, u will notice the background of white colored App is Cyan.

**Comment by HappyZ** [comment]
can you attach an image? huh, i didn't notice this change - mine seems fine

<img src=https://user-images.githubusercontent.com/4674090/57975889-ff7eca00-7998-11e9-88e8-9c21a2deed11.png width="300" />

**Comment by kitsek** [comment]
![xxx2](https://user-images.githubusercontent.com/19667884/57978700-b6844f80-7a44-11e9-9aba-6d99570205c2.png)
Well the color is quite different if directly make a snapshot of DPA window instead of "save as"

**Comment by zhangyl08** [comment]
Well the color is quite different on my computer, but in github webpage, it seems...
Maybe I'll compare it with another computer

**Comment by HappyZ** [comment]
huh interesting.. i'll try it sometime later

**Comment by kitsek** [comment]
> huh interesting.. i'll try it sometime later
Thank you.
I reckon the direct way to check it out is to print framebuffer's output into png, see what exactly it is.
And another question, is there a way to adjust Contrast/gamma of the display?

**Comment by HappyZ** [comment]
I guess you can just install some Android screen adjustment tool/app to do it.

**Comment by kitsek** [comment]
> I guess you can just install some Android screen adjustment tool/app to do it.

tried, not working at all. this device seems to be unique to normal android devices
