### ISSUE TITLE
factory reset not work

### ISSUE THREAD

**Issue by qiebin** [HappyZ/dpt-tools#95]
thanks for your great work!
I've cracked it step by step, but because of the heavy power consumption, I've changed back to the official. Now I've upgraded the latest version. But when I go through the initialization operation in the settings, the upper left corner will show three squares, and then stop. Nothing happens. Can you give me some advice?

**Comment by HappyZ** [comment]
are you able to get into diagnosis mode?

**Comment by qiebin** [comment]
Yes, I can get into diagnosis mode through scripts. 
Everything looks the same as the official excepted the reset function. Should I execute the reset through script?

**Comment by HappyZ** [comment]
yea, you can just use the reset script in diagnosis as well

**Comment by y1quan** [comment]
Thank you, HappeZ. You taught me a lot.
I don't know what's wrong with my CP1. 
I cannot use the reset script in settings
I cannot use the reset script in diagnosis as well

root #: /usr/local/bin/factory_reset.sh
: line 28: DIAG_get_setid: not found
NG
root@FPX-1010:~# 

I can FW

I can Python dpt-tools.py--diagnosis

But it can't be reset.

And I reinstalled the system several times
Use system. img or FwUpdater. PKG
From Official CP1 v1.4.02.09061 from mega.nz and
Official CP1/RP1 v1.6.00.15110 from mega.nz
But the result is the same, although the system has been installed successfully.
But I can't use "/usr/local/bin/factory_reset.sh" in diagnosis.
Does that mean I can't clean up the root system right now?
Can't I go back to the undisturbed state?
I want to go back to the official system, no root, no unlock, can you help me?

I also have the "AppLauncher has stopped" situation.
When I use your launcher_mod.tar.gz, AppLauncher runs.
But when I delete the Android Settings and Apps folders of etc/dp_extensions from the compressed package and run the command again, it still says "AppLauncher has stopped"

My English is not good. The above content is translated from Baidu.

Thanks again.

**Comment by qiebin** [comment]
after enter the serial port”/dev/tty”, it says failed to login.where can I find the serial port?  I’m not familiar with this, can you give me more details steps?


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by y1quan** [comment]
> after enter the serial port”/dev/tty”, it says failed to login.where can I find the serial port? I’m not familiar with this, can you give me more details steps?
> 
> :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

IF you use MAC，you can use APP 《CoolTerm》
Select your serial port in Options Port and you can find it in the triangle on the right.

**Comment by qiebin** [comment]
I also encountered the problem of launcher stopping at that time. I remember deleting the new application and restarting the Sony paper and the launcher works. Sorry, I can't remember clearly. but also can’t do factory reset.


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by ya0guang** [comment]
I have the same problem.
I'm using Win10 and when I try to reset in diagnosis mod, it says this:
`root #: /usr/local/bin/factory_reset.sh  
: line 28: DIAG_get_setid: not found  
NG`

And same problem on Applauncher crash.

**Comment by HappyZ** [comment]
to run the reset script, you need to first initiated it via DIAG_functions by `. DIAG_functions` I believe. the script should be in`/usr/local/bin` as well. srry i don't have the device in hand right now

**Comment by HappyZ** [comment]
you can try to find where the file is by `grep -nr "DIAG_get_setid " /usr/local/bin`

**Comment by HappyZ** [comment]
@y1quan reinstalling the system does not help because it is crashed due to user data partition. You have to reset the device. I don't have the device in hand, but if you can boot into normal system, please use `fw` to enable `adb` first, and then apply `suggested AppLauncher mods` as written in wiki. The crash will be gone. 

Then, if you still have the `waiting button` issue, wait for you can cancel it, and create a folder named `Note` to prevent the wait button. And you finally, you should be able to reset through the system menu.

**Comment by HappyZ** [comment]
let me know if your problems are resolved @y1quan @ya0guang @wulinhaobing

**Comment by qiebin** [comment]
Is system menu reset the same as the script reset in diagnosis mode?


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by y1quan** [comment]
> let me know if your problems are resolved @y1quan @ya0guang @wulinhaobing

I didn't find the default launcher_mod.tar.gz, no apps, no Android settings.
Nor is it known how to run the reset script.
Can you be more specific about reset script?

**Comment by HappyZ** [comment]
> Is system menu reset the same as the script reset in diagnosis mode?
> 
> :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

yes

**Comment by qiebin** [comment]
when reset through system menu,it restarts and quickly stopped,seems something wrong with the system partition.because everything works fine,I give up reset temporarily.thx all the same


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by HappyZ** [comment]
srry to hear that, may I ask if you were using windows or macos? for windows if you hacked in earlier days without the simple method, there's a small chance the update script is forced to reformat with `/r/n` which may cause a problem. otherwise i honestly have no idea why it halts - causality of system partition issue is unclear to me

i'll write a wiki page about resetting in diagnosis mode @y1quan this weekend

**Comment by qiebin** [comment]
I'm using macOS, Maybe I will try to crack it again later.Many thanks.

**Comment by HappyZ** [comment]
https://github.com/HappyZ/dpt-tools/wiki/Ways-of-Factory-Reset
