### ISSUE TITLE
Mods to the official apps?

### ISSUE THREAD

**Issue by junrenshi** [HappyZ/dpt-tools#96]
Since we now have access to the apk files of the official apps, I am wondering whether it is possible to modify the apps.   One particular mod I would like to have is to change the way of toggling the menu bar:

Currently, touching the screen anywhere toggles the the menu bar.  I find the behavior distressing.  It would be better if the menu bar is toggled only when the top portion of the screen is touched.

Can this be done by hacking the apk files?

**Comment by kitsek** [comment]
It's illegal, violation of Sony's Copyright.
No binary patch to sony's app is allowed.

U can do it privately only restricted by your own usage. But if made public, troubles will come to u.

**Comment by junrenshi** [comment]
Yes, it would be  illegal if you distribute a modified binary.  Just figuring it out and publishing a howto  should be perfectly legal.  Correct me if I were wrong.

**Comment by kitsek** [comment]
> Yes, it would be illegal if you distribute a modified binary. Just figuring it out and publishing a howto should be perfectly legal. Correct me if I were wrong.

Yes, you are right.
But if that happens, this repo might be facing a DCMA take-down if sony got noticed.

better off posting such info in personal blogs, not github.

**Comment by HappyZ** [comment]
thanks @zhangyl08 

and @junrenshi, im not interested in it. technically, it's just Android apk, but without source it will be very difficult to change the app itself. you should contact them to get a better app, not through hacks
