### ISSUE TITLE
Upgrading through Method 3 may cause firmware crush 

### ISSUE THREAD

**Issue by ya0guang** [HappyZ/dpt-tools#97]
First, thank HappyZ for the upgrade of the root guide to the new firmware!
I've root my device with this repo successfully before. I decided to upgrade it following the Method 3 in The Upgrade Guide.
Note that when I tried to upgrade with Method 2, the python script says this:

> [error] HTTPSConnectionPool(host='digitalpaper.local', port=8443): Max retries exceeded with url: /auth/nonce/d3f96579-7499-4f19-a01e-8b9f9729cb07 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000298DAA39588>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[error] cannot get nonce
[error] Cannot authenticate. Make sure your id, key, and ip addresses are correct.

So I followed Method 3 then. I encountered the problem Halting at waiting.. with a cancel button (actually it says Please wait...) and AppLauncher crash after upgrade and I re-done the launcher mod to solve the latter problem. But pressing reset button after taping "Cancel" have no help. I also tried factory_reset.sh script in diagnosis modem but it says:

> root #: /usr/local/bin/factory_reset.sh
: line 28: DIAG_get_setid: not found
NG

My Digital Paper App can still connect to my DPT-RP1 but there is an error when synchronizing: Cannot find folder "Note" in digital paper, just like reason of the problem presented in The Upgrade Guide.

I want  to make it all right, no matter to the official system or the rooted system :) May someone help me?

**Comment by ya0guang** [comment]
Would refreshing the new official PKG work for me? If yes, then I can first do it and then root it again.

**Comment by ya0guang** [comment]
I fixed it.
The problem is because I was in a hurry :( 
You should wait until the “Please wait” dialog box disappear and then you can press home and the Launcher will appear again. You may create a new note to make "Note" folder to be created. (If you've fixed AppLauncher crash problem before)
Then reboot it, all things right :)
Great thanks to HappyZ again and apologize for my impatience.

**Comment by HappyZ** [comment]
yea you have to be patient to wait for it canceled.. it takes about 1min or so to me; closed as it is no longer a problem
